// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actor_audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countActorAudit = `-- name: CountActorAudit :one

SELECT COUNT(*)
FROM actor_audit
WHERE (?1 IS NULL OR actor_user_id = ?1)
  AND (?2 IS NULL OR actor_kind = ?2)
  AND (?3 IS NULL OR event = ?3)
  AND (?4 IS NULL OR resource_type = ?4)
  AND (?5 IS NULL OR resource_id = ?5)
  AND (?6 IS NULL OR created_at >= ?6)
  AND (?7 IS NULL OR created_at < ?7)
`

type CountActorAuditParams struct {
	ActorUserID  interface{}
	ActorKind    interface{}
	Event        interface{}
	ResourceType interface{}
	ResourceID   interface{}
	SinceUnix    interface{}
	UntilUnix    interface{}
}

// Counterpart to ListActorAudit -- must apply identical WHERE so
// pagination totals match the visible rows.
func (q *Queries) CountActorAudit(ctx context.Context, arg CountActorAuditParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActorAudit,
		arg.ActorUserID,
		arg.ActorKind,
		arg.Event,
		arg.ResourceType,
		arg.ResourceID,
		arg.SinceUnix,
		arg.UntilUnix,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActorAudit = `-- name: InsertActorAudit :exec

INSERT INTO actor_audit (
    actor_user_id, actor_kind, actor_name,
    event, resource_type, resource_id, details_json
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7
)
`

type InsertActorAuditParams struct {
	ActorUserID  sql.NullInt64
	ActorKind    string
	ActorName    string
	Event        string
	ResourceType string
	ResourceID   sql.NullString
	DetailsJson  string
}

// actor_audit: append-only event log for admin actions that aren't
// otherwise audited (scan start, restart, settings PUT, storage location
// PUT, prune execute, pairing lifecycle). Mirrors companion_pairing_audit's
// shape but cross-cutting: one table, not per-domain.
//
// actor_kind + actor_name carry the display identity. actor_user_id
// (nullable) carries the FK to users when one exists, so admin/audit
// views can filter "everything by user X" or "everything the system did"
// without parsing the name string.
//
// All positional params use bare ?1/?2 (not sqlc.arg) per AGENTS.md's
// "SQL Syntax Traps" note.
func (q *Queries) InsertActorAudit(ctx context.Context, arg InsertActorAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertActorAudit,
		arg.ActorUserID,
		arg.ActorKind,
		arg.ActorName,
		arg.Event,
		arg.ResourceType,
		arg.ResourceID,
		arg.DetailsJson,
	)
	return err
}

const listActorAudit = `-- name: ListActorAudit :many

SELECT id, actor_user_id, actor_kind, actor_name,
       event, resource_type, resource_id, details_json, created_at
FROM actor_audit
WHERE (?3 IS NULL OR actor_user_id = ?3)
  AND (?4 IS NULL OR actor_kind = ?4)
  AND (?5 IS NULL OR event = ?5)
  AND (?6 IS NULL OR resource_type = ?6)
  AND (?7 IS NULL OR resource_id = ?7)
  AND (?8 IS NULL OR created_at >= ?8)
  AND (?9 IS NULL OR created_at < ?9)
ORDER BY created_at DESC, id DESC
LIMIT ?1 OFFSET ?2
`

type ListActorAuditParams struct {
	Limit        int64
	Offset       int64
	ActorUserID  interface{}
	ActorKind    interface{}
	Event        interface{}
	ResourceType interface{}
	ResourceID   interface{}
	SinceUnix    interface{}
	UntilUnix    interface{}
}

// Admin/audit list view. Offset pagination -- audit volume is bounded
// (one entry per admin action), so pagination drift isn't the unbounded-
// table hazard it would be for a per-row event stream like audit_queue.
// Filters are all sqlc.narg so a caller can filter on any subset
// (a user-scoped "what did I do" view is actor_user_id + maybe event).
func (q *Queries) ListActorAudit(ctx context.Context, arg ListActorAuditParams) ([]ActorAudit, error) {
	rows, err := q.db.QueryContext(ctx, listActorAudit,
		arg.Limit,
		arg.Offset,
		arg.ActorUserID,
		arg.ActorKind,
		arg.Event,
		arg.ResourceType,
		arg.ResourceID,
		arg.SinceUnix,
		arg.UntilUnix,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActorAudit{}
	for rows.Next() {
		var i ActorAudit
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorKind,
			&i.ActorName,
			&i.Event,
			&i.ResourceType,
			&i.ResourceID,
			&i.DetailsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
