// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_telemetry.sql

package sqlcgen

import (
	"context"
)

const deleteAgentScratchTelemetry = `-- name: DeleteAgentScratchTelemetry :exec
DELETE FROM agent_scratch_telemetry
WHERE agent_id = ?1
`

func (q *Queries) DeleteAgentScratchTelemetry(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentScratchTelemetry, agentID)
	return err
}

const getAgentScratchTelemetry = `-- name: GetAgentScratchTelemetry :one
SELECT agent_id, client_version, timestamp_unix, mount_path, total_bytes, free_bytes, used_bytes, mirrors_size_bytes, render_cache_size_bytes, proxies_size_bytes, prunable_bytes, last_prune_timestamp_unix, last_reclaimed_bytes, last_prune_duration_ms, pruned_item_counts, updated_at
FROM agent_scratch_telemetry
WHERE agent_id = ?1
`

func (q *Queries) GetAgentScratchTelemetry(ctx context.Context, agentID string) (AgentScratchTelemetry, error) {
	row := q.db.QueryRowContext(ctx, getAgentScratchTelemetry, agentID)
	var i AgentScratchTelemetry
	err := row.Scan(
		&i.AgentID,
		&i.ClientVersion,
		&i.TimestampUnix,
		&i.MountPath,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.UsedBytes,
		&i.MirrorsSizeBytes,
		&i.RenderCacheSizeBytes,
		&i.ProxiesSizeBytes,
		&i.PrunableBytes,
		&i.LastPruneTimestampUnix,
		&i.LastReclaimedBytes,
		&i.LastPruneDurationMs,
		&i.PrunedItemCounts,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentScratchTelemetry = `-- name: ListAgentScratchTelemetry :many
SELECT agent_id, client_version, timestamp_unix, mount_path, total_bytes, free_bytes, used_bytes, mirrors_size_bytes, render_cache_size_bytes, proxies_size_bytes, prunable_bytes, last_prune_timestamp_unix, last_reclaimed_bytes, last_prune_duration_ms, pruned_item_counts, updated_at
FROM agent_scratch_telemetry
ORDER BY agent_id ASC
`

func (q *Queries) ListAgentScratchTelemetry(ctx context.Context) ([]AgentScratchTelemetry, error) {
	rows, err := q.db.QueryContext(ctx, listAgentScratchTelemetry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentScratchTelemetry{}
	for rows.Next() {
		var i AgentScratchTelemetry
		if err := rows.Scan(
			&i.AgentID,
			&i.ClientVersion,
			&i.TimestampUnix,
			&i.MountPath,
			&i.TotalBytes,
			&i.FreeBytes,
			&i.UsedBytes,
			&i.MirrorsSizeBytes,
			&i.RenderCacheSizeBytes,
			&i.ProxiesSizeBytes,
			&i.PrunableBytes,
			&i.LastPruneTimestampUnix,
			&i.LastReclaimedBytes,
			&i.LastPruneDurationMs,
			&i.PrunedItemCounts,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentScratchTelemetry = `-- name: UpsertAgentScratchTelemetry :one
INSERT INTO agent_scratch_telemetry (
    agent_id,
    client_version,
    timestamp_unix,
    mount_path,
    total_bytes,
    free_bytes,
    used_bytes,
    mirrors_size_bytes,
    render_cache_size_bytes,
    proxies_size_bytes,
    prunable_bytes,
    last_prune_timestamp_unix,
    last_reclaimed_bytes,
    last_prune_duration_ms,
    pruned_item_counts,
    updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10, ?11,
    ?12, ?13, ?14, ?15,
    unixepoch()
)
ON CONFLICT (agent_id) DO UPDATE SET
    client_version = excluded.client_version,
    timestamp_unix = excluded.timestamp_unix,
    mount_path = excluded.mount_path,
    total_bytes = excluded.total_bytes,
    free_bytes = excluded.free_bytes,
    used_bytes = excluded.used_bytes,
    mirrors_size_bytes = excluded.mirrors_size_bytes,
    render_cache_size_bytes = excluded.render_cache_size_bytes,
    proxies_size_bytes = excluded.proxies_size_bytes,
    prunable_bytes = excluded.prunable_bytes,
    last_prune_timestamp_unix = excluded.last_prune_timestamp_unix,
    last_reclaimed_bytes = excluded.last_reclaimed_bytes,
    last_prune_duration_ms = excluded.last_prune_duration_ms,
    pruned_item_counts = excluded.pruned_item_counts,
    updated_at = unixepoch()
RETURNING agent_id, client_version, timestamp_unix, mount_path, total_bytes, free_bytes, used_bytes, mirrors_size_bytes, render_cache_size_bytes, proxies_size_bytes, prunable_bytes, last_prune_timestamp_unix, last_reclaimed_bytes, last_prune_duration_ms, pruned_item_counts, updated_at
`

type UpsertAgentScratchTelemetryParams struct {
	AgentID                string
	ClientVersion          string
	TimestampUnix          int64
	MountPath              string
	TotalBytes             int64
	FreeBytes              int64
	UsedBytes              int64
	MirrorsSizeBytes       int64
	RenderCacheSizeBytes   int64
	ProxiesSizeBytes       int64
	PrunableBytes          int64
	LastPruneTimestampUnix int64
	LastReclaimedBytes     int64
	LastPruneDurationMs    int64
	PrunedItemCounts       string
}

func (q *Queries) UpsertAgentScratchTelemetry(ctx context.Context, arg UpsertAgentScratchTelemetryParams) (AgentScratchTelemetry, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentScratchTelemetry,
		arg.AgentID,
		arg.ClientVersion,
		arg.TimestampUnix,
		arg.MountPath,
		arg.TotalBytes,
		arg.FreeBytes,
		arg.UsedBytes,
		arg.MirrorsSizeBytes,
		arg.RenderCacheSizeBytes,
		arg.ProxiesSizeBytes,
		arg.PrunableBytes,
		arg.LastPruneTimestampUnix,
		arg.LastReclaimedBytes,
		arg.LastPruneDurationMs,
		arg.PrunedItemCounts,
	)
	var i AgentScratchTelemetry
	err := row.Scan(
		&i.AgentID,
		&i.ClientVersion,
		&i.TimestampUnix,
		&i.MountPath,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.UsedBytes,
		&i.MirrorsSizeBytes,
		&i.RenderCacheSizeBytes,
		&i.ProxiesSizeBytes,
		&i.PrunableBytes,
		&i.LastPruneTimestampUnix,
		&i.LastReclaimedBytes,
		&i.LastPruneDurationMs,
		&i.PrunedItemCounts,
		&i.UpdatedAt,
	)
	return i, err
}
