// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package sqlcgen

import (
	"context"
)

const deleteAppSetting = `-- name: DeleteAppSetting :exec
DELETE FROM app_settings WHERE key = ?1
`

// "Revert to config" deletes the row -- this is what makes provenance
// recoverable rather than merely resettable to some other stored value.
func (q *Queries) DeleteAppSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteAppSetting, key)
	return err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, is_secret, updated_at, updated_by
FROM app_settings
ORDER BY key
`

// The resolver (internal/settings) loads the whole table once at startup
// and on every PUT; the table is expected to stay small (one row per
// overridden field, never one row per node), so no pagination.
func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSetting = `-- name: UpsertAppSetting :one
INSERT INTO app_settings (key, value, is_secret, updated_at, updated_by)
VALUES (?1, ?2, ?3, unixepoch(), ?4)
ON CONFLICT (key) DO UPDATE SET
    value = excluded.value,
    is_secret = excluded.is_secret,
    updated_at = unixepoch(),
    updated_by = excluded.updated_by
RETURNING key, value, is_secret, updated_at, updated_by
`

type UpsertAppSettingParams struct {
	Key       string
	Value     string
	IsSecret  int64
	UpdatedBy string
}

// The row's mere existence is the override -- callers pass "" for value
// exactly when the operator wants "explicitly empty", never as a signal to
// skip the write. See internal/settings/resolver.go for why an empty
// override still beats a populated config/env base value. updated_at is
// set via unixepoch() here, not passed from Go, matching every other
// UPDATE/upsert in this package (docs/schema.md fix #5).
func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertAppSetting,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.UpdatedBy,
	)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
