// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companion_pairing.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countDevicePairings = `-- name: CountDevicePairings :one
SELECT COUNT(*) FROM device_pairings
`

func (q *Queries) CountDevicePairings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevicePairings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPairingAudit = `-- name: CountPairingAudit :one
SELECT COUNT(*) FROM companion_pairing_audit WHERE pairing_id = ?1
`

func (q *Queries) CountPairingAudit(ctx context.Context, pairingID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPairingAudit, pairingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevicePairing = `-- name: CreateDevicePairing :one
INSERT INTO device_pairings (
    agent_id, friendly_label, created_at, created_by, qr_svg
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
RETURNING id, agent_id, friendly_label, created_at, created_by, revoked_at, qr_svg
`

type CreateDevicePairingParams struct {
	AgentID       string
	FriendlyLabel string
	CreatedAt     int64
	CreatedBy     string
	QrSvg         []byte
}

// Companion pairing queries. The handlers in internal/httpapi/companion_pairings.go
// and the KeyLookup callback in internal/pairing/service.go both go through
// these -- no raw SQL outside this file (per the project's sqlc convention,
// documented in CONTRIBUTING.md).
//
// All positional params use bare ?1/?2/?3 (not sqlc.arg(name)) per AGENTS.md's
// "SQL Syntax Traps" note.
// Inserts the pairing row and returns it. The HTTP layer wraps this with
// the matching KEY_MINTED audit insert in the same tx (see pairing.Service).
func (q *Queries) CreateDevicePairing(ctx context.Context, arg CreateDevicePairingParams) (DevicePairing, error) {
	row := q.db.QueryRowContext(ctx, createDevicePairing,
		arg.AgentID,
		arg.FriendlyLabel,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.QrSvg,
	)
	var i DevicePairing
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.FriendlyLabel,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.QrSvg,
	)
	return i, err
}

const createDevicePairingKey = `-- name: CreateDevicePairingKey :one
INSERT INTO device_pairing_keys (
    pairing_id, key_lookup_hash, key_preview, created_at
) VALUES (
    ?1, ?2, ?3, ?4
)
RETURNING id, pairing_id, key_lookup_hash, key_preview, created_at,
          expires_at, revoked_at
`

type CreateDevicePairingKeyParams struct {
	PairingID     int64
	KeyLookupHash string
	KeyPreview    string
	CreatedAt     int64
}

func (q *Queries) CreateDevicePairingKey(ctx context.Context, arg CreateDevicePairingKeyParams) (DevicePairingKey, error) {
	row := q.db.QueryRowContext(ctx, createDevicePairingKey,
		arg.PairingID,
		arg.KeyLookupHash,
		arg.KeyPreview,
		arg.CreatedAt,
	)
	var i DevicePairingKey
	err := row.Scan(
		&i.ID,
		&i.PairingID,
		&i.KeyLookupHash,
		&i.KeyPreview,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDevicePairingByAgentID = `-- name: GetDevicePairingByAgentID :one
SELECT id, agent_id, friendly_label, created_at, created_by, revoked_at, qr_svg
FROM device_pairings
WHERE agent_id = ?1
`

// Used by the handshake's pendingRotation hint to load the pairing by
// the agent_id attached to the request's Principal.
func (q *Queries) GetDevicePairingByAgentID(ctx context.Context, agentID string) (DevicePairing, error) {
	row := q.db.QueryRowContext(ctx, getDevicePairingByAgentID, agentID)
	var i DevicePairing
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.FriendlyLabel,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.QrSvg,
	)
	return i, err
}

const getDevicePairingByID = `-- name: GetDevicePairingByID :one
SELECT id, agent_id, friendly_label, created_at, created_by, revoked_at, qr_svg
FROM device_pairings
WHERE id = ?1
`

func (q *Queries) GetDevicePairingByID(ctx context.Context, id int64) (DevicePairing, error) {
	row := q.db.QueryRowContext(ctx, getDevicePairingByID, id)
	var i DevicePairing
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.FriendlyLabel,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.QrSvg,
	)
	return i, err
}

const getDevicePairingKeyByHash = `-- name: GetDevicePairingKeyByHash :one
SELECT k.id, k.pairing_id, k.key_lookup_hash, k.key_preview, k.created_at,
       k.expires_at, k.revoked_at
FROM device_pairing_keys k
JOIN device_pairings p ON p.id = k.pairing_id
WHERE k.key_lookup_hash = ?1
  AND p.revoked_at IS NULL
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > unixepoch())
LIMIT 1
`

// The hot path: KeyLookup runs this on every authenticated agent request.
// UNIQUE index on key_lookup_hash keeps it O(log n). Active means
// revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now).
func (q *Queries) GetDevicePairingKeyByHash(ctx context.Context, keyLookupHash string) (DevicePairingKey, error) {
	row := q.db.QueryRowContext(ctx, getDevicePairingKeyByHash, keyLookupHash)
	var i DevicePairingKey
	err := row.Scan(
		&i.ID,
		&i.PairingID,
		&i.KeyLookupHash,
		&i.KeyPreview,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDevicePairingKeyByID = `-- name: GetDevicePairingKeyByID :one
SELECT id, pairing_id, key_lookup_hash, key_preview, created_at,
       expires_at, revoked_at
FROM device_pairing_keys
WHERE id = ?1
`

func (q *Queries) GetDevicePairingKeyByID(ctx context.Context, id int64) (DevicePairingKey, error) {
	row := q.db.QueryRowContext(ctx, getDevicePairingKeyByID, id)
	var i DevicePairingKey
	err := row.Scan(
		&i.ID,
		&i.PairingID,
		&i.KeyLookupHash,
		&i.KeyPreview,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertPairingAudit = `-- name: InsertPairingAudit :exec
INSERT INTO companion_pairing_audit (
    pairing_id, actor, event, details, created_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
`

type InsertPairingAuditParams struct {
	PairingID int64
	Actor     string
	Event     string
	Details   string
	CreatedAt int64
}

func (q *Queries) InsertPairingAudit(ctx context.Context, arg InsertPairingAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertPairingAudit,
		arg.PairingID,
		arg.Actor,
		arg.Event,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const listDevicePairings = `-- name: ListDevicePairings :many
SELECT
    p.id, p.agent_id, p.friendly_label, p.created_at, p.created_by, p.revoked_at,
    COALESCE((
        SELECT COUNT(*) FROM device_pairing_keys k
        WHERE k.pairing_id = p.id
          AND k.revoked_at IS NULL
          AND (k.expires_at IS NULL OR k.expires_at > unixepoch())
    ), 0) AS active_key_count,
    (
        SELECT MIN(k.expires_at) FROM device_pairing_keys k
        WHERE k.pairing_id = p.id
          AND k.revoked_at IS NULL
          AND k.expires_at IS NOT NULL
          AND k.expires_at > unixepoch()
    ) AS next_expiry_unix,
    (
        SELECT MAX(k.created_at) FROM device_pairing_keys k
        WHERE k.pairing_id = p.id
    ) AS last_key_at
FROM device_pairings p
ORDER BY p.created_at DESC, p.id DESC
LIMIT ?1 OFFSET ?2
`

type ListDevicePairingsParams struct {
	Limit  int64
	Offset int64
}

type ListDevicePairingsRow struct {
	ID             int64
	AgentID        string
	FriendlyLabel  string
	CreatedAt      int64
	CreatedBy      string
	RevokedAt      sql.NullInt64
	ActiveKeyCount interface{}
	NextExpiryUnix interface{}
	LastKeyAt      interface{}
}

// One row per pairing with a count of currently-active keys (NULL -> 0)
// and the earliest unexpired-but-soon-to-expire key (NULL if all keys
// are permanent or none). Used by the SPA's list view to render the
// grace-window countdown for in-progress rotations.
func (q *Queries) ListDevicePairings(ctx context.Context, arg ListDevicePairingsParams) ([]ListDevicePairingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevicePairings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicePairingsRow{}
	for rows.Next() {
		var i ListDevicePairingsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.FriendlyLabel,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.ActiveKeyCount,
			&i.NextExpiryUnix,
			&i.LastKeyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeysByPairing = `-- name: ListKeysByPairing :many
SELECT id, pairing_id, key_lookup_hash, key_preview, created_at,
       expires_at, revoked_at
FROM device_pairing_keys
WHERE pairing_id = ?1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListKeysByPairing(ctx context.Context, pairingID int64) ([]DevicePairingKey, error) {
	rows, err := q.db.QueryContext(ctx, listKeysByPairing, pairingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevicePairingKey{}
	for rows.Next() {
		var i DevicePairingKey
		if err := rows.Scan(
			&i.ID,
			&i.PairingID,
			&i.KeyLookupHash,
			&i.KeyPreview,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPairingAudit = `-- name: ListPairingAudit :many
SELECT id, pairing_id, actor, event, details, created_at
FROM companion_pairing_audit
WHERE pairing_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2 OFFSET ?3
`

type ListPairingAuditParams struct {
	PairingID int64
	Limit     int64
	Offset    int64
}

// Offset pagination. Audit log for a single pairing is bounded (a few
// hundred events over the lifetime of a device, never tens of thousands),
// so offset drift isn't a concern the way it is for the unbounded
// audit_queue edge-review list.
func (q *Queries) ListPairingAudit(ctx context.Context, arg ListPairingAuditParams) ([]CompanionPairingAudit, error) {
	rows, err := q.db.QueryContext(ctx, listPairingAudit, arg.PairingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanionPairingAudit{}
	for rows.Next() {
		var i CompanionPairingAudit
		if err := rows.Scan(
			&i.ID,
			&i.PairingID,
			&i.Actor,
			&i.Event,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newestActiveKeyForPairing = `-- name: NewestActiveKeyForPairing :one
SELECT k.id, k.pairing_id, k.key_lookup_hash, k.key_preview, k.created_at,
       k.expires_at, k.revoked_at
FROM device_pairing_keys k
WHERE k.pairing_id = ?1
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > unixepoch())
  AND k.id <> ?2
  AND (
    k.created_at > (SELECT created_at FROM device_pairing_keys WHERE id = ?2)
    OR (
      k.created_at = (SELECT created_at FROM device_pairing_keys WHERE id = ?2)
      AND k.id > ?2
    )
  )
ORDER BY k.created_at DESC, k.id DESC
LIMIT 1
`

type NewestActiveKeyForPairingParams struct {
	PairingID int64
	ID        int64
}

// Used by /agent/handshake to find the device's newest unexpired key that
// isn't the one the request used. If the caller is already on the newest
// key, this returns no rows (sqlc will surface sql.ErrNoRows).
func (q *Queries) NewestActiveKeyForPairing(ctx context.Context, arg NewestActiveKeyForPairingParams) (DevicePairingKey, error) {
	row := q.db.QueryRowContext(ctx, newestActiveKeyForPairing, arg.PairingID, arg.ID)
	var i DevicePairingKey
	err := row.Scan(
		&i.ID,
		&i.PairingID,
		&i.KeyLookupHash,
		&i.KeyPreview,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllKeysForPairing = `-- name: RevokeAllKeysForPairing :exec
UPDATE device_pairing_keys
SET revoked_at = ?2
WHERE pairing_id = ?1
  AND revoked_at IS NULL
`

type RevokeAllKeysForPairingParams struct {
	PairingID int64
	RevokedAt sql.NullInt64
}

func (q *Queries) RevokeAllKeysForPairing(ctx context.Context, arg RevokeAllKeysForPairingParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllKeysForPairing, arg.PairingID, arg.RevokedAt)
	return err
}

const revokeDevicePairing = `-- name: RevokeDevicePairing :exec
UPDATE device_pairings
SET revoked_at = ?2
WHERE id = ?1
  AND revoked_at IS NULL
`

type RevokeDevicePairingParams struct {
	ID        int64
	RevokedAt sql.NullInt64
}

// Sets revoked_at on the pairing (does NOT touch keys -- the HTTP layer
// also revokes every key for the pairing in the same tx).
func (q *Queries) RevokeDevicePairing(ctx context.Context, arg RevokeDevicePairingParams) error {
	_, err := q.db.ExecContext(ctx, revokeDevicePairing, arg.ID, arg.RevokedAt)
	return err
}

const setActiveKeyExpirations = `-- name: SetActiveKeyExpirations :exec
UPDATE device_pairing_keys
SET expires_at = ?2
WHERE pairing_id = ?1
  AND revoked_at IS NULL
  AND expires_at IS NULL
`

type SetActiveKeyExpirationsParams struct {
	PairingID int64
	ExpiresAt sql.NullInt64
}

// Rotation: set expires_at on every currently-active key for this pairing
// that doesn't already have one. Idempotent — re-running after the same
// clock has no effect.
func (q *Queries) SetActiveKeyExpirations(ctx context.Context, arg SetActiveKeyExpirationsParams) error {
	_, err := q.db.ExecContext(ctx, setActiveKeyExpirations, arg.PairingID, arg.ExpiresAt)
	return err
}

const updateDevicePairingQRSVG = `-- name: UpdateDevicePairingQRSVG :exec
UPDATE device_pairings
SET qr_svg = ?2
WHERE id = ?1
`

type UpdateDevicePairingQRSVGParams struct {
	ID    int64
	QrSvg []byte
}

func (q *Queries) UpdateDevicePairingQRSVG(ctx context.Context, arg UpdateDevicePairingQRSVGParams) error {
	_, err := q.db.ExecContext(ctx, updateDevicePairingQRSVG, arg.ID, arg.QrSvg)
	return err
}

const getDevicePairingQRSVG = `-- name: GetDevicePairingQRSVG :one
SELECT qr_svg
FROM device_pairings
WHERE id = ?1
`

func (q *Queries) GetDevicePairingQRSVG(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getDevicePairingQRSVG, id)
	var qrSvg []byte
	err := row.Scan(&qrSvg)
	return qrSvg, err
}
