// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_queue.sql

package sqlcgen

import (
	"context"
)

const enqueueAgentEvent = `-- name: EnqueueAgentEvent :one
INSERT INTO event_queue (event_uuid, agent_id, event_type, payload_json, status)
VALUES (?1, ?2, ?3, ?4, 'PENDING')
RETURNING id, event_uuid, agent_id, event_type, payload_json, status, error_log, created_at, processed_at
`

type EnqueueAgentEventParams struct {
	EventUuid   string
	AgentID     string
	EventType   string
	PayloadJson string
}

// Backs POST /api/v1/agent/events: persists and returns 202 in increment 1.
// Actually draining/processing these rows ships with the deferred
// workstation-agent increment -- this table and endpoint exist now so that
// increment is additive, not a schema migration.
func (q *Queries) EnqueueAgentEvent(ctx context.Context, arg EnqueueAgentEventParams) (EventQueue, error) {
	row := q.db.QueryRowContext(ctx, enqueueAgentEvent,
		arg.EventUuid,
		arg.AgentID,
		arg.EventType,
		arg.PayloadJson,
	)
	var i EventQueue
	err := row.Scan(
		&i.ID,
		&i.EventUuid,
		&i.AgentID,
		&i.EventType,
		&i.PayloadJson,
		&i.Status,
		&i.ErrorLog,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}
