// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: local_auth.sql

// Hand-maintained rather than sqlc-generated: sqlc v1.20-v1.31.1 all fail to
// parse the existing companion_pairing.sql subqueries in this environment
// (the parser emits truncated const blocks across many unrelated query
// strings); running `sqlc generate` corrupts files in internal/db/sqlcgen/.
// See User / Session / LoginAudit types' doc comments in models.go for the
// full rationale, and PLAN.md in the repo root for the operational context.
//
// The file's header is preserved as the project's sqlcgen convention so a
// future regeneration can replace the hand-written additions once sqlc's
// parser is fixed or this environment is repaired.
package sqlcgen

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, is_admin, source, created_at, created_by, disabled_at
FROM users
WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, is_admin, source, created_at, created_by, disabled_at
FROM users
WHERE username = ?1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByEmailSource = `-- name: GetUserByEmailSource :one
SELECT id, username, email, password_hash, is_admin, source, created_at, created_by, disabled_at
FROM users
WHERE email = ?1 AND source = ?2
`

type GetUserByEmailSourceParams struct {
	Email  sql.NullString
	Source string
}

func (q *Queries) GetUserByEmailSource(ctx context.Context, arg GetUserByEmailSourceParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailSource, arg.Email, arg.Source)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DisabledAt,
	)
	return i, err
}

const createLocalUser = `-- name: CreateLocalUser :one
INSERT INTO users (
    username, email, password_hash, is_admin, source, created_at, created_by
) VALUES (
    ?1, ?2, ?3, ?4, 'local', ?5, ?6
)
RETURNING id, username, email, password_hash, is_admin, source, created_at, created_by, disabled_at
`

type CreateLocalUserParams struct {
	Username     string
	Email        sql.NullString
	PasswordHash string
	IsAdmin      int64
	CreatedAt    int64
	CreatedBy    string
}

func (q *Queries) CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createLocalUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DisabledAt,
	)
	return i, err
}

const createForwardJITUser = `-- name: CreateForwardJITUser :one
INSERT INTO users (
    username, email, password_hash, is_admin, source, created_at, created_by
) VALUES (
    ?1, ?2, NULL, ?3, 'forward-jit', ?4, ?5
)
RETURNING id, username, email, password_hash, is_admin, source, created_at, created_by, disabled_at
`

type CreateForwardJITUserParams struct {
	Username  string
	Email     sql.NullString
	IsAdmin   int64
	CreatedAt int64
	CreatedBy string
}

func (q *Queries) CreateForwardJITUser(ctx context.Context, arg CreateForwardJITUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createForwardJITUser,
		arg.Username,
		arg.Email,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DisabledAt,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET disabled_at = ?2 WHERE id = ?1
`

type DisableUserParams struct {
	ID         int64
	DisabledAt sql.NullInt64
}

func (q *Queries) DisableUser(ctx context.Context, arg DisableUserParams) error {
	_, err := q.db.ExecContext(ctx, disableUser, arg.ID, arg.DisabledAt)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, is_admin, source, created_at, created_by, disabled_at
FROM users
ORDER BY id ASC
LIMIT ?1 OFFSET ?2
`

type ListUsersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    cookie_id, user_id, created_at, last_seen_at, expires_at,
    idle_expires_at, ip, user_agent
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
RETURNING id, cookie_id, user_id, created_at, last_seen_at, expires_at, idle_expires_at, ip, user_agent, revoked_at
`

type CreateSessionParams struct {
	CookieID      string
	UserID        int64
	CreatedAt     int64
	LastSeenAt    int64
	ExpiresAt     int64
	IdleExpiresAt int64
	Ip            string
	UserAgent     string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.CookieID,
		arg.UserID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CookieID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByCookieID = `-- name: GetSessionByCookieID :one
SELECT id, cookie_id, user_id, created_at, last_seen_at, expires_at, idle_expires_at, ip, user_agent, revoked_at
FROM sessions
WHERE cookie_id = ?1
`

func (q *Queries) GetSessionByCookieID(ctx context.Context, cookieID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByCookieID, cookieID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CookieID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = ?2, idle_expires_at = ?3
WHERE id = ?1 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	ID            int64
	LastSeenAt    int64
	IdleExpiresAt int64
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.ID, arg.LastSeenAt, arg.IdleExpiresAt)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = ?2 WHERE id = ?1
`

type RevokeSessionParams struct {
	ID        int64
	RevokedAt sql.NullInt64
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = ?2 WHERE user_id = ?1 AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	UserID    int64
	RevokedAt sql.NullInt64
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserSessions, arg.UserID, arg.RevokedAt)
	return err
}

const insertLoginAudit = `-- name: InsertLoginAudit :exec
INSERT INTO login_audit (
    user_id, username_presented, source, outcome, ip, user_agent, details, created_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
`

type InsertLoginAuditParams struct {
	UserID            sql.NullInt64
	UsernamePresented string
	Source            string
	Outcome           string
	Ip                string
	UserAgent         string
	Details           string
	CreatedAt         int64
}

func (q *Queries) InsertLoginAudit(ctx context.Context, arg InsertLoginAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginAudit,
		arg.UserID,
		arg.UsernamePresented,
		arg.Source,
		arg.Outcome,
		arg.Ip,
		arg.UserAgent,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}
