// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_audit_read.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countLoginAudit = `-- name: CountLoginAudit :one
SELECT COUNT(*) FROM login_audit
`

func (q *Queries) CountLoginAudit(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoginAudit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listLoginAudit = `-- name: ListLoginAudit :many

SELECT id, user_id, username_presented, source, outcome, ip, user_agent, created_at
FROM login_audit
ORDER BY created_at DESC, id DESC
LIMIT ?1 OFFSET ?2
`

type ListLoginAuditParams struct {
	Limit  int64
	Offset int64
}

type ListLoginAuditRow struct {
	ID                int64
	UserID            sql.NullInt64
	UsernamePresented string
	Source            string
	Outcome           string
	Ip                string
	UserAgent         string
	CreatedAt         int64
}

// login_audit: append-only log of authentication events (PR #407).
// Read by /api/v1/audit?type=login alongside /api/v1/audit?type=activity
// (which reads actor_audit). login_audit is owned by internal/auth/users;
// these queries are kept here so the merged audit route can read both
// tables through the same sqlcgen layer without a second db call site.
//
// All positional params use bare ?1/?2 (not sqlc.arg) per AGENTS.md's
// "SQL Syntax Traps" note.
// Newest-first. Offset pagination -- volume is bounded by authentication
// events (not per-asset), so the drift problem that justifies keyset
// pagination on /api/v1/edges/audit doesn't apply here.
func (q *Queries) ListLoginAudit(ctx context.Context, arg ListLoginAuditParams) ([]ListLoginAuditRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoginAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoginAuditRow{}
	for rows.Next() {
		var i ListLoginAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UsernamePresented,
			&i.Source,
			&i.Outcome,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
