// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_edges_resolve.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const confirmMediaEdge = `-- name: ConfirmMediaEdge :exec
UPDATE media_edges
SET review_state = 'CONFIRMED', reviewed_at = unixepoch(), reviewed_by = ?2, updated_at = unixepoch()
WHERE id = ?1
`

type ConfirmMediaEdgeParams struct {
	ID         int64
	ReviewedBy sql.NullString
}

func (q *Queries) ConfirmMediaEdge(ctx context.Context, arg ConfirmMediaEdgeParams) error {
	_, err := q.db.ExecContext(ctx, confirmMediaEdge, arg.ID, arg.ReviewedBy)
	return err
}

const rejectMediaEdge = `-- name: RejectMediaEdge :exec
UPDATE media_edges
SET review_state = 'REJECTED', reviewed_at = unixepoch(), reviewed_by = ?2, updated_at = unixepoch()
WHERE id = ?1
`

type RejectMediaEdgeParams struct {
	ID         int64
	ReviewedBy sql.NullString
}

func (q *Queries) RejectMediaEdge(ctx context.Context, arg RejectMediaEdgeParams) error {
	_, err := q.db.ExecContext(ctx, rejectMediaEdge, arg.ID, arg.ReviewedBy)
	return err
}

const resolvedEdgeParentMissing = `-- name: ResolvedEdgeParentMissing :one
SELECT parent_missing FROM v_media_edges_resolved WHERE id = ?1
`

// Backs T7's regression guard: v_media_edges_resolved.parent_missing must
// be true for every relationship_type, not just DERIVED_FROM -- the thing
// the spec's deleted trigger (docs/schema.md fix #4) never did.
func (q *Queries) ResolvedEdgeParentMissing(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, resolvedEdgeParentMissing, id)
	var parent_missing bool
	err := row.Scan(&parent_missing)
	return parent_missing, err
}

const upsertMediaEdge = `-- name: UpsertMediaEdge :one
INSERT INTO media_edges (
    source_node_id, target_node_id, relationship_type, confidence, tier,
    resolver, evidence_json, review_state
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
ON CONFLICT (source_node_id, target_node_id, relationship_type) DO UPDATE SET
    confidence    = MAX(excluded.confidence, media_edges.confidence),
    tier          = excluded.tier,
    resolver      = excluded.resolver,
    evidence_json = excluded.evidence_json,
    review_state  = CASE
                        WHEN MAX(excluded.confidence, media_edges.confidence) >= 0.90 THEN 'AUTO_ACCEPTED'
                        ELSE 'NEEDS_REVIEW'
                    END,
    updated_at    = unixepoch()
WHERE media_edges.review_state NOT IN ('CONFIRMED', 'REJECTED')
RETURNING id, source_node_id, target_node_id, relationship_type, confidence,
          tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
          created_at, updated_at
`

type UpsertMediaEdgeParams struct {
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
	Confidence       float64
	Tier             int64
	Resolver         string
	EvidenceJson     string
	ReviewState      string
}

// A human decision outranks any resolver, permanently: the UPDATE branch is
// gated by a WHERE that skips rows already CONFIRMED or REJECTED entirely
// (SQLite's upsert semantics: when the WHERE evaluates false, DO UPDATE is
// skipped and the pre-existing row is returned unmodified). confidence only
// ever increases (MAX), never regresses if a later resolve pass finds a
// weaker signal for the same edge; review_state is recomputed from that
// same MAX'd confidence rather than trusting the just-inserted value, so
// the two can never disagree about which confidence they describe.
func (q *Queries) UpsertMediaEdge(ctx context.Context, arg UpsertMediaEdgeParams) (MediaEdge, error) {
	row := q.db.QueryRowContext(ctx, upsertMediaEdge,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.RelationshipType,
		arg.Confidence,
		arg.Tier,
		arg.Resolver,
		arg.EvidenceJson,
		arg.ReviewState,
	)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.RelationshipType,
		&i.Confidence,
		&i.Tier,
		&i.Resolver,
		&i.EvidenceJson,
		&i.ReviewState,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
