// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_nodes.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const archiveMediaNode = `-- name: ArchiveMediaNode :exec
;

UPDATE media_nodes SET lifecycle_state = 'ARCHIVED', updated_at = unixepoch() WHERE id = ?
`

// Step 1 of a version collision (docs/schema.md fix #3): archive the OLD
// row FIRST, before inserting the new one. The partial unique index
// (WHERE lifecycle_state != 'ARCHIVED') means a live row and a new live
// row can never share file_path even for an instant within the
// transaction -- archiving first, not after, is what keeps that true.
func (q *Queries) ArchiveMediaNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveMediaNode, id)
	return err
}

const getLiveNodeByPath = `-- name: GetLiveNodeByPath :one
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE file_path = ?1 AND lifecycle_state != 'ARCHIVED'
`

// The live-path lookup a scan does for every file: is there already a
// non-archived node at this exact path? Backed by ux_media_nodes_live_path
// (docs/schema.md fix #3).
func (q *Queries) GetLiveNodeByPath(ctx context.Context, filePath string) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, getLiveNodeByPath, filePath)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CameraSerial,
		&i.LensModel,
	)
	return i, err
}

const getMediaNodeByID = `-- name: GetMediaNodeByID :one
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE id = ?1
`

// Includes archived rows, unlike GetLiveNodeByPath -- used to verify a
// superseded node's post-archive state (superseded_by, lifecycle_state).
func (q *Queries) GetMediaNodeByID(ctx context.Context, id int64) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, getMediaNodeByID, id)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CameraSerial,
		&i.LensModel,
	)
	return i, err
}

const getMissingNodeByFastHash = `-- name: GetMissingNodeByFastHash :one
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE fast_hash = ?1 AND lifecycle_state = 'MISSING'
LIMIT 1
`

// Pillar 5 move detection: a file vanished (lifecycle_state='MISSING') and
// a new file elsewhere hashes the same -- likely the same file, moved.
func (q *Queries) GetMissingNodeByFastHash(ctx context.Context, fastHash *string) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, getMissingNodeByFastHash, fastHash)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CameraSerial,
		&i.LensModel,
	)
	return i, err
}

const insertMediaNode = `-- name: InsertMediaNode :one
;

INSERT INTO media_nodes (
    node_uuid, storage_location_id, file_path, file_name, file_ext,
    size_bytes, mtime_unix, fast_hash, full_hash, phash,
    indexing_status, graph_status, lifecycle_state,
    original_document_id, document_id, derived_from_id,
    captured_at_unix, camera_model, filename_stem,
    camera_serial, lens_model,
    first_seen_at, last_seen_at, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15, ?16,
    ?17, ?18, ?19, ?20, ?21,
    unixepoch(), unixepoch(), unixepoch(), unixepoch()
)
RETURNING id, node_uuid, storage_location_id, file_path, file_name, file_ext,
          size_bytes, mtime_unix, fast_hash, full_hash, phash,
          indexing_status, graph_status, lifecycle_state, superseded_by,
          original_document_id, document_id, derived_from_id,
          captured_at_unix, camera_model, filename_stem,
          first_seen_at, last_seen_at, created_at, updated_at,
          camera_serial, lens_model
`

type InsertMediaNodeParams struct {
	NodeUuid           string
	StorageLocationID  int64
	FilePath           string
	FileName           string
	FileExt            string
	SizeBytes          int64
	MtimeUnix          int64
	FastHash           *string
	FullHash           *string
	Phash              sql.NullInt64
	IndexingStatus     string
	GraphStatus        string
	LifecycleState     string
	OriginalDocumentID sql.NullString
	DocumentID         sql.NullString
	DerivedFromID      sql.NullString
	CapturedAtUnix     sql.NullInt64
	CameraModel        sql.NullString
	FilenameStem       sql.NullString
	CameraSerial       sql.NullString
	LensModel          sql.NullString
}

func (q *Queries) InsertMediaNode(ctx context.Context, arg InsertMediaNodeParams) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, insertMediaNode,
		arg.NodeUuid,
		arg.StorageLocationID,
		arg.FilePath,
		arg.FileName,
		arg.FileExt,
		arg.SizeBytes,
		arg.MtimeUnix,
		arg.FastHash,
		arg.FullHash,
		arg.Phash,
		arg.IndexingStatus,
		arg.GraphStatus,
		arg.LifecycleState,
		arg.OriginalDocumentID,
		arg.DocumentID,
		arg.DerivedFromID,
		arg.CapturedAtUnix,
		arg.CameraModel,
		arg.FilenameStem,
		arg.CameraSerial,
		arg.LensModel,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CameraSerial,
		&i.LensModel,
	)
	return i, err
}

const listLiveNodesByDocumentID = `-- name: ListLiveNodesByDocumentID :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE document_id = ?1 AND lifecycle_state != 'ARCHIVED'
`

// Tier-2 xmpOriginalDocumentID resolver: a child's XMP:OriginalDocumentID
// matching a candidate parent's document_id is a near-certain lineage
// signal (confidence 0.95).
func (q *Queries) ListLiveNodesByDocumentID(ctx context.Context, documentID sql.NullString) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CameraSerial,
			&i.LensModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveNodesByFastHash = `-- name: ListLiveNodesByFastHash :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE fast_hash = ?1 AND lifecycle_state != 'ARCHIVED'
`

// T1 (spec 9.5): before assuming two same-fast_hash files at DIFFERENT live
// paths are the same content, the pipeline needs every other live node
// sharing that fast_hash so it can escalate to full_hash and compare.
func (q *Queries) ListLiveNodesByFastHash(ctx context.Context, fastHash *string) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesByFastHash, fastHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CameraSerial,
			&i.LensModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveNodesByFileName = `-- name: ListLiveNodesByFileName :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE file_name = ?1 AND lifecycle_state != 'ARCHIVED'
`

// Look up live media nodes sharing exact file_name for fallback path matching.
func (q *Queries) ListLiveNodesByFileName(ctx context.Context, fileName string) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesByFileName, fileName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CameraSerial,
			&i.LensModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveNodesByFilenameStem = `-- name: ListLiveNodesByFilenameStem :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE filename_stem = ?1 AND lifecycle_state != 'ARCHIVED'
`

// Tier-2 filenameStem resolver: candidate parents sharing a normalized
// filename stem with the child, scored further by capture day / camera /
// directory match in internal/graph.
func (q *Queries) ListLiveNodesByFilenameStem(ctx context.Context, filenameStem sql.NullString) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesByFilenameStem, filenameStem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CameraSerial,
			&i.LensModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaNodes = `-- name: ListMediaNodes :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE lifecycle_state != 'ARCHIVED'
ORDER BY id DESC
LIMIT ?1 OFFSET ?2
`

type ListMediaNodesParams struct {
	Limit  int64
	Offset int64
}

// Backs GET /api/v1/assets. Excludes archived rows by default -- an
// archived node is reachable via its successor's superseded history, not
// the main asset list.
func (q *Queries) ListMediaNodes(ctx context.Context, arg ListMediaNodesParams) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listMediaNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CameraSerial,
			&i.LensModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMediaNodesFiltered = `-- name: CountMediaNodesFiltered :one
SELECT COUNT(*)
FROM media_nodes
WHERE (?1 IS NULL OR lifecycle_state = ?1)
  AND (?2 IS NULL OR camera_model = ?2)
  AND (?3 IS NULL OR graph_status = ?3)
  AND (?4 IS NULL OR storage_location_id = ?4)
`

type CountMediaNodesFilteredParams struct {
	LifecycleState    sql.NullString
	CameraModel       sql.NullString
	GraphStatus       sql.NullString
	StorageLocationID sql.NullInt64
}

func (q *Queries) CountMediaNodesFiltered(ctx context.Context, arg CountMediaNodesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaNodesFiltered,
		arg.LifecycleState,
		arg.CameraModel,
		arg.GraphStatus,
		arg.StorageLocationID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCameraModelFacets = `-- name: ListCameraModelFacets :many
SELECT DISTINCT camera_model
FROM media_nodes
WHERE camera_model IS NOT NULL AND camera_model != '' AND lifecycle_state != 'ARCHIVED'
ORDER BY camera_model ASC
`

func (q *Queries) ListCameraModelFacets(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCameraModelFacets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var camera_model string
		if err := rows.Scan(&camera_model); err != nil {
			return nil, err
		}
		items = append(items, camera_model)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaNodesFiltered = `-- name: ListMediaNodesFiltered :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE (?3 IS NULL OR lifecycle_state = ?3)
  AND (?4 IS NULL OR camera_model = ?4)
  AND (?5 IS NULL OR graph_status = ?5)
  AND (?6 IS NULL OR storage_location_id = ?6)
ORDER BY id DESC
LIMIT ?1 OFFSET ?2
`

type ListMediaNodesFilteredParams struct {
	Limit             int64
	Offset            int64
	LifecycleState    sql.NullString
	CameraModel       sql.NullString
	GraphStatus       sql.NullString
	StorageLocationID sql.NullInt64
}

func (q *Queries) ListMediaNodesFiltered(ctx context.Context, arg ListMediaNodesFilteredParams) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listMediaNodesFiltered,
		arg.Limit,
		arg.Offset,
		arg.LifecycleState,
		arg.CameraModel,
		arg.GraphStatus,
		arg.StorageLocationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CameraSerial,
			&i.LensModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTier3Candidates = `-- name: ListTier3Candidates :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at,
       camera_serial, lens_model
FROM media_nodes
WHERE camera_serial = ?1
  AND captured_at_unix >= ?2
  AND captured_at_unix <= ?3
  AND id <> ?4
  AND lifecycle_state != 'ARCHIVED'
`

type ListTier3CandidatesParams struct {
	CameraSerial     sql.NullString
	CapturedAtUnix   sql.NullInt64
	CapturedAtUnix_2 sql.NullInt64
	ID               int64
}

// Tier-3 spatial-temporal resolver candidate lookup: live nodes sharing
// camera_serial with captured_at_unix within ±2 seconds of a target timestamp,
// excluding a given node ID.
func (q *Queries) ListTier3Candidates(ctx context.Context, arg ListTier3CandidatesParams) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listTier3Candidates,
		arg.CameraSerial,
		arg.CapturedAtUnix,
		arg.CapturedAtUnix_2,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CameraSerial,
			&i.LensModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeMissing = `-- name: MarkNodeMissing :exec
;

UPDATE media_nodes SET lifecycle_state = 'MISSING', updated_at = unixepoch() WHERE id = ?1
`

func (q *Queries) MarkNodeMissing(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markNodeMissing, id)
	return err
}

const markUnseenNodesMissing = `-- name: MarkUnseenNodesMissing :execrows
;

UPDATE media_nodes
SET lifecycle_state = 'MISSING', updated_at = unixepoch()
WHERE storage_location_id = ?1
  AND lifecycle_state = 'ACTIVE'
  AND last_seen_at < ?2
  AND file_path NOT IN (SELECT value FROM json_each(?3));
`

type MarkUnseenNodesMissingParams struct {
	StorageLocationID int64
	LastSeenAt        int64
	JsonEach          interface{}
}

func (q *Queries) MarkUnseenNodesMissing(ctx context.Context, arg MarkUnseenNodesMissingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUnseenNodesMissing, arg.StorageLocationID, arg.LastSeenAt, arg.JsonEach)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rebaseMissingNodePath = `-- name: RebaseMissingNodePath :exec
;

UPDATE media_nodes
SET file_path = ?2, file_name = ?3, storage_location_id = ?4,
    lifecycle_state = 'ACTIVE', mtime_unix = ?5,
    last_seen_at = unixepoch(), updated_at = unixepoch()
WHERE id = ?1
`

type RebaseMissingNodePathParams struct {
	ID                int64
	FilePath          string
	FileName          string
	StorageLocationID int64
	MtimeUnix         int64
}

// Pillar 5 move detection, applied: the id and node_uuid never change, so
// every edge referencing this node (as parent or child) survives the move
// untouched -- no CASCADE, no rewrite needed.
func (q *Queries) RebaseMissingNodePath(ctx context.Context, arg RebaseMissingNodePathParams) error {
	_, err := q.db.ExecContext(ctx, rebaseMissingNodePath,
		arg.ID,
		arg.FilePath,
		arg.FileName,
		arg.StorageLocationID,
		arg.MtimeUnix,
	)
	return err
}

const setSupersededBy = `-- name: SetSupersededBy :exec
;

UPDATE media_nodes SET superseded_by = ?2, updated_at = unixepoch() WHERE id = ?1
`

type SetSupersededByParams struct {
	ID           int64
	SupersededBy sql.NullInt64
}

// Step 3 of a version collision: link the archived row to its successor,
// once the successor's id is known (i.e. after InsertMediaNode).
func (q *Queries) SetSupersededBy(ctx context.Context, arg SetSupersededByParams) error {
	_, err := q.db.ExecContext(ctx, setSupersededBy, arg.ID, arg.SupersededBy)
	return err
}

const touchMediaNode = `-- name: TouchMediaNode :exec
;

UPDATE media_nodes
SET mtime_unix = ?2, last_seen_at = unixepoch(),
    lifecycle_state = CASE WHEN lifecycle_state = 'MISSING' THEN 'ACTIVE' ELSE lifecycle_state END,
    updated_at = unixepoch()
WHERE id = ?1
`

type TouchMediaNodeParams struct {
	ID        int64
	MtimeUnix int64
}

// Same content at the same path, seen again on a later scan. Records that
// and, if the row was MISSING (a file re-created at its old path), reactivates
// it in place -- a MISSING row found alive again is not a version collision
// and must not stay MISSING.
func (q *Queries) TouchMediaNode(ctx context.Context, arg TouchMediaNodeParams) error {
	_, err := q.db.ExecContext(ctx, touchMediaNode, arg.ID, arg.MtimeUnix)
	return err
}

const updateMediaNodeFullHash = `-- name: UpdateMediaNodeFullHash :exec
;

UPDATE media_nodes SET full_hash = ?2, indexing_status = 'INDEXED_FULL', updated_at = unixepoch() WHERE id = ?1
`

type UpdateMediaNodeFullHashParams struct {
	ID       int64
	FullHash *string
}

// Escalation path for T1: computed lazily, only when fast_hash collides
// with another live node or the file lives on a TIER3_MASTER_ARCHIVE
// location (docs/schema.md fix #8's full_hash policy).
func (q *Queries) UpdateMediaNodeFullHash(ctx context.Context, arg UpdateMediaNodeFullHashParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaNodeFullHash, arg.ID, arg.FullHash)
	return err
}

const updateMediaNodeGraphStatus = `-- name: UpdateMediaNodeGraphStatus :exec
;

UPDATE media_nodes SET graph_status = ?2, updated_at = unixepoch() WHERE id = ?1
`

type UpdateMediaNodeGraphStatusParams struct {
	ID          int64
	GraphStatus string
}

func (q *Queries) UpdateMediaNodeGraphStatus(ctx context.Context, arg UpdateMediaNodeGraphStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaNodeGraphStatus, arg.ID, arg.GraphStatus)
	return err
}
