// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_nodes.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const archiveMediaNode = `-- name: ArchiveMediaNode :exec
UPDATE media_nodes SET lifecycle_state = 'ARCHIVED', updated_at = unixepoch() WHERE id = ?1
`

// Step 1 of a version collision (docs/schema.md fix #3): archive the OLD
// row FIRST, before inserting the new one. The partial unique index
// (WHERE lifecycle_state != 'ARCHIVED') means a live row and a new live
// row can never share file_path even for an instant within the
// transaction -- archiving first, not after, is what keeps that true.
func (q *Queries) ArchiveMediaNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveMediaNode, id)
	return err
}

const getLiveNodeByPath = `-- name: GetLiveNodeByPath :one
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at
FROM media_nodes
WHERE file_path = ?1 AND lifecycle_state != 'ARCHIVED'
`

// The live-path lookup a scan does for every file: is there already a
// non-archived node at this exact path? Backed by ux_media_nodes_live_path
// (docs/schema.md fix #3).
func (q *Queries) GetLiveNodeByPath(ctx context.Context, filePath string) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, getLiveNodeByPath, filePath)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaNodeByID = `-- name: GetMediaNodeByID :one
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at
FROM media_nodes
WHERE id = ?1
`

// Includes archived rows, unlike GetLiveNodeByPath -- used to verify a
// superseded node's post-archive state (superseded_by, lifecycle_state).
func (q *Queries) GetMediaNodeByID(ctx context.Context, id int64) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, getMediaNodeByID, id)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMissingNodeByFastHash = `-- name: GetMissingNodeByFastHash :one
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at
FROM media_nodes
WHERE fast_hash = ?1 AND lifecycle_state = 'MISSING'
LIMIT 1
`

// Pillar 5 move detection: a file vanished (lifecycle_state='MISSING') and
// a new file elsewhere hashes the same -- likely the same file, moved.
func (q *Queries) GetMissingNodeByFastHash(ctx context.Context, fastHash *string) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, getMissingNodeByFastHash, fastHash)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMediaNode = `-- name: InsertMediaNode :one
INSERT INTO media_nodes (
    node_uuid, storage_location_id, file_path, file_name, file_ext,
    size_bytes, mtime_unix, fast_hash, full_hash, phash,
    indexing_status, graph_status, lifecycle_state,
    original_document_id, document_id, derived_from_id,
    captured_at_unix, camera_model, filename_stem,
    first_seen_at, last_seen_at, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15, ?16,
    ?17, ?18, ?19,
    unixepoch(), unixepoch(), unixepoch(), unixepoch()
)
RETURNING id, node_uuid, storage_location_id, file_path, file_name, file_ext,
          size_bytes, mtime_unix, fast_hash, full_hash, phash,
          indexing_status, graph_status, lifecycle_state, superseded_by,
          original_document_id, document_id, derived_from_id,
          captured_at_unix, camera_model, filename_stem,
          first_seen_at, last_seen_at, created_at, updated_at
`

type InsertMediaNodeParams struct {
	NodeUuid           string
	StorageLocationID  int64
	FilePath           string
	FileName           string
	FileExt            string
	SizeBytes          int64
	MtimeUnix          int64
	FastHash           *string
	FullHash           *string
	Phash              sql.NullInt64
	IndexingStatus     string
	GraphStatus        string
	LifecycleState     string
	OriginalDocumentID sql.NullString
	DocumentID         sql.NullString
	DerivedFromID      sql.NullString
	CapturedAtUnix     sql.NullInt64
	CameraModel        sql.NullString
	FilenameStem       sql.NullString
}

func (q *Queries) InsertMediaNode(ctx context.Context, arg InsertMediaNodeParams) (MediaNode, error) {
	row := q.db.QueryRowContext(ctx, insertMediaNode,
		arg.NodeUuid,
		arg.StorageLocationID,
		arg.FilePath,
		arg.FileName,
		arg.FileExt,
		arg.SizeBytes,
		arg.MtimeUnix,
		arg.FastHash,
		arg.FullHash,
		arg.Phash,
		arg.IndexingStatus,
		arg.GraphStatus,
		arg.LifecycleState,
		arg.OriginalDocumentID,
		arg.DocumentID,
		arg.DerivedFromID,
		arg.CapturedAtUnix,
		arg.CameraModel,
		arg.FilenameStem,
	)
	var i MediaNode
	err := row.Scan(
		&i.ID,
		&i.NodeUuid,
		&i.StorageLocationID,
		&i.FilePath,
		&i.FileName,
		&i.FileExt,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.FastHash,
		&i.FullHash,
		&i.Phash,
		&i.IndexingStatus,
		&i.GraphStatus,
		&i.LifecycleState,
		&i.SupersededBy,
		&i.OriginalDocumentID,
		&i.DocumentID,
		&i.DerivedFromID,
		&i.CapturedAtUnix,
		&i.CameraModel,
		&i.FilenameStem,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveNodesByDocumentID = `-- name: ListLiveNodesByDocumentID :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at
FROM media_nodes
WHERE document_id = ?1 AND lifecycle_state != 'ARCHIVED'
`

// Tier-2 xmpOriginalDocumentID resolver: a child's XMP:OriginalDocumentID
// matching a candidate parent's document_id is a near-certain lineage
// signal (confidence 0.95).
func (q *Queries) ListLiveNodesByDocumentID(ctx context.Context, documentID sql.NullString) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveNodesByFastHash = `-- name: ListLiveNodesByFastHash :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at
FROM media_nodes
WHERE fast_hash = ?1 AND lifecycle_state != 'ARCHIVED'
`

// T1 (spec 9.5): before assuming two same-fast_hash files at DIFFERENT live
// paths are the same content, the pipeline needs every other live node
// sharing that fast_hash so it can escalate to full_hash and compare.
func (q *Queries) ListLiveNodesByFastHash(ctx context.Context, fastHash *string) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesByFastHash, fastHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveNodesByFilenameStem = `-- name: ListLiveNodesByFilenameStem :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at
FROM media_nodes
WHERE filename_stem = ?1 AND lifecycle_state != 'ARCHIVED'
`

// Tier-2 filenameStem resolver: candidate parents sharing a normalized
// filename stem with the child, scored further by capture day / camera /
// directory match in internal/graph.
func (q *Queries) ListLiveNodesByFilenameStem(ctx context.Context, filenameStem sql.NullString) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesByFilenameStem, filenameStem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaNodes = `-- name: ListMediaNodes :many
SELECT id, node_uuid, storage_location_id, file_path, file_name, file_ext,
       size_bytes, mtime_unix, fast_hash, full_hash, phash,
       indexing_status, graph_status, lifecycle_state, superseded_by,
       original_document_id, document_id, derived_from_id,
       captured_at_unix, camera_model, filename_stem,
       first_seen_at, last_seen_at, created_at, updated_at
FROM media_nodes
WHERE lifecycle_state != 'ARCHIVED'
ORDER BY id DESC
LIMIT ?1 OFFSET ?2
`

type ListMediaNodesParams struct {
	Limit  int64
	Offset int64
}

// Backs GET /api/v1/assets. Excludes archived rows by default -- an
// archived node is reachable via its successor's superseded history, not
// the main asset list.
func (q *Queries) ListMediaNodes(ctx context.Context, arg ListMediaNodesParams) ([]MediaNode, error) {
	rows, err := q.db.QueryContext(ctx, listMediaNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaNode{}
	for rows.Next() {
		var i MediaNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.StorageLocationID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.FastHash,
			&i.FullHash,
			&i.Phash,
			&i.IndexingStatus,
			&i.GraphStatus,
			&i.LifecycleState,
			&i.SupersededBy,
			&i.OriginalDocumentID,
			&i.DocumentID,
			&i.DerivedFromID,
			&i.CapturedAtUnix,
			&i.CameraModel,
			&i.FilenameStem,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeMissing = `-- name: MarkNodeMissing :exec
UPDATE media_nodes SET lifecycle_state = 'MISSING', updated_at = unixepoch() WHERE id = ?1
`

func (q *Queries) MarkNodeMissing(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markNodeMissing, id)
	return err
}

const markUnseenNodesMissing = `-- name: MarkUnseenNodesMissing :execrows
UPDATE media_nodes
SET lifecycle_state = 'MISSING', updated_at = unixepoch()
WHERE storage_location_id = ?1
  AND lifecycle_state = 'ACTIVE'
  AND last_seen_at < ?2
  AND file_path NOT IN (/*SLICE:keep_active*/?)
`

type MarkUnseenNodesMissingParams struct {
	StorageLocationID int64
	BeforeUnix        int64
	KeepActive        []string
}

// Phase 1 (#31): at the end of a clean full scan, every ACTIVE node under the
// scanned storage location whose last_seen_at predates the scan's start is
// gone. TouchMediaNode/InsertMediaNode/RebaseMissingNodePath all bump
// last_seen_at on every node the walk actually saw and committed, so anything
// still old here was genuinely unseen this scan. KeepActive is the pass's
// seen-but-uncertain set -- paths the walk saw but did not reliably commit
// (processFile error, submit refused, dropped result, batch Commit failure) --
// and is excluded from the sweep: a file on disk with a stale last_seen_at is
// not proof it's gone. SQLite's per-statement variable limit (32766 on modern
// builds) bounds how large KeepActive can be; beyond that the caller would
// need to chunk the sweep, which it does not. Scoped by storage_location_id so
// a scan of one mount never touches another. unixepoch() is 1s granularity, so
// a node last seen in a scan that happened to end in the SAME wall-clock
// second as this scan's start may survive one extra scan -- it is swept the
// next round, which is delayed-not-wrong.
func (q *Queries) MarkUnseenNodesMissing(ctx context.Context, arg MarkUnseenNodesMissingParams) (int64, error) {
	query := markUnseenNodesMissing
	var queryParams []interface{}
	queryParams = append(queryParams, arg.StorageLocationID)
	queryParams = append(queryParams, arg.BeforeUnix)
	if len(arg.KeepActive) > 0 {
		for _, v := range arg.KeepActive {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keep_active*/?", strings.Repeat(",?", len(arg.KeepActive))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keep_active*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rebaseMissingNodePath = `-- name: RebaseMissingNodePath :exec
UPDATE media_nodes
SET file_path = ?2, file_name = ?3, storage_location_id = ?4,
    lifecycle_state = 'ACTIVE', mtime_unix = ?5,
    last_seen_at = unixepoch(), updated_at = unixepoch()
WHERE id = ?1
`

type RebaseMissingNodePathParams struct {
	ID                int64
	FilePath          string
	FileName          string
	StorageLocationID int64
	MtimeUnix         int64
}

// Pillar 5 move detection, applied: the id and node_uuid never change, so
// every edge referencing this node (as parent or child) survives the move
// untouched -- no CASCADE, no rewrite needed.
func (q *Queries) RebaseMissingNodePath(ctx context.Context, arg RebaseMissingNodePathParams) error {
	_, err := q.db.ExecContext(ctx, rebaseMissingNodePath,
		arg.ID,
		arg.FilePath,
		arg.FileName,
		arg.StorageLocationID,
		arg.MtimeUnix,
	)
	return err
}

const setSupersededBy = `-- name: SetSupersededBy :exec
UPDATE media_nodes SET superseded_by = ?2, updated_at = unixepoch() WHERE id = ?1
`

type SetSupersededByParams struct {
	ID           int64
	SupersededBy sql.NullInt64
}

// Step 3 of a version collision: link the archived row to its successor,
// once the successor's id is known (i.e. after InsertMediaNode).
func (q *Queries) SetSupersededBy(ctx context.Context, arg SetSupersededByParams) error {
	_, err := q.db.ExecContext(ctx, setSupersededBy, arg.ID, arg.SupersededBy)
	return err
}

const touchMediaNode = `-- name: TouchMediaNode :exec
UPDATE media_nodes
SET mtime_unix = ?2, last_seen_at = unixepoch(),
    lifecycle_state = CASE WHEN lifecycle_state = 'MISSING' THEN 'ACTIVE' ELSE lifecycle_state END,
    updated_at = unixepoch()
WHERE id = ?1
`

type TouchMediaNodeParams struct {
	ID        int64
	MtimeUnix int64
}

// Same content at the same path, seen again on a later scan. Records that
// and, if the row was MISSING (a file re-created at its old path), reactivates
// it in place -- a MISSING row found alive again is not a version collision
// and must not stay MISSING.
func (q *Queries) TouchMediaNode(ctx context.Context, arg TouchMediaNodeParams) error {
	_, err := q.db.ExecContext(ctx, touchMediaNode, arg.ID, arg.MtimeUnix)
	return err
}

const updateMediaNodeFullHash = `-- name: UpdateMediaNodeFullHash :exec
UPDATE media_nodes SET full_hash = ?2, indexing_status = 'INDEXED_FULL', updated_at = unixepoch() WHERE id = ?1
`

type UpdateMediaNodeFullHashParams struct {
	ID       int64
	FullHash *string
}

// Escalation path for T1: computed lazily, only when fast_hash collides
// with another live node or the file lives on a TIER3_MASTER_ARCHIVE
// location (docs/schema.md fix #8's full_hash policy).
func (q *Queries) UpdateMediaNodeFullHash(ctx context.Context, arg UpdateMediaNodeFullHashParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaNodeFullHash, arg.ID, arg.FullHash)
	return err
}

const updateMediaNodeGraphStatus = `-- name: UpdateMediaNodeGraphStatus :exec
UPDATE media_nodes SET graph_status = ?2, updated_at = unixepoch() WHERE id = ?1
`

type UpdateMediaNodeGraphStatusParams struct {
	ID          int64
	GraphStatus string
}

func (q *Queries) UpdateMediaNodeGraphStatus(ctx context.Context, arg UpdateMediaNodeGraphStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaNodeGraphStatus, arg.ID, arg.GraphStatus)
	return err
}
