// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_edges_resolve.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const confirmMediaEdge = `-- name: ConfirmMediaEdge :one
UPDATE media_edges
SET review_state = 'CONFIRMED', reviewed_at = unixepoch(), reviewed_by = ?2, updated_at = unixepoch()
WHERE id = ?1
RETURNING target_node_id
`

type ConfirmMediaEdgeParams struct {
	ID         int64
	ReviewedBy sql.NullString
}

// RETURNING target_node_id (rather than plain :exec) doubles as the
// existence check: sql.ErrNoRows means id didn't match any row, which the
// caller (internal/httpapi) turns into a 404 instead of a silent no-op
// 200. The returned target_node_id is what the caller re-derives
// graph_status from -- see routes.go's recomputeGraphStatus.
func (q *Queries) ConfirmMediaEdge(ctx context.Context, arg ConfirmMediaEdgeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, confirmMediaEdge, arg.ID, arg.ReviewedBy)
	var target_node_id int64
	err := row.Scan(&target_node_id)
	return target_node_id, err
}

const getMediaEdgeBySourceTargetRel = `-- name: GetMediaEdgeBySourceTargetRel :one
SELECT id, source_node_id, target_node_id, relationship_type, confidence,
       tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
       created_at, updated_at
FROM media_edges
WHERE source_node_id = ?1 AND target_node_id = ?2 AND relationship_type = ?3
`

type GetMediaEdgeBySourceTargetRelParams struct {
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
}

// Used by internal/graph.Engine.ResolveAndCommit when UpsertMediaEdge
// returns sql.ErrNoRows -- the edge is CONFIRMED/REJECTED and was
// intentionally left untouched, so the caller re-fetches its current state
// here rather than treating the no-row RETURNING as an error.
func (q *Queries) GetMediaEdgeBySourceTargetRel(ctx context.Context, arg GetMediaEdgeBySourceTargetRelParams) (MediaEdge, error) {
	row := q.db.QueryRowContext(ctx, getMediaEdgeBySourceTargetRel, arg.SourceNodeID, arg.TargetNodeID, arg.RelationshipType)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.RelationshipType,
		&i.Confidence,
		&i.Tier,
		&i.Resolver,
		&i.EvidenceJson,
		&i.ReviewState,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mediaEdgeExists = `-- name: MediaEdgeExists :one
SELECT EXISTS(
    SELECT 1 FROM media_edges
    WHERE source_node_id = ?1 AND target_node_id = ?2 AND relationship_type = ?3
) AS edge_exists
`

type MediaEdgeExistsParams struct {
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
}

// Checked before UpsertMediaEdge so the caller can tell a genuinely new
// edge apart from an existing one whose confidence/evidence was merely
// refreshed -- UpsertMediaEdge's RETURNING row looks the same either way.
// Backs scan_jobs.edges_created (fix(pipeline): #90).
func (q *Queries) MediaEdgeExists(ctx context.Context, arg MediaEdgeExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, mediaEdgeExists, arg.SourceNodeID, arg.TargetNodeID, arg.RelationshipType)
	var edge_exists bool
	err := row.Scan(&edge_exists)
	return edge_exists, err
}

const rejectMediaEdge = `-- name: RejectMediaEdge :one
UPDATE media_edges
SET review_state = 'REJECTED', reviewed_at = unixepoch(), reviewed_by = ?2, updated_at = unixepoch()
WHERE id = ?1
RETURNING target_node_id
`

type RejectMediaEdgeParams struct {
	ID         int64
	ReviewedBy sql.NullString
}

// See ConfirmMediaEdge's comment -- same shape, same reasoning.
func (q *Queries) RejectMediaEdge(ctx context.Context, arg RejectMediaEdgeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, rejectMediaEdge, arg.ID, arg.ReviewedBy)
	var target_node_id int64
	err := row.Scan(&target_node_id)
	return target_node_id, err
}

const resolvedEdgeParentMissing = `-- name: ResolvedEdgeParentMissing :one
SELECT parent_missing FROM v_media_edges_resolved WHERE id = ?1
`

// Backs T7's regression guard: v_media_edges_resolved.parent_missing must
// be true for every relationship_type, not just DERIVED_FROM -- the thing
// the spec's deleted trigger (docs/schema.md fix #4) never did.
func (q *Queries) ResolvedEdgeParentMissing(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, resolvedEdgeParentMissing, id)
	var parent_missing bool
	err := row.Scan(&parent_missing)
	return parent_missing, err
}

const upsertMediaEdge = `-- name: UpsertMediaEdge :one
INSERT INTO media_edges (
    source_node_id, target_node_id, relationship_type, confidence, tier,
    resolver, evidence_json, review_state
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
ON CONFLICT (source_node_id, target_node_id, relationship_type) DO UPDATE SET
    confidence    = MAX(excluded.confidence, media_edges.confidence),
    tier          = CASE WHEN excluded.confidence >= media_edges.confidence
                            AND NOT (excluded.confidence = media_edges.confidence
                                     AND media_edges.review_state = 'AUTO_ACCEPTED'
                                     AND excluded.review_state = 'NEEDS_REVIEW')
                          THEN excluded.tier ELSE media_edges.tier END,
    resolver      = CASE WHEN excluded.confidence >= media_edges.confidence
                            AND NOT (excluded.confidence = media_edges.confidence
                                     AND media_edges.review_state = 'AUTO_ACCEPTED'
                                     AND excluded.review_state = 'NEEDS_REVIEW')
                          THEN excluded.resolver ELSE media_edges.resolver END,
    evidence_json = CASE WHEN excluded.confidence >= media_edges.confidence
                            AND NOT (excluded.confidence = media_edges.confidence
                                     AND media_edges.review_state = 'AUTO_ACCEPTED'
                                     AND excluded.review_state = 'NEEDS_REVIEW')
                          THEN excluded.evidence_json ELSE media_edges.evidence_json END,
    review_state  = CASE WHEN excluded.confidence >= media_edges.confidence
                            AND NOT (excluded.confidence = media_edges.confidence
                                     AND media_edges.review_state = 'AUTO_ACCEPTED'
                                     AND excluded.review_state = 'NEEDS_REVIEW')
                          THEN excluded.review_state ELSE media_edges.review_state END,
    updated_at    = unixepoch()
WHERE media_edges.review_state NOT IN ('CONFIRMED', 'REJECTED')
RETURNING id, source_node_id, target_node_id, relationship_type, confidence,
          tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
          created_at, updated_at
`

type UpsertMediaEdgeParams struct {
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
	Confidence       float64
	Tier             int64
	Resolver         string
	EvidenceJson     string
	ReviewState      string
}

// A human decision outranks any resolver, permanently: the UPDATE branch is
// gated by a WHERE that skips rows already CONFIRMED or REJECTED entirely.
// IMPORTANT: when that WHERE evaluates false, SQLite's RETURNING emits NO
// ROW at all -- it does NOT return the pre-existing row unmodified (verified
// against SQLite directly; an earlier version of this comment claimed
// otherwise and was wrong). Because this query is :one, a human-locked edge
// therefore surfaces to the caller as sql.ErrNoRows, which internal/graph's
// Engine.ResolveAndCommit must treat as "edge intentionally left untouched,
// re-fetch it and continue" -- NOT as a failure to roll the whole batch
// back on.
//
// confidence only ever increases (MAX), never regresses if a later resolve
// pass finds a weaker signal for the same edge. tier/resolver/evidence_json/
// review_state are each keyed on WHICH SIDE actually supplied that MAX'd
// confidence (excluded, i.e. this call's candidate, vs. the row as it stood
// before this call) rather than being taken unconditionally from excluded or
// re-derived from a hardcoded threshold -- both of those independently let a
// later, weaker resolver pass silently overwrite a stronger earlier one:
// unconditional excluded.tier/resolver/evidence_json could stamp a losing
// pass's provenance next to a winning MAX'd confidence, and a hardcoded
// ">= 0.90" ignored internal/graph's per-tier auto-accept threshold (0.85
// for Tier 3), downgrading a Tier-3 AUTO_ACCEPTED edge back to NEEDS_REVIEW
// on every subsequent scan pass. review_state is never independently
// recomputed here at all: excluded.review_state (bind ?8) already carries
// the tier-correct value Engine computed for this candidate, so keying it
// the same way as confidence keeps the two permanently consistent. On an
// exact confidence tie, `>=` deliberately favors the incoming candidate
// (excluded) -- that's what refreshes evidence_json/resolver/timestamps on
// an identical same-resolver re-fire, the common case. Do not tighten this
// to `>` outright (Hermes review on PR #128 suggested exactly that for
// review_state alone; rejected below).
//
// One exception carves into that `>=`: because the per-tier auto-accept
// threshold differs by tier (0.85 for Tier 3, 0.90 otherwise), an exact
// confidence tie between a HIGHER tier (already AUTO_ACCEPTED) and a LOWER
// tier candidate at that same confidence (computed NEEDS_REVIEW, since it
// doesn't clear ITS tier's higher threshold) would otherwise let the
// lower-tier candidate win the tie and downgrade review_state -- confidence
// doesn't regress, but review_state does, which is exactly the class of bug
// this query exists to prevent. Each CASE below therefore adds one more
// clause on top of the `>=` tie rule: excluded still wins ties EXCEPT the
// specific one where the stored row is AUTO_ACCEPTED and the incoming
// candidate computed NEEDS_REVIEW at that same confidence. Applying that
// same exception to ALL FOUR fields together (not just review_state, as
// Hermes' suggestion would have done) is deliberate: tier/resolver/
// evidence_json/review_state must always
// describe the SAME pass, so on a blocked tie the stored row's provenance
// stays fully intact too, rather than adopting the incoming candidate's
// tier/resolver while keeping the old review_state -- that combination
// would itself be an inconsistent, self-contradicting row.
func (q *Queries) UpsertMediaEdge(ctx context.Context, arg UpsertMediaEdgeParams) (MediaEdge, error) {
	row := q.db.QueryRowContext(ctx, upsertMediaEdge,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.RelationshipType,
		arg.Confidence,
		arg.Tier,
		arg.Resolver,
		arg.EvidenceJson,
		arg.ReviewState,
	)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.RelationshipType,
		&i.Confidence,
		&i.Tier,
		&i.Resolver,
		&i.EvidenceJson,
		&i.ReviewState,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
