// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_edges_write.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createManualMediaEdge = `-- name: CreateManualMediaEdge :one
INSERT INTO media_edges (
    source_node_id, target_node_id, relationship_type, confidence, tier,
    resolver, evidence_json, review_state, reviewed_by, reviewed_at
) VALUES (
    ?1, ?2, ?3, 1.00, 1, 'manual', '{}', 'CONFIRMED', ?4, unixepoch()
)
ON CONFLICT (source_node_id, target_node_id, relationship_type) DO UPDATE SET
    confidence = 1.00,
    tier = 1,
    resolver = 'manual',
    review_state = 'CONFIRMED',
    reviewed_by = ?4,
    reviewed_at = unixepoch(),
    updated_at = unixepoch()
RETURNING id, source_node_id, target_node_id, relationship_type, confidence,
          tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
          created_at, updated_at
`

type CreateManualMediaEdgeParams struct {
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
	ReviewedBy       sql.NullString
}

func (q *Queries) CreateManualMediaEdge(ctx context.Context, arg CreateManualMediaEdgeParams) (MediaEdge, error) {
	row := q.db.QueryRowContext(ctx, createManualMediaEdge,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.RelationshipType,
		arg.ReviewedBy,
	)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.RelationshipType,
		&i.Confidence,
		&i.Tier,
		&i.Resolver,
		&i.EvidenceJson,
		&i.ReviewState,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMediaEdge = `-- name: CreateMediaEdge :one
INSERT INTO media_edges (
    source_node_id, target_node_id, relationship_type, confidence, tier,
    resolver, evidence_json, review_state
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
RETURNING id, source_node_id, target_node_id, relationship_type, confidence,
          tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
          created_at, updated_at
`

type CreateMediaEdgeParams struct {
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
	Confidence       float64
	Tier             int64
	Resolver         string
	EvidenceJson     string
	ReviewState      string
}

// Minimal edge insert, landed here because PR 6's own version-collision test
// (T5, spec 9.5) needs to prove an existing edge survives archiving its
// source node (docs/schema.md fix #6: RESTRICT, never CASCADE). Full edge
// resolution -- confidence scoring, cycle detection, upsert-without-
// downgrading-review_state -- is internal/graph's job (PR 7), built on top
// of this.
func (q *Queries) CreateMediaEdge(ctx context.Context, arg CreateMediaEdgeParams) (MediaEdge, error) {
	row := q.db.QueryRowContext(ctx, createMediaEdge,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.RelationshipType,
		arg.Confidence,
		arg.Tier,
		arg.Resolver,
		arg.EvidenceJson,
		arg.ReviewState,
	)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.RelationshipType,
		&i.Confidence,
		&i.Tier,
		&i.Resolver,
		&i.EvidenceJson,
		&i.ReviewState,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaEdge = `-- name: GetMediaEdge :one
SELECT id, source_node_id, target_node_id, relationship_type, confidence,
       tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
       created_at, updated_at
FROM media_edges
WHERE id = ?1
`

func (q *Queries) GetMediaEdge(ctx context.Context, id int64) (MediaEdge, error) {
	row := q.db.QueryRowContext(ctx, getMediaEdge, id)
	var i MediaEdge
	err := row.Scan(
		&i.ID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.RelationshipType,
		&i.Confidence,
		&i.Tier,
		&i.Resolver,
		&i.EvidenceJson,
		&i.ReviewState,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEdgesBySource = `-- name: ListEdgesBySource :many
SELECT id, source_node_id, target_node_id, relationship_type, confidence,
       tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
       created_at, updated_at
FROM media_edges
WHERE source_node_id = ?1
`

func (q *Queries) ListEdgesBySource(ctx context.Context, sourceNodeID int64) ([]MediaEdge, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesBySource, sourceNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaEdge{}
	for rows.Next() {
		var i MediaEdge
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.RelationshipType,
			&i.Confidence,
			&i.Tier,
			&i.Resolver,
			&i.EvidenceJson,
			&i.ReviewState,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesByTarget = `-- name: ListEdgesByTarget :many
SELECT id, source_node_id, target_node_id, relationship_type, confidence,
       tier, resolver, evidence_json, review_state, reviewed_at, reviewed_by,
       created_at, updated_at
FROM media_edges
WHERE target_node_id = ?1
`

func (q *Queries) ListEdgesByTarget(ctx context.Context, targetNodeID int64) ([]MediaEdge, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesByTarget, targetNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaEdge{}
	for rows.Next() {
		var i MediaEdge
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.RelationshipType,
			&i.Confidence,
			&i.Tier,
			&i.Resolver,
			&i.EvidenceJson,
			&i.ReviewState,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
