// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_edges.sql

package sqlcgen

import (
	"context"
)

const listAuditQueue = `-- name: ListAuditQueue :many
SELECT id, source_node_id, target_node_id, relationship_type, confidence,
       resolver, evidence_json, parent_alive, parent_missing
FROM v_media_edges_resolved
WHERE review_state = 'NEEDS_REVIEW'
ORDER BY confidence DESC, id ASC
LIMIT ?1 OFFSET ?
`

type ListAuditQueueParams struct {
	Limit  int64
	Offset int64
}

type ListAuditQueueRow struct {
	ID               int64
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
	Confidence       float64
	Resolver         string
	EvidenceJson     string
	ParentAlive      bool
	ParentMissing    bool
}

// The audit queue (spec §7) is this query over review_state, not a second
// table. v_media_edges_resolved's parent_missing works for every
// relationship_type -- the spec's deleted trigger never did. See
// docs/schema.md fix #4.
func (q *Queries) ListAuditQueue(ctx context.Context, arg ListAuditQueueParams) ([]ListAuditQueueRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditQueue, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditQueueRow{}
	for rows.Next() {
		var i ListAuditQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.RelationshipType,
			&i.Confidence,
			&i.Resolver,
			&i.EvidenceJson,
			&i.ParentAlive,
			&i.ParentMissing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wouldCreateCycle = `-- name: WouldCreateCycle :one
WITH RECURSIVE descendants(id) AS (
    SELECT ?2 AS id
    UNION
    SELECT e.target_node_id
    FROM media_edges e
    JOIN descendants d ON e.source_node_id = d.id
)
SELECT EXISTS(SELECT 1 FROM descendants WHERE id = ?1) AS would_cycle
`

type WouldCreateCycleParams struct {
	ParentNodeID int64
	ChildNodeID  int64
}

// Walk the proposed child's descendants; if the proposed PARENT is already a
// descendant of the proposed CHILD, the new edge would close a cycle. Used
// by internal/graph (PR 7) inside the same write transaction as the edge
// insert -- DB.InTx's single writer connection is what makes this
// check-then-insert sound without extra application-level locking.
//
// The bare-parameter anchor `SELECT sqlc.arg(...)` needed an explicit alias
// to satisfy sqlc's SQLite parser -- see docs/schema.md's sqlc risk note.
func (q *Queries) WouldCreateCycle(ctx context.Context, arg WouldCreateCycleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, wouldCreateCycle, arg.ParentNodeID, arg.ChildNodeID)
	var would_cycle bool
	err := row.Scan(&would_cycle)
	return would_cycle, err
}
