// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearMFAPendingSecret = `-- name: ClearMFAPendingSecret :exec
UPDATE users SET mfa_pending_secret = NULL WHERE id = ?1
`

func (q *Queries) ClearMFAPendingSecret(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearMFAPendingSecret, id)
	return err
}

const deleteMFACredentials = `-- name: DeleteMFACredentials :exec
DELETE FROM mfa_credentials WHERE user_id = ?1
`

func (q *Queries) DeleteMFACredentials(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMFACredentials, userID)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM mfa_recovery_codes WHERE user_id = ?1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, userID)
	return err
}

const findUnusedRecoveryCode = `-- name: FindUnusedRecoveryCode :one
SELECT id, code_hash
FROM mfa_recovery_codes
WHERE user_id = ?1 AND code_hash = ?2 AND used_at IS NULL
LIMIT 1
`

type FindUnusedRecoveryCodeParams struct {
	UserID   int64
	CodeHash string
}

type FindUnusedRecoveryCodeRow struct {
	ID       int64
	CodeHash string
}

func (q *Queries) FindUnusedRecoveryCode(ctx context.Context, arg FindUnusedRecoveryCodeParams) (FindUnusedRecoveryCodeRow, error) {
	row := q.db.QueryRowContext(ctx, findUnusedRecoveryCode, arg.UserID, arg.CodeHash)
	var i FindUnusedRecoveryCodeRow
	err := row.Scan(&i.ID, &i.CodeHash)
	return i, err
}

const getMFACredentials = `-- name: GetMFACredentials :one

SELECT user_id, secret_encrypted, algo, digits, period, last_used_step
FROM mfa_credentials
WHERE user_id = ?1
`

// MFA queries. All positional params use bare ?1/?2 per AGENTS.md's
// "SQL Syntax Traps" note.
func (q *Queries) GetMFACredentials(ctx context.Context, userID int64) (MfaCredential, error) {
	row := q.db.QueryRowContext(ctx, getMFACredentials, userID)
	var i MfaCredential
	err := row.Scan(
		&i.UserID,
		&i.SecretEncrypted,
		&i.Algo,
		&i.Digits,
		&i.Period,
		&i.LastUsedStep,
	)
	return i, err
}

const getMFAPendingSecret = `-- name: GetMFAPendingSecret :one
SELECT id, mfa_pending_secret FROM users WHERE id = ?1
`

type GetMFAPendingSecretRow struct {
	ID               int64
	MfaPendingSecret sql.NullString
}

func (q *Queries) GetMFAPendingSecret(ctx context.Context, id int64) (GetMFAPendingSecretRow, error) {
	row := q.db.QueryRowContext(ctx, getMFAPendingSecret, id)
	var i GetMFAPendingSecretRow
	err := row.Scan(&i.ID, &i.MfaPendingSecret)
	return i, err
}

const getSessionWithMFA = `-- name: GetSessionWithMFA :one
SELECT id, cookie_id, user_id, created_at, last_seen_at, expires_at, idle_expires_at, ip, user_agent, revoked_at, mfa_verified_at
FROM sessions
WHERE cookie_id = ?1
`

func (q *Queries) GetSessionWithMFA(ctx context.Context, cookieID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithMFA, cookieID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CookieID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
		&i.MfaVerifiedAt,
	)
	return i, err
}

const insertRecoveryCodes = `-- name: InsertRecoveryCodes :exec
INSERT INTO mfa_recovery_codes (user_id, code_hash)
VALUES (?1, ?2)
`

type InsertRecoveryCodesParams struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) InsertRecoveryCodes(ctx context.Context, arg InsertRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, insertRecoveryCodes, arg.UserID, arg.CodeHash)
	return err
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE mfa_recovery_codes SET used_at = ?2 WHERE id = ?1
`

type MarkRecoveryCodeUsedParams struct {
	ID     int64
	UsedAt sql.NullInt64
}

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, markRecoveryCodeUsed, arg.ID, arg.UsedAt)
	return err
}

const setMFAPendingSecret = `-- name: SetMFAPendingSecret :exec
UPDATE users SET mfa_pending_secret = ?2 WHERE id = ?1
`

type SetMFAPendingSecretParams struct {
	ID               int64
	MfaPendingSecret sql.NullString
}

func (q *Queries) SetMFAPendingSecret(ctx context.Context, arg SetMFAPendingSecretParams) error {
	_, err := q.db.ExecContext(ctx, setMFAPendingSecret, arg.ID, arg.MfaPendingSecret)
	return err
}

const setSessionMFAVerified = `-- name: SetSessionMFAVerified :exec
UPDATE sessions SET mfa_verified_at = ?2 WHERE id = ?1
`

type SetSessionMFAVerifiedParams struct {
	ID            int64
	MfaVerifiedAt sql.NullInt64
}

func (q *Queries) SetSessionMFAVerified(ctx context.Context, arg SetSessionMFAVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, setSessionMFAVerified, arg.ID, arg.MfaVerifiedAt)
	return err
}

const updateLastUsedStep = `-- name: UpdateLastUsedStep :exec
UPDATE mfa_credentials SET last_used_step = ?2 WHERE user_id = ?1
`

type UpdateLastUsedStepParams struct {
	UserID       int64
	LastUsedStep int64
}

func (q *Queries) UpdateLastUsedStep(ctx context.Context, arg UpdateLastUsedStepParams) error {
	_, err := q.db.ExecContext(ctx, updateLastUsedStep, arg.UserID, arg.LastUsedStep)
	return err
}

const upsertMFACredentials = `-- name: UpsertMFACredentials :exec
INSERT INTO mfa_credentials (user_id, secret_encrypted, algo, digits, period, last_used_step)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (user_id) DO UPDATE SET
    secret_encrypted = excluded.secret_encrypted,
    algo = excluded.algo,
    digits = excluded.digits,
    period = excluded.period,
    last_used_step = excluded.last_used_step
`

type UpsertMFACredentialsParams struct {
	UserID          int64
	SecretEncrypted string
	Algo            string
	Digits          int64
	Period          int64
	LastUsedStep    int64
}

func (q *Queries) UpsertMFACredentials(ctx context.Context, arg UpsertMFACredentialsParams) error {
	_, err := q.db.ExecContext(ctx, upsertMFACredentials,
		arg.UserID,
		arg.SecretEncrypted,
		arg.Algo,
		arg.Digits,
		arg.Period,
		arg.LastUsedStep,
	)
	return err
}
