// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type EventQueue struct {
	ID          int64
	EventUuid   string
	AgentID     string
	EventType   string
	PayloadJson string
	Status      string
	ErrorLog    sql.NullString
	CreatedAt   int64
	ProcessedAt sql.NullInt64
	RetryCount  int64
}

type MediaEdge struct {
	ID               int64
	SourceNodeID     int64
	TargetNodeID     int64
	RelationshipType string
	Confidence       float64
	Tier             int64
	Resolver         string
	EvidenceJson     string
	ReviewState      string
	ReviewedAt       sql.NullInt64
	ReviewedBy       sql.NullString
	CreatedAt        int64
	UpdatedAt        int64
}

type MediaNode struct {
	ID                 int64
	NodeUuid           string
	StorageLocationID  int64
	FilePath           string
	FileName           string
	FileExt            string
	SizeBytes          int64
	MtimeUnix          int64
	FastHash           *string
	FullHash           *string
	Phash              sql.NullInt64
	IndexingStatus     string
	GraphStatus        string
	LifecycleState     string
	SupersededBy       sql.NullInt64
	OriginalDocumentID sql.NullString
	DocumentID         sql.NullString
	DerivedFromID      sql.NullString
	CapturedAtUnix     sql.NullInt64
	CameraModel        sql.NullString
	FilenameStem       sql.NullString
	FirstSeenAt        int64
	LastSeenAt         int64
	CreatedAt          int64
	UpdatedAt          int64
	CameraSerial       sql.NullString
	LensModel          sql.NullString
	ThumbState         string
	ThumbAttempts      int64
}

type NodeMetadatum struct {
	NodeID int64
	Source string
	Key    string
	Value  string
}

type RemoteSyncState struct {
	NodeID        int64
	Remote        string
	SyncStatus    string
	RemoteAssetID sql.NullString
	LastError     sql.NullString
	LastAttemptAt sql.NullInt64
	CreatedAt     int64
	UpdatedAt     int64
	RetryCount    int64
}

type ScanJob struct {
	ID                int64
	StorageLocationID sql.NullInt64
	Kind              string
	State             string
	FilesSeen         int64
	FilesHashed       int64
	FilesFailed       int64
	EdgesCreated      int64
	StartedAt         int64
	FinishedAt        sql.NullInt64
	LastError         sql.NullString
	UpdatedAt         int64
}

type StorageLocation struct {
	ID        int64
	Name      string
	RootPath  string
	Tier      string
	ReadOnly  int64
	Prunable  int64
	IsActive  int64
	CreatedAt int64
	UpdatedAt int64
}

type VMediaEdgesResolved struct {
	ID                   int64
	SourceNodeID         int64
	TargetNodeID         int64
	RelationshipType     string
	Confidence           float64
	Tier                 int64
	Resolver             string
	EvidenceJson         string
	ReviewState          string
	ReviewedAt           sql.NullInt64
	ReviewedBy           sql.NullString
	CreatedAt            int64
	UpdatedAt            int64
	ParentLifecycleState string
	ChildLifecycleState  string
	ParentAlive          bool
	ParentMissing        bool
}
