// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_metadata.sql

package sqlcgen

import (
	"context"
)

const insertNodeMetadata = `-- name: InsertNodeMetadata :exec
INSERT INTO node_metadata (node_id, source, key, value)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (node_id, source, key) DO UPDATE SET value = excluded.value
`

type InsertNodeMetadataParams struct {
	NodeID int64
	Source string
	Key    string
	Value  string
}

// Phase 1 (#33): EXIF/ffprobe overflow. Upsert on the table's natural key so
// a re-scan that re-derives metadata replaces rather than duplicates rows.
func (q *Queries) InsertNodeMetadata(ctx context.Context, arg InsertNodeMetadataParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeMetadata,
		arg.NodeID,
		arg.Source,
		arg.Key,
		arg.Value,
	)
	return err
}

const listNodeMetadata = `-- name: ListNodeMetadata :many
SELECT node_id, source, key, value
FROM node_metadata
WHERE node_id = ?1
ORDER BY source, key
`

// Backs tests and any future metadata inspector UI.
func (q *Queries) ListNodeMetadata(ctx context.Context, nodeID int64) ([]NodeMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listNodeMetadata, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeMetadatum{}
	for rows.Next() {
		var i NodeMetadatum
		if err := rows.Scan(
			&i.NodeID,
			&i.Source,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
