// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_creators.sql

package sqlcgen

import (
	"context"
)

const getNodeCreator = `-- name: GetNodeCreator :one
SELECT agent_id FROM node_creators WHERE node_uuid = ?1
`

func (q *Queries) GetNodeCreator(ctx context.Context, nodeUuid string) (string, error) {
	row := q.db.QueryRowContext(ctx, getNodeCreator, nodeUuid)
	var agent_id string
	err := row.Scan(&agent_id)
	return agent_id, err
}

const setNodeCreator = `-- name: SetNodeCreator :exec
INSERT INTO node_creators (node_uuid, agent_id)
VALUES (?1, ?2)
ON CONFLICT (node_uuid) DO NOTHING
`

type SetNodeCreatorParams struct {
	NodeUuid string
	AgentID  string
}

// Records the paired device that created a node through the agent API.
// First writer wins: a node's creator never changes.
func (q *Queries) SetNodeCreator(ctx context.Context, arg SetNodeCreatorParams) error {
	_, err := q.db.ExecContext(ctx, setNodeCreator, arg.NodeUuid, arg.AgentID)
	return err
}
