// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

// Hand-maintained rather than sqlc-generated: sqlc v1.20-v1.31.1 all
// fail to parse the existing companion_pairing.sql subqueries in this
// environment (the parser emits truncated const blocks across many
// unrelated query strings); running `sqlc generate` corrupts files in
// internal/db/sqlcgen/. See User / Session / LoginAudit /
// PasswordResetToken types' doc comments in models.go for the full
// rationale, and AGENTS.md's "sqlc generate Risk Note" for the
// operational context.
//
// The file's header is preserved as the project's sqlcgen convention
// so a future regeneration can replace the hand-written additions
// once sqlc's parser is fixed or this environment is repaired.
package sqlcgen

import (
	"context"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    user_id, token_hash, created_at, expires_at, created_by
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
RETURNING id, user_id, token_hash, created_at, expires_at, used_at, created_by
`

type CreatePasswordResetTokenParams struct {
	UserID    int64
	TokenHash string
	CreatedAt int64
	ExpiresAt int64
	CreatedBy string
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = ?3
WHERE id = ?1
  AND used_at IS NULL
  AND expires_at > ?2
RETURNING id, user_id, token_hash, created_at, expires_at, used_at, created_by
`

type ConsumePasswordResetTokenParams struct {
	ID     int64
	Now    int64
	UsedAt int64
}

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, consumePasswordResetToken, arg.ID, arg.Now, arg.UsedAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listActivePasswordResetTokens = `-- name: ListActivePasswordResetTokens :many
SELECT id, user_id, token_hash, created_at, expires_at, used_at, created_by
FROM password_reset_tokens
WHERE user_id = ?1
  AND used_at IS NULL
  AND expires_at > ?2
ORDER BY created_at DESC
`

type ListActivePasswordResetTokensParams struct {
	UserID int64
	Now    int64
}

func (q *Queries) ListActivePasswordResetTokens(ctx context.Context, arg ListActivePasswordResetTokensParams) ([]PasswordResetToken, error) {
	rows, err := q.db.QueryContext(ctx, listActivePasswordResetTokens, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivePasswordResetTokens = `-- name: ListAllActivePasswordResetTokens :many
SELECT id, user_id, token_hash, created_at, expires_at, used_at, created_by
FROM password_reset_tokens
WHERE used_at IS NULL
  AND expires_at > ?1
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListAllActivePasswordResetTokensParams struct {
	Now    int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllActivePasswordResetTokens(ctx context.Context, arg ListAllActivePasswordResetTokensParams) ([]PasswordResetToken, error) {
	rows, err := q.db.QueryContext(ctx, listAllActivePasswordResetTokens, arg.Now, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePasswordResetToken = `-- name: RevokePasswordResetToken :exec
UPDATE password_reset_tokens
SET used_at = ?2
WHERE id = ?1
  AND used_at IS NULL
`

type RevokePasswordResetTokenParams struct {
	ID     int64
	UsedAt int64
}

func (q *Queries) RevokePasswordResetToken(ctx context.Context, arg RevokePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokePasswordResetToken, arg.ID, arg.UsedAt)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, created_at, expires_at, used_at, created_by
FROM password_reset_tokens
WHERE token_hash = ?1
  AND used_at IS NULL
  AND expires_at > ?2
LIMIT 1
`

type GetPasswordResetTokenByHashParams struct {
	TokenHash string
	Now       int64
}

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, arg GetPasswordResetTokenByHashParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByHash, arg.TokenHash, arg.Now)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
	)
	return i, err
}
