// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = ?3
WHERE id = ?1
  AND used_at IS NULL
  AND expires_at > ?2
RETURNING id, user_id, token_hash, created_at, expires_at, used_at, created_by
`

type ConsumePasswordResetTokenParams struct {
	ID        int64
	ExpiresAt int64
	UsedAt    sql.NullInt64
}

// Atomic single-use consume. The WHERE used_at IS NULL guard is the
// whole point: a second attempt with the same token id matches zero
// rows, and the caller treats that as "token already consumed". The
// expires_at < ?3 guard means an expired token fails the same way
// (no row, no error), so a stolen-expired-token doesn't reveal that
// it was once valid.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, consumePasswordResetToken, arg.ID, arg.ExpiresAt, arg.UsedAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    user_id, token_hash, created_at, expires_at, created_by
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
RETURNING id, user_id, token_hash, created_at, expires_at, used_at, created_by
`

type CreatePasswordResetTokenParams struct {
	UserID    int64
	TokenHash string
	CreatedAt int64
	ExpiresAt int64
	CreatedBy string
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, created_at, expires_at, used_at, created_by
FROM password_reset_tokens
WHERE token_hash = ?1
  AND used_at IS NULL
  AND expires_at > ?2
LIMIT 1
`

type GetPasswordResetTokenByHashParams struct {
	TokenHash string
	ExpiresAt int64
}

// Confirm-time lookup: scan the active-token index for a specific
// token_hash. The active-partial unique index keeps the candidate
// set small. The handler iterates and finds the row whose hash
// matches -- the index narrows the scan to the small set of
// in-flight tokens, not the entire history.
func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, arg GetPasswordResetTokenByHashParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByHash, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listActivePasswordResetTokens = `-- name: ListActivePasswordResetTokens :many
SELECT id, user_id, token_hash, created_at, expires_at, used_at, created_by
FROM password_reset_tokens
WHERE user_id = ?1
  AND used_at IS NULL
  AND expires_at > ?2
ORDER BY created_at DESC
`

type ListActivePasswordResetTokensParams struct {
	UserID    int64
	ExpiresAt int64
}

// "Pending" panel: list of un-consumed, un-expired tokens for a given
// user. The /admin/users/{id}/resets endpoint will use this in #408.
func (q *Queries) ListActivePasswordResetTokens(ctx context.Context, arg ListActivePasswordResetTokensParams) ([]PasswordResetToken, error) {
	rows, err := q.db.QueryContext(ctx, listActivePasswordResetTokens, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivePasswordResetTokens = `-- name: ListAllActivePasswordResetTokens :many
SELECT id, user_id, token_hash, created_at, expires_at, used_at, created_by
FROM password_reset_tokens
WHERE used_at IS NULL
  AND expires_at > ?1
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListAllActivePasswordResetTokensParams struct {
	ExpiresAt int64
	Limit     int64
	Offset    int64
}

// Global pending list -- used by the admin-UI pending-resets panel
// (PR #408). The query is intentionally cheap: the
// password_reset_tokens_user_idx covers user_id + created_at, and the
// partial active unique covers used_at IS NULL. With a homelab user
// count this is < 100 rows; production-scale is a follow-up.
func (q *Queries) ListAllActivePasswordResetTokens(ctx context.Context, arg ListAllActivePasswordResetTokensParams) ([]PasswordResetToken, error) {
	rows, err := q.db.QueryContext(ctx, listAllActivePasswordResetTokens, arg.ExpiresAt, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePasswordResetToken = `-- name: RevokePasswordResetToken :exec
UPDATE password_reset_tokens
SET used_at = ?2
WHERE id = ?1
  AND used_at IS NULL
`

type RevokePasswordResetTokenParams struct {
	ID     int64
	UsedAt sql.NullInt64
}

// Admin "delete" / revoke. Idempotent: revoking an already-used or
// already-expired token matches the row but is a no-op.
func (q *Queries) RevokePasswordResetToken(ctx context.Context, arg RevokePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokePasswordResetToken, arg.ID, arg.UsedAt)
	return err
}
