// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Step 1 of a version collision (docs/schema.md fix #3): archive the OLD
	// row FIRST, before inserting the new one. The partial unique index
	// (WHERE lifecycle_state != 'ARCHIVED') means a live row and a new live
	// row can never share file_path even for an instant within the
	// transaction -- archiving first, not after, is what keeps that true.
	ArchiveMediaNode(ctx context.Context, id int64) error
	// Phase 1 (#32): a WATCH job torn down by a clean shutdown ends CANCELLED,
	// not FAILED -- only a watcher that died on its own is a failure.
	CancelScanJob(ctx context.Context, id int64) error
	CompleteScanJob(ctx context.Context, id int64) error
	// RETURNING target_node_id (rather than plain :exec) doubles as the
	// existence check: sql.ErrNoRows means id didn't match any row, which the
	// caller (internal/httpapi) turns into a 404 instead of a silent no-op
	// 200. The returned target_node_id is what the caller re-derives
	// graph_status from -- see routes.go's recomputeGraphStatus.
	ConfirmMediaEdge(ctx context.Context, arg ConfirmMediaEdgeParams) (int64, error)
	CountMediaNodesFiltered(ctx context.Context, arg CountMediaNodesFilteredParams) (int64, error)
	CountPendingAgentEvents(ctx context.Context) (int64, error)
	// Observability for #182's automatic-retry bound: how many PUSH_FAILED rows
	// for this remote have a retry_count at or past the bound, so
	// ResetRemoteSyncStateFailed will never re-claim them again on its own.
	// Backs Worker.drain's periodic "permanently abandoned" warning -- distinct
	// from ResetRemoteSyncStateFailed's `retry_count < ?3` claim filter (this is
	// its complement, `>=`), so a misconfigured remote's silent backlog is
	// visible in logs instead of only discoverable via a direct SQLite query.
	CountRemoteSyncStateExhausted(ctx context.Context, arg CountRemoteSyncStateExhaustedParams) (int64, error)
	// #163: called inside the same transaction as CreateScanJob (see
	// pipeline.RunScan) so the check-then-insert is one atomic unit, not just
	// an accident of the writer pool being single-connection. Scoped to
	// kind = 'FULL_SCAN' only -- WATCH jobs are already singleton-per-location
	// via WatcherSupervisor.Start's sync.Once and are long-lived by design, so
	// they must not block a FULL_SCAN (or vice versa).
	CountRunningFullScansForLocation(ctx context.Context, storageLocationID sql.NullInt64) (int64, error)
	CountRunningScanJobs(ctx context.Context) (int64, error)
	CountScanJobsFiltered(ctx context.Context, arg CountScanJobsFilteredParams) (int64, error)
	CreateManualMediaEdge(ctx context.Context, arg CreateManualMediaEdgeParams) (MediaEdge, error)
	// Minimal edge insert, landed here because PR 6's own version-collision test
	// (T5, spec 9.5) needs to prove an existing edge survives archiving its
	// source node (docs/schema.md fix #6: RESTRICT, never CASCADE). Full edge
	// resolution -- confidence scoring, cycle detection, upsert-without-
	// downgrading-review_state -- is internal/graph's job (PR 7), built on top
	// of this.
	CreateMediaEdge(ctx context.Context, arg CreateMediaEdgeParams) (MediaEdge, error)
	CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error)
	CreateStorageLocation(ctx context.Context, arg CreateStorageLocationParams) (StorageLocation, error)
	// Backs M6: after seeding every location config.yaml currently lists,
	// deactivate any PREVIOUSLY active location whose root_path is no longer
	// among them -- an operator removing a location from config, rather than
	// it merely failing to resolve, is a deliberate decision that should also
	// self-heal storage-health/UI state without a manual DB edit. MUST NOT be
	// called with an empty currentRootPaths (cmd/branchdam guards this):
	// json_each(?1) returns ZERO rows for both NULL and '[]' (verified against
	// SQLite directly), which makes `root_path NOT IN (SELECT ... FROM
	// json_each(?1))` true for EVERY row -- the opposite failure direction
	// from MarkUnseenNodesMissing's empty-array gotcha (that one silently
	// matches nothing; this one would silently deactivate every location in
	// the database on a misconfigured or empty config.yaml).
	DeactivateStorageLocationsNotIn(ctx context.Context, jsonEach interface{}) (int64, error)
	// Backs POST /api/v1/agent/events: persists and returns 202 in increment 1.
	// Actually draining/processing these rows ships with the deferred
	// workstation-agent increment -- this table and endpoint exist now so that
	// increment is additive, not a schema migration.
	EnqueueAgentEvent(ctx context.Context, arg EnqueueAgentEventParams) (EnqueueAgentEventRow, error)
	FailScanJob(ctx context.Context, arg FailScanJobParams) error
	GetAgentEventByUUID(ctx context.Context, eventUuid string) (GetAgentEventByUUIDRow, error)
	GetLatestProcessedAgentEventByAgent(ctx context.Context, agentID string) (GetLatestProcessedAgentEventByAgentRow, error)
	// The live-path lookup a scan does for every file: is there already a
	// non-archived node at this exact path? Backed by ux_media_nodes_live_path
	// (docs/schema.md fix #3).
	GetLiveNodeByPath(ctx context.Context, filePath string) (MediaNode, error)
	GetMediaEdge(ctx context.Context, id int64) (MediaEdge, error)
	// Used by internal/graph.Engine.ResolveAndCommit when UpsertMediaEdge
	// returns sql.ErrNoRows -- the edge is CONFIRMED/REJECTED and was
	// intentionally left untouched, so the caller re-fetches its current state
	// here rather than treating the no-row RETURNING as an error.
	GetMediaEdgeBySourceTargetRel(ctx context.Context, arg GetMediaEdgeBySourceTargetRelParams) (MediaEdge, error)
	// Includes archived rows, unlike GetLiveNodeByPath -- used to verify a
	// superseded node's post-archive state (superseded_by, lifecycle_state).
	GetMediaNodeByID(ctx context.Context, id int64) (MediaNode, error)
	GetMediaNodeByUUID(ctx context.Context, nodeUuid string) (MediaNode, error)
	// Pillar 5 move detection: a file vanished (lifecycle_state='MISSING') and
	// a new file elsewhere hashes the same -- likely the same file, moved.
	GetMissingNodeByFastHash(ctx context.Context, fastHash *string) (MediaNode, error)
	// The idempotency look-before-write read for Enqueue: does (node_id, remote)
	// already exist, and in what state?
	GetRemoteSyncState(ctx context.Context, arg GetRemoteSyncStateParams) (RemoteSyncState, error)
	GetScanJob(ctx context.Context, id int64) (ScanJob, error)
	GetStorageLocationByID(ctx context.Context, id int64) (StorageLocation, error)
	// Used by storage.Guard (PR 2) to resolve a canonicalized path to its tier --
	// the single source of truth for tier is this table, never a hardcoded
	// prefix. See docs/schema.md fix #1.
	GetStorageLocationByPath(ctx context.Context, rootPath string) (StorageLocation, error)
	IncrementAgentEventRetry(ctx context.Context, arg IncrementAgentEventRetryParams) error
	InsertMediaNode(ctx context.Context, arg InsertMediaNodeParams) (MediaNode, error)
	// Phase 1 (#33): EXIF/ffprobe overflow. Upsert on the table's natural key so
	// a re-scan that re-derives metadata replaces rather than duplicates rows.
	InsertNodeMetadata(ctx context.Context, arg InsertNodeMetadataParams) error
	// Resets a node's thumbnail generation state to PENDING with attempts
	// zeroed, so internal/thumbs.Worker regenerates it on its next pass.
	// Called from internal/pipeline's reconcilePromotedColumns call site when
	// fast_hash changes on the Touched/rebase branches: the bytes on disk
	// changed, so whatever thumbnail (if any) is cached no longer represents
	// them.
	InvalidateThumbnail(ctx context.Context, id int64) error
	// Recursively list ancestor node IDs.
	// Anchor SELECT explicitly names/aliases all columns to satisfy sqlc's SQLite parser.
	ListAncestors(ctx context.Context, id int64) ([]int64, error)
	// The audit queue (spec §7) is this query over review_state, not a second
	// table. v_media_edges_resolved's parent_missing works for every
	// relationship_type -- the spec's deleted trigger never did. See
	// docs/schema.md fix #4.
	ListAuditQueue(ctx context.Context, arg ListAuditQueueParams) ([]ListAuditQueueRow, error)
	ListAuditQueueDetailed(ctx context.Context, arg ListAuditQueueDetailedParams) ([]ListAuditQueueDetailedRow, error)
	ListCameraModelFacets(ctx context.Context) ([]string, error)
	// Recursively list descendant node IDs.
	// Anchor SELECT explicitly names/aliases all columns to satisfy sqlc's SQLite parser.
	ListDescendants(ctx context.Context, id int64) ([]int64, error)
	ListEdgesBySource(ctx context.Context, sourceNodeID int64) ([]MediaEdge, error)
	ListEdgesByTarget(ctx context.Context, targetNodeID int64) ([]MediaEdge, error)
	ListEdgesForNodes(ctx context.Context, jsonEach string) ([]ListEdgesForNodesRow, error)
	// Tier-2 xmpOriginalDocumentID resolver: a child's XMP:OriginalDocumentID
	// matching a candidate parent's document_id is a near-certain lineage
	// signal (confidence 0.95).
	ListLiveNodesByDocumentID(ctx context.Context, documentID sql.NullString) ([]MediaNode, error)
	// T1 (spec 9.5): before assuming two same-fast_hash files at DIFFERENT live
	// paths are the same content, the pipeline needs every other live node
	// sharing that fast_hash so it can escalate to full_hash and compare.
	ListLiveNodesByFastHash(ctx context.Context, fastHash *string) ([]MediaNode, error)
	// Look up live media nodes sharing exact file_name for fallback path matching.
	ListLiveNodesByFileName(ctx context.Context, fileName string) ([]MediaNode, error)
	// Tier-2 filenameStem resolver: candidate parents sharing a normalized
	// filename stem with the child, scored further by capture day / camera /
	// directory match in internal/graph. Capped at ?2 rows -- defense in depth
	// on top of (not instead of) versionSuffixRe's own -\d{1,2} bound
	// (internal/pipeline/commit.go), which narrows but does not close the
	// over-collapse bug class: an unpadded 1-2 digit hyphen-numbering scheme
	// can still produce a large same-stem batch. FilenameStemResolver logs
	// when this cap is actually hit.
	ListLiveNodesByFilenameStem(ctx context.Context, arg ListLiveNodesByFilenameStemParams) ([]MediaNode, error)
	// #55: the sync worker's enqueue source -- live nodes under a path prefix
	// (the Immich export mount) that have NO remote_sync_state row for the given
	// remote yet. Once pushed, a row exists and the node drops out of this set.
	ListLiveNodesForSync(ctx context.Context, arg ListLiveNodesForSyncParams) ([]ListLiveNodesForSyncRow, error)
	// Backs GET /api/v1/assets. Excludes archived rows by default -- an
	// archived node is reachable via its successor's superseded history, not
	// the main asset list.
	ListMediaNodes(ctx context.Context, arg ListMediaNodesParams) ([]MediaNode, error)
	ListMediaNodesFiltered(ctx context.Context, arg ListMediaNodesFilteredParams) ([]MediaNode, error)
	ListNodeCountsByLocation(ctx context.Context) ([]ListNodeCountsByLocationRow, error)
	// Backs tests and any future metadata inspector UI.
	ListNodeMetadata(ctx context.Context, nodeID int64) ([]NodeMetadatum, error)
	ListNodesByIDs(ctx context.Context, jsonEach string) ([]MediaNode, error)
	ListPendingAgentEvents(ctx context.Context, limit int64) ([]ListPendingAgentEventsRow, error)
	// internal/thumbs.Worker's claim query: up to ?2 PENDING nodes oldest-first
	// (by id, this codebase's usual FIFO tiebreak), backed by 00007's partial
	// index idx_media_nodes_thumb_pending (WHERE thumb_state = 'PENDING'), so
	// the index stays cheap as the backlog drains rather than scanning every
	// row regardless of state. thumb_attempts < ?1 excludes a node that has
	// already exhausted the worker's retry bound -- a permanently-broken
	// source (corrupt file, unsupported format that errors rather than
	// returning thumbs.ErrUnsupported) stops being retried every pass forever,
	// mirroring remote_sync_state's retry_count bound
	// (ResetRemoteSyncStateFailed). lifecycle_state excludes MISSING/ARCHIVED:
	// there is no live file left to read a thumbnail from.
	ListPendingThumbnails(ctx context.Context, arg ListPendingThumbnailsParams) ([]ListPendingThumbnailsRow, error)
	// #61's TTL cache pruning eligibility: a Tier-1 node past its TTL
	// (mtime_unix < cutoff_unix) is only a candidate if a LIVE ancestor on a
	// TIER3_MASTER_ARCHIVE location has a verified (non-NULL, 64-hex) full_hash.
	// "live" matches v_media_edges_resolved's own parent_alive definition --
	// ACTIVE or HIDDEN, deliberately not the looser "!= ARCHIVED" -- so a
	// vanished (MISSING) or archived Tier-3 master can never authorize a purge.
	// Ancestor, not "same full_hash": walks media_edges target->source
	// (REJECTED edges excluded), mirroring ListAncestors' direction convention.
	// Tier-1-only and prunable-only are already schema-enforced
	// (00001_init.sql's CHECK (tier = 'TIER1_LOCAL_SCRATCH' OR prunable = 0)) --
	// not re-checked here; the caller only invokes this against a location it
	// already knows is prunable.
	//
	// Every column in each anchor SELECT is explicitly named/aliased -- sqlc's
	// SQLite parser fails with `*ast.ResTarget has nil name` otherwise (see
	// docs/schema.md's sqlc risk note). "64-hex" is enforced here as
	// length(full_hash) = 64 only, matching the schema's own CHECK exactly
	// (docs/schema.md) -- sqlc's SQLite grammar does not support GLOB
	// ("no viable alternative at input 'GLOB'"), and full_hash is only ever
	// written by internal/hashing.FullHash, which always emits lowercase hex.
	// Plain positional params (?1/?2), not sqlc.arg: this file already has
	// earlier queries (e.g. ListTier3Candidates) using bare ?N placeholders,
	// and sqlc v1.31.1 mis-numbers/corrupts a later sqlc.arg(name) placeholder
	// in the same file when a bare ?N appears anywhere earlier in it --
	// reproduced by bisection, a real generator bug for this sqlc version, not
	// something wrong with sqlc.arg's own syntax elsewhere in the codebase.
	ListPrunableNodes(ctx context.Context, arg ListPrunableNodesParams) ([]ListPrunableNodesRow, error)
	ListRecentScanJobs(ctx context.Context, limit int64) ([]ScanJob, error)
	// The sync worker's claim query: oldest-attempt-first so a backlog drains in
	// order, capped at one batch. Scoped to a single remote -- a node can hold
	// both IMMICH and GOOGLE_PHOTOS rows under the (node_id, remote) PK, so
	// ProcessPending(remote) must never list (or re-flip) another remote's rows.
	ListRemoteSyncStateByStatus(ctx context.Context, arg ListRemoteSyncStateByStatusParams) ([]RemoteSyncState, error)
	// Backs GET /api/v1/assets/{id}/sync-status: every remote_sync_state row
	// for a node (both remotes), ordered by remote for a stable DTO.
	ListRemoteSyncStateByNode(ctx context.Context, nodeID int64) ([]RemoteSyncState, error)
	ListScanJobsFiltered(ctx context.Context, arg ListScanJobsFilteredParams) ([]ScanJob, error)
	ListStorageLocations(ctx context.Context) ([]StorageLocation, error)
	// Tier-3 spatial-temporal resolver candidate lookup: live nodes sharing
	// camera_serial with captured_at_unix within ±2 seconds of a target timestamp,
	// excluding a given node ID.
	ListTier3Candidates(ctx context.Context, arg ListTier3CandidatesParams) ([]MediaNode, error)
	// Backs POST /api/v1/assets/{id}/sync/retry (handleSyncRetry, #156): an
	// explicit operator "try again" action on a PUSH_FAILED row, bypassing
	// ResetRemoteSyncStateFailed's retry_count bound by design (see that
	// query's comment). retry_count resets to 0 here -- the same rule
	// MarkRemoteSyncStatePushed applies on a real success -- so the operator's
	// action restores a full automatic-retry budget, not just one attempt
	// before immediately re-hitting the bound on the very next failure (#182).
	//
	// last_attempt_at is deliberately left untouched, matching
	// ResetRemoteSyncStateFailed (the automatic recovery path for the same
	// PUSH_FAILED -> PENDING_CLOUD_PUSH transition), not UpsertRemoteSyncState.
	// ListRemoteSyncStateByStatus claims oldest-last_attempt_at-first, so
	// bumping it here would send a row an operator just explicitly asked to
	// retry to the BACK of the claim queue -- behind every row the automatic
	// recovery already reset. Leaving it alone keeps the row's original
	// position, so it claims promptly instead of behind a potentially large
	// backlog.
	ManualRetryRemoteSyncState(ctx context.Context, arg ManualRetryRemoteSyncStateParams) error
	MarkAgentEventFailed(ctx context.Context, arg MarkAgentEventFailedParams) error
	MarkAgentEventProcessed(ctx context.Context, id int64) error
	MarkNodeMissing(ctx context.Context, id int64) error
	// Terminal failure: records the error, the attempt time, and increments
	// retry_count -- what ResetRemoteSyncStateFailed's bound is measured against.
	MarkRemoteSyncStateFailed(ctx context.Context, arg MarkRemoteSyncStateFailedParams) error
	// Terminal success: records the remote asset id (empty for a scan-trigger
	// push) and clears any prior error. retry_count resets to 0 -- it tracks
	// consecutive failures since the last success, not a lifetime total.
	// updated_at set explicitly -- no trigger.
	//
	// remote_asset_id uses COALESCE(excluded, existing), matching
	// UpsertRemoteSyncState's pattern, not a bare overwrite: today's only
	// PushFunc (Immich's whole-library TriggerScan) never populates it, so ?3 is
	// always empty and this is currently unreachable in practice. It's still
	// fixed for symmetry -- a bare overwrite would silently NULL a previously
	// recorded id on any future call site that (unlike today's) sometimes pushes
	// without a fresh remote_asset_id in hand.
	MarkRemoteSyncStatePushed(ctx context.Context, arg MarkRemoteSyncStatePushedParams) error
	// Phase 1 (#31): at the end of a clean full scan, every ACTIVE node under the
	// scanned storage location whose last_seen_at predates the scan's start is
	// gone. TouchMediaNode/InsertMediaNode/RebaseMissingNodePath all bump
	// last_seen_at on every node the walk actually saw and committed, so anything
	// still old here was genuinely unseen this scan. KeepActive is the pass's
	// seen-but-uncertain set -- paths the walk saw but did not reliably commit
	// (processFile error, submit refused, dropped result, batch Commit failure) --
	// and is excluded from the sweep: a file on disk with a stale last_seen_at is
	// not proof it's gone. KeepActive paths are passed as a JSON array string
	// to json_each(?3) to remain within SQLite per-statement parameter bounds.
	// Scoped by storage_location_id so a scan of one mount never touches another.
	// unixepoch() is 1s granularity, so a node last seen in a scan that happened
	// to end in the SAME wall-clock second as this scan's start may survive one
	// extra scan -- it is swept the next round, which is delayed-not-wrong.
	MarkUnseenNodesMissing(ctx context.Context, arg MarkUnseenNodesMissingParams) (int64, error)
	// Checked before UpsertMediaEdge so the caller can tell a genuinely new
	// edge apart from an existing one whose confidence/evidence was merely
	// refreshed -- UpsertMediaEdge's RETURNING row looks the same either way.
	// Backs scan_jobs.edges_created (fix(pipeline): #90).
	MediaEdgeExists(ctx context.Context, arg MediaEdgeExistsParams) (bool, error)
	// Phase 1 (#89): remove node_metadata rows whose owning media_nodes row is
	// ARCHIVED. ARCHIVED nodes are superseded versions that no longer participate
	// in the live graph; their metadata is write-once historical data that grows
	// monotonically with editing activity. Pruning these rows bounds table size
	// without deleting media_nodes rows themselves (the "rows are never deleted"
	// invariant for media_nodes stands).
	PruneArchivedNodeMetadata(ctx context.Context) (int64, error)
	// Pillar 5 move detection, applied: the id and node_uuid never change, so
	// every edge referencing this node (as parent or child) survives the move
	// untouched -- no CASCADE, no rewrite needed.
	RebaseMissingNodePath(ctx context.Context, arg RebaseMissingNodePathParams) error
	RebaseNodePathByUUID(ctx context.Context, arg RebaseNodePathByUUIDParams) error
	// The metadata-inheritance endpoint (#54) is the first server-initiated
	// filesystem write: it rewrites a child's file in place via exiftool, which
	// changes size_bytes/mtime_unix/fast_hash on disk. Without this update the
	// next scan's commitOne sees a changed fast_hash at the same path and treats
	// it as a version collision -- archiving the node and minting a new
	// node_uuid, which strands every media_edges row (including a human
	// CONFIRMED/REJECTED review decision) on the archived row. Called once,
	// immediately after the write succeeds, so the DB and the file agree before
	// any scan observes the change.
	RefreshMediaNodeAfterInPlaceWrite(ctx context.Context, arg RefreshMediaNodeAfterInPlaceWriteParams) error
	// Every row still 'RUNNING' at process startup, before this process has
	// created any scan_jobs row of its own, was left behind by a previous
	// process that never reached a terminal state -- SIGKILL, OOM-kill,
	// container hard-stop, power loss. A WATCH row is RUNNING for its entire
	// process lifetime by design, so this is the only place its state ever
	// gets cleaned up after a crash. Reuses FAILED rather than adding a new
	// enum state (see issue #88's scope note): last_error distinguishes this
	// from a genuine processing failure. Must run before
	// WatcherSupervisor.Start creates any fresh WATCH row for the same
	// location, or a reconciled row and a fresh row could momentarily both
	// claim to represent "the" watch state for it. ix_scan_jobs_active
	// (state, started_at DESC) backs this WHERE clause.
	ReconcileOrphanedScanJobs(ctx context.Context, lastError sql.NullString) (int64, error)
	// See ConfirmMediaEdge's comment -- same shape, same reasoning.
	RejectMediaEdge(ctx context.Context, arg RejectMediaEdgeParams) (int64, error)
	// Crash recovery: rows left PUSHING by a process that died mid-push are reset
	// to PENDING_CLOUD_PUSH so the next worker pass re-claims them. Scoped to a
	// single remote so an IMMICH recovery can never touch GOOGLE_PHOTOS rows.
	ResetRemoteSyncStateStale(ctx context.Context, arg ResetRemoteSyncStateStaleParams) (int64, error)
	// #55/#182: worker-level retry. PUSH_FAILED rows whose last attempt is older
	// than the retry window AND whose retry_count hasn't yet reached the bound
	// are reset to PENDING_CLOUD_PUSH so the next worker pass re-attempts them --
	// a transient remote failure must not strand a batch forever. Once
	// retry_count reaches the bound, a row is left PUSH_FAILED permanently: a
	// misconfigured remote (e.g. an empty libraryId, see #182) must not retry
	// every 5 minutes forever. A human can still force a re-attempt via
	// POST /api/v1/assets/{id}/sync/retry (handleSyncRetry), which bypasses this
	// bound by design -- an explicit operator action, not an automatic loop.
	// Scoped to a single remote. last_attempt_at is set explicitly on every
	// attempt, so this only re-claims rows that have not been retried recently
	// (bounded retry frequency, not a hot loop).
	ResetRemoteSyncStateFailed(ctx context.Context, arg ResetRemoteSyncStateFailedParams) (int64, error)
	// Backs T7's regression guard: v_media_edges_resolved.parent_missing must
	// be true for every relationship_type, not just DERIVED_FROM -- the thing
	// the spec's deleted trigger (docs/schema.md fix #4) never did.
	ResolvedEdgeParentMissing(ctx context.Context, id int64) (bool, error)
	// Backs M6: storage.LoadGuard calls this to deactivate a location whose
	// root_path can't be resolved at startup (mount vanished) rather than
	// treating that as a fatal error that prevents the whole server from
	// booting -- see LoadGuard's doc comment.
	SetStorageLocationActive(ctx context.Context, arg SetStorageLocationActiveParams) error
	// Step 3 of a version collision: link the archived row to its successor,
	// once the successor's id is known (i.e. after InsertMediaNode).
	SetSupersededBy(ctx context.Context, arg SetSupersededByParams) error
	// The caller passes the effective thumb_attempts value itself (0 on a
	// successful READY -- a later invalidation starts the attempt count fresh
	// again; current+1 on a FAILED retry) rather than this query
	// incrementing/resetting on its own, so one statement serves every
	// transition -- same "caller passes effective values" contract as
	// UpdateMediaNodePromotedColumns above.
	SetThumbState(ctx context.Context, arg SetThumbStateParams) error
	// Same content at the same path, seen again on a later scan. Records that
	// and, if the row was MISSING (a file re-created at its old path), reactivates
	// it in place -- a MISSING row found alive again is not a version collision
	// and must not stay MISSING.
	TouchMediaNode(ctx context.Context, arg TouchMediaNodeParams) error
	// Escalation path for T1: computed lazily, only when fast_hash collides
	// with another live node or the file lives on a TIER3_MASTER_ARCHIVE
	// location (docs/schema.md fix #8's full_hash policy).
	UpdateMediaNodeFullHash(ctx context.Context, arg UpdateMediaNodeFullHashParams) error
	UpdateMediaNodeGraphStatus(ctx context.Context, arg UpdateMediaNodeGraphStatusParams) error
	// #197: the touched/rebased branches' backfill (reconcileAllMetadata ->
	// reconcilePromotedColumns, internal/pipeline/commit.go) refreshes the
	// promoted EXIF/XMP columns from a freshly-probed Result. Before #188 these
	// columns were repopulated incidentally whenever an in-place metadata write
	// (e.g. inherit-metadata) forced a version collision on the next scan; now
	// that the write refreshes fast_hash instead (RefreshMediaNodeAfterInPlaceWrite),
	// the node takes commitOne's Touched branch and would otherwise keep its
	// insert-time values forever -- including a XMP-xmpMM:DerivedFrom written by
	// inherit-metadata that never reaches media_nodes.derived_from_id.
	UpdateMediaNodePromotedColumns(ctx context.Context, arg UpdateMediaNodePromotedColumnsParams) error
	UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error
	// A human decision outranks any resolver, permanently: the UPDATE branch is
	// gated by a WHERE that skips rows already CONFIRMED or REJECTED entirely.
	// IMPORTANT: when that WHERE evaluates false, SQLite's RETURNING emits NO
	// ROW at all -- it does NOT return the pre-existing row unmodified (verified
	// against SQLite directly; an earlier version of this comment claimed
	// otherwise and was wrong). Because this query is :one, a human-locked edge
	// therefore surfaces to the caller as sql.ErrNoRows, which internal/graph's
	// Engine.ResolveAndCommit must treat as "edge intentionally left untouched,
	// re-fetch it and continue" -- NOT as a failure to roll the whole batch
	// back on.
	//
	// confidence only ever increases (MAX), never regresses if a later resolve
	// pass finds a weaker signal for the same edge. tier/resolver/evidence_json/
	// review_state are each keyed on WHICH SIDE actually supplied that MAX'd
	// confidence (excluded, i.e. this call's candidate, vs. the row as it stood
	// before this call) rather than being taken unconditionally from excluded or
	// re-derived from a hardcoded threshold -- both of those independently let a
	// later, weaker resolver pass silently overwrite a stronger earlier one:
	// unconditional excluded.tier/resolver/evidence_json could stamp a losing
	// pass's provenance next to a winning MAX'd confidence, and a hardcoded
	// ">= 0.90" ignored internal/graph's per-tier auto-accept threshold (0.85
	// for Tier 3), downgrading a Tier-3 AUTO_ACCEPTED edge back to NEEDS_REVIEW
	// on every subsequent scan pass. review_state is never independently
	// recomputed here at all: excluded.review_state (bind ?8) already carries
	// the tier-correct value Engine computed for this candidate, so keying it
	// the same way as confidence keeps the two permanently consistent. On an
	// exact confidence tie, `>=` deliberately favors the incoming candidate
	// (excluded) -- that's what refreshes evidence_json/resolver/timestamps on
	// an identical same-resolver re-fire, the common case. Do not tighten this
	// to `>` outright (Hermes review on PR #128 suggested exactly that for
	// review_state alone; rejected below).
	//
	// One exception carves into that `>=`: because the per-tier auto-accept
	// threshold differs by tier (0.85 for Tier 3, 0.90 otherwise), an exact
	// confidence tie between a HIGHER tier (already AUTO_ACCEPTED) and a LOWER
	// tier candidate at that same confidence (computed NEEDS_REVIEW, since it
	// doesn't clear ITS tier's higher threshold) would otherwise let the
	// lower-tier candidate win the tie and downgrade review_state -- confidence
	// doesn't regress, but review_state does, which is exactly the class of bug
	// this query exists to prevent. Each CASE below therefore adds one more
	// clause on top of the `>=` tie rule: excluded still wins ties EXCEPT the
	// specific one where the stored row is AUTO_ACCEPTED and the incoming
	// candidate computed NEEDS_REVIEW at that same confidence. Applying that
	// same exception to ALL FOUR fields together (not just review_state, as
	// Hermes' suggestion would have done) is deliberate: tier/resolver/
	// evidence_json/review_state must always
	// describe the SAME pass, so on a blocked tie the stored row's provenance
	// stays fully intact too, rather than adopting the incoming candidate's
	// tier/resolver while keeping the old review_state -- that combination
	// would itself be an inconsistent, self-contradicting row.
	UpsertMediaEdge(ctx context.Context, arg UpsertMediaEdgeParams) (MediaEdge, error)
	// Claims a node for push (or re-claims it): sets the target sync_status and
	// bumps last_attempt_at/updated_at. On a re-claim of an existing PUSH_FAILED
	// row, last_error is cleared and the existing remote_asset_id (if any) is
	// kept. Every transition sets updated_at explicitly -- no triggers, per this
	// repo's invariant. This is the ONLY way a (node_id, remote) row is created.
	UpsertRemoteSyncState(ctx context.Context, arg UpsertRemoteSyncStateParams) (RemoteSyncState, error)
	// Backs config-driven seeding at startup (cmd/branchdam): config.yaml's
	// storageLocations list is applied idempotently on every restart, keyed on
	// root_path's UNIQUE constraint, so re-running it against an
	// already-seeded database updates tier/read_only/prunable in place rather
	// than failing on the second startup. is_active is unconditionally reset
	// to 1 here -- a location present in config is presumed active until
	// storage.LoadGuard's post-seed resolvability check (M6) says otherwise
	// via SetStorageLocationActive, which is what makes a location that
	// vanished and came back self-heal on the next successful startup.
	UpsertStorageLocation(ctx context.Context, arg UpsertStorageLocationParams) (StorageLocation, error)
	// Walk the proposed child's descendants; if the proposed PARENT is already a
	// descendant of the proposed CHILD, the new edge would close a cycle. Used
	// by internal/graph (PR 7) inside the same write transaction as the edge
	// insert -- DB.InTx's single writer connection is what makes this
	// check-then-insert sound without extra application-level locking.
	//
	// The bare-parameter anchor `SELECT sqlc.arg(...)` needed an explicit alias
	// to satisfy sqlc's SQLite parser -- see docs/schema.md's sqlc risk note.
	WouldCreateCycle(ctx context.Context, arg WouldCreateCycleParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
