// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Step 1 of a version collision (docs/schema.md fix #3): archive the OLD
	// row FIRST, before inserting the new one. The partial unique index
	// (WHERE lifecycle_state != 'ARCHIVED') means a live row and a new live
	// row can never share file_path even for an instant within the
	// transaction -- archiving first, not after, is what keeps that true.
	ArchiveMediaNode(ctx context.Context, id int64) error
	// Phase 1 (#32): a WATCH job torn down by a clean shutdown ends CANCELLED,
	// not FAILED -- only a watcher that died on its own is a failure.
	CancelScanJob(ctx context.Context, id int64) error
	CompleteScanJob(ctx context.Context, id int64) error
	// #225: used when the MISSING sweep is skipped because the walk saw zero
	// files. The scan itself still completed cleanly -- state stays COMPLETED,
	// not FAILED, since a walk *error* is a distinct, already-handled failure
	// mode (see FailScanJob) -- but last_error carries a human-readable note so
	// an operator can tell "swept nothing because there was genuinely nothing to
	// see" apart from "swept nothing because the walk aborted."
	CompleteScanJobWithWarning(ctx context.Context, arg CompleteScanJobWithWarningParams) error
	// RETURNING target_node_id (rather than plain :exec) doubles as the
	// existence check: sql.ErrNoRows means id didn't match any row, which the
	// caller (internal/httpapi) turns into a 404 instead of a silent no-op
	// 200. The returned target_node_id is what the caller re-derives
	// graph_status from -- see routes.go's recomputeGraphStatus.
	ConfirmMediaEdge(ctx context.Context, arg ConfirmMediaEdgeParams) (int64, error)
	// Atomic single-use consume. The WHERE used_at IS NULL guard is the
	// whole point: a second attempt with the same token id matches zero
	// rows, and the caller treats that as "token already consumed". The
	// expires_at < ?3 guard means an expired token fails the same way
	// (no row, no error), so a stolen-expired-token doesn't reveal that
	// it was once valid.
	ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (PasswordResetToken, error)
	// Counterpart to ListActorAudit -- must apply identical WHERE so
	// pagination totals match the visible rows.
	CountActorAudit(ctx context.Context, arg CountActorAuditParams) (int64, error)
	CountAttributionUsers(ctx context.Context) (int64, error)
	CountDevicePairings(ctx context.Context) (int64, error)
	CountLoginAudit(ctx context.Context) (int64, error)
	// Comparison before IS NULL in each clause (not the reverse) is load-bearing:
	// sqlc's SQLite type inference only picks up the column's own (nullable)
	// type off the `col = sqlc.narg(...)` comparison; leading with `IS NULL`
	// makes it fall back to interface{} for every param.
	CountMediaNodesFiltered(ctx context.Context, arg CountMediaNodesFilteredParams) (int64, error)
	CountPairingAudit(ctx context.Context, pairingID int64) (int64, error)
	CountPendingAgentEvents(ctx context.Context) (int64, error)
	// Observability for #182's automatic-retry bound: how many PUSH_FAILED rows
	// for this remote have a retry_count at or past the bound, so
	// ResetRemoteSyncStateFailed will never re-claim them again on its own.
	// Backs Worker.drain's periodic "permanently abandoned" warning -- distinct
	// from ResetRemoteSyncStateFailed's `retry_count < ?3` claim filter (this is
	// its complement, `>=`), so a misconfigured remote's silent backlog is
	// visible in logs instead of only discoverable via a direct SQLite query.
	CountRemoteSyncStateExhausted(ctx context.Context, arg CountRemoteSyncStateExhaustedParams) (int64, error)
	CountRunningScanJobs(ctx context.Context) (int64, error)
	// #163/#226: called inside the same transaction as CreateScanJob (see
	// pipeline.createScanJob) so the check-then-insert is one atomic unit, not
	// just an accident of the writer pool being single-connection. Parameterized
	// on kind (rather than hardcoded to 'FULL_SCAN') since #226 added a second
	// HTTP-triggered path (POST /api/v1/scan {differential:true}) that creates
	// an INCREMENTAL job directly, which needs the same same-kind guard a
	// FULL_SCAN already got -- SweeperSupervisor's own INCREMENTAL passes are
	// still serialized by its own ticker loop (sweeper.go), so this check is a
	// no-op there, not a behavior change. WATCH jobs are excluded by the
	// caller only ever passing FULL_SCAN or INCREMENTAL here -- they're already
	// singleton-per-location via WatcherSupervisor.Start's sync.Once and are
	// long-lived by design, so they must not block (or be blocked by) either.
	CountRunningScansForLocationByKind(ctx context.Context, arg CountRunningScansForLocationByKindParams) (int64, error)
	CountScanJobsFiltered(ctx context.Context, arg CountScanJobsFilteredParams) (int64, error)
	// Local auth queries. The handlers in internal/httpapi/local_auth.go
	// and the middleware in internal/auth/session.go both go through these --
	// no raw SQL outside this file (per the project's sqlc convention,
	// documented in CONTRIBUTING.md).
	//
	// All positional params use bare ?1/?2/?3 (not sqlc.arg(name)) per AGENTS.md's
	// "SQL Syntax Traps" note.
	// Returns the total number of users. /setup/status returns readyForSetup:
	// (count == 0) so the SPA can branch between setup form and login form.
	// Cheap (no WHERE), single indexed-ish scan; called on every unauthenticated
	// request that hits the SPA shell, so kept O(1)-ish.
	CountUsers(ctx context.Context) (int64, error)
	// Lazy-provisioning insert. The caller resolves auth_provider +
	// external_uid from the Principal; username/email are denormalized
	// display fields refreshed on every ResolveOrCreate. source='forward-link'
	// with NULL password_hash matches PR #407's existing CHECK constraint --
	// these rows are attribution-only, not local-auth credentials.
	// Returns the row id on both insert and on conflict (no-op) so the
	// caller never has to distinguish "created" from "already existed" --
	// matching the ResolveOrCreate contract: get-or-create with stable id.
	// SQLite's RETURNING on ON CONFLICT DO NOTHING returns nothing for the
	// no-op case; the workaround is DO UPDATE SET on the conflict target
	// column with a no-op value so the row is "updated" (still returned) but
	// nothing actually changes.
	CreateAttributionUser(ctx context.Context, arg CreateAttributionUserParams) (int64, error)
	// Companion pairing queries. The handlers in internal/httpapi/companion_pairings.go
	// and the KeyLookup callback in internal/pairing/service.go both go through
	// these -- no raw SQL outside this file (per the project's sqlc convention,
	// documented in CONTRIBUTING.md).
	//
	// All positional params use bare ?1/?2/?3 (not sqlc.arg(name)) per AGENTS.md's
	// "SQL Syntax Traps" note.
	// Inserts the pairing row and returns it. The HTTP layer wraps this with
	// the matching KEY_MINTED audit insert in the same tx (see pairing.Service).
	// user_id is the owner FK from migration 00020; nullable so legacy
	// pairings pre-dating that migration stay valid.
	//
	// RETURNING includes user_id (the owner column) so the result struct
	// matches the new DevicePairing shape introduced by migration 00019
	// (otherwise sqlc creates a separate CreateDevicePairingRow struct that
	// breaks the service call sites, which expect the DevicePairing type).
	CreateDevicePairing(ctx context.Context, arg CreateDevicePairingParams) (DevicePairing, error)
	CreateDevicePairingKey(ctx context.Context, arg CreateDevicePairingKeyParams) (DevicePairingKey, error)
	// Inserts a source='forward-jit' user with password_hash = NULL. The
	// schema CHECK constraint enforces this. email is required (callers
	// refuse the JIT when the forward-auth email header is empty). created_by is
	// 'forward:<forward-auth username>'.
	CreateForwardJITUser(ctx context.Context, arg CreateForwardJITUserParams) (User, error)
	// Inserts a source='local' user. password_hash is the argon2id encoded
	// string. created_by is 'setup' for the first admin, 'self' for self-
	// registration flows (none in v1), or 'user:<principal name>' for admin-
	// created users. Returns the inserted row.
	CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (User, error)
	CreateManualMediaEdge(ctx context.Context, arg CreateManualMediaEdgeParams) (MediaEdge, error)
	// Minimal edge insert, landed here because PR 6's own version-collision test
	// (T5, spec 9.5) needs to prove an existing edge survives archiving its
	// source node (docs/schema.md fix #6: RESTRICT, never CASCADE). Full edge
	// resolution -- confidence scoring, cycle detection, upsert-without-
	// downgrading-review_state -- is internal/graph's job (PR 7), built on top
	// of this.
	CreateMediaEdge(ctx context.Context, arg CreateMediaEdgeParams) (MediaEdge, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	// started_by_user_id (param 3) is the per-scan attribution FK: the
	// resolved user for POST /api/v1/scan, the system user for the
	// background SweeperSupervisor's INCREMENTAL passes, NULL for the
	// always-RUNNING WATCH rows (WatcherSupervisor never sets it; those are
	// long-lived server-owned rows, not user actions).
	//
	// RETURNING includes started_by_user_id so the result struct matches
	// ScanJob after migration 00018.
	CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error)
	// Inserts a new session row. cookie_id is 32 random bytes hex-encoded
	// (length 64, CHECK-enforced). The HMAC tag over cookie_id is computed
	// at cookie-write time, NOT stored here -- sessions.cookie_id alone is
	// sufficient for lookup, the HMAC is for tamper detection (rejected by
	// the middleware before the DB lookup).
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// cache_ttl_hours defaults to 0 ("never eligible", same as handlePrune's
	// own <= 0 treatment) for the many test fixtures that don't care about it;
	// pass it explicitly when a test needs a non-zero TTL persisted on the row.
	CreateStorageLocation(ctx context.Context, arg CreateStorageLocationParams) (StorageLocation, error)
	// Backs M6: after seeding every location config.yaml currently lists,
	// deactivate any PREVIOUSLY active location whose root_path is no longer
	// among them -- an operator removing a location from config, rather than
	// it merely failing to resolve, is a deliberate decision that should also
	// self-heal storage-health/UI state without a manual DB edit. MUST NOT be
	// called with an empty currentRootPaths (cmd/branchdam guards this):
	// json_each(?1) returns ZERO rows for both NULL and '[]' (verified against
	// SQLite directly), which makes `root_path NOT IN (SELECT ... FROM
	// json_each(?1))` true for EVERY row -- the opposite failure direction
	// from MarkUnseenNodesMissing's empty-array gotcha (that one silently
	// matches nothing; this one would silently deactivate every location in
	// the database on a misconfigured or empty config.yaml).
	DeactivateStorageLocationsNotIn(ctx context.Context, currentRootPaths string) (int64, error)
	DeleteAgentScratchTelemetry(ctx context.Context, agentID string) error
	// "Revert to config" deletes the row -- this is what makes provenance
	// recoverable rather than merely resettable to some other stored value.
	DeleteAppSetting(ctx context.Context, key string) error
	// Deletes remote_sync_state records when an asset is deleted / unlinked.
	DeleteRemoteSyncStateForNode(ctx context.Context, nodeID int64) error
	// Sets disabled_at. Idempotent. Does NOT revoke existing sessions --
	// that's a separate admin action (RevokeAllUserSessions) so an admin can
	// disable future logins without immediately logging the user out.
	DisableUser(ctx context.Context, arg DisableUserParams) error
	// Backs POST /api/v1/agent/events: persists and returns 202 in increment 1.
	// Actually draining/processing these rows ships with the deferred
	// workstation-agent increment -- this table and endpoint exist now so that
	// increment is additive, not a schema migration.
	EnqueueAgentEvent(ctx context.Context, arg EnqueueAgentEventParams) (EnqueueAgentEventRow, error)
	// Lazy-provisions the "system" attribution sentinel: background workers
	// (SweeperSupervisor's INCREMENTAL passes, prune, anything that has no
	// request Principal) attribute their writes to this user. Idempotent:
	// re-running returns the same row. source='forward-link' with NULL
	// password_hash matches PR #407's existing CHECK; auth_provider='system'
	// / external_uid='system' can't collide with a real Authentik uid (those
	// are UUIDs). This is the canonical "no human behind this" attribution in
	// actor_audit and scan_jobs.started_by_user_id. The DO UPDATE SET trick
	// (see CreateAttributionUser) keeps RETURNING returning a row on conflict.
	EnsureSystemUser(ctx context.Context) (int64, error)
	FailScanJob(ctx context.Context, arg FailScanJobParams) error
	GetAgentEventByUUID(ctx context.Context, eventUuid string) (GetAgentEventByUUIDRow, error)
	GetAgentScratchTelemetry(ctx context.Context, agentID string) (AgentScratchTelemetry, error)
	// users: one row per human principal that has ever authenticated via
	// Authentik ForwardAuth. Lazily provisioned on first sight by
	// internal/users.Service.ResolveOrCreate, keyed on the stable
	// (auth_provider, external_uid) so Authentik username renames don't
	// fragment attribution.
	//
	// All positional params use bare ?1/?2 (not sqlc.arg) per AGENTS.md's
	// "SQL Syntax Traps" note.
	GetAttributionUserByExternalUID(ctx context.Context, arg GetAttributionUserByExternalUIDParams) (GetAttributionUserByExternalUIDRow, error)
	GetAttributionUserByID(ctx context.Context, id int64) (GetAttributionUserByIDRow, error)
	// Used by the handshake's pendingRotation hint to load the pairing by
	// the agent_id attached to the request's Principal.
	GetDevicePairingByAgentID(ctx context.Context, agentID string) (DevicePairing, error)
	GetDevicePairingByID(ctx context.Context, id int64) (GetDevicePairingByIDRow, error)
	// The hot path: KeyLookup runs this on every authenticated agent request.
	// UNIQUE index on key_lookup_hash keeps it O(log n). Active means
	// revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now).
	GetDevicePairingKeyByHash(ctx context.Context, keyLookupHash string) (DevicePairingKey, error)
	GetDevicePairingKeyByID(ctx context.Context, id int64) (DevicePairingKey, error)
	// Returns just the qr_svg column for the ActiveQRSVG hot path. Skips
	// the row-wide scan if all the caller wants is the bytes.
	GetDevicePairingQRSVG(ctx context.Context, id int64) ([]byte, error)
	GetLatestProcessedAgentEventByAgent(ctx context.Context, agentID string) (GetLatestProcessedAgentEventByAgentRow, error)
	// The live-path lookup a scan does for every file: is there already a
	// non-archived node at this exact path? Backed by ux_media_nodes_live_path
	// (docs/schema.md fix #3).
	GetLiveNodeByPath(ctx context.Context, filePath string) (MediaNode, error)
	GetMediaEdge(ctx context.Context, id int64) (MediaEdge, error)
	// Used by internal/graph.Engine.ResolveAndCommit when UpsertMediaEdge
	// returns sql.ErrNoRows -- the edge is CONFIRMED/REJECTED and was
	// intentionally left untouched, so the caller re-fetches its current state
	// here rather than treating the no-row RETURNING as an error.
	GetMediaEdgeBySourceTargetRel(ctx context.Context, arg GetMediaEdgeBySourceTargetRelParams) (MediaEdge, error)
	GetMediaNodeByFastHash(ctx context.Context, fastHash *string) (int64, error)
	// Strict dedup: find an active or hidden node with the given BLAKE3 full_hash.
	// Excludes ARCHIVED and MISSING nodes so re-ingesting removed content creates a fresh node.
	GetMediaNodeByFullHash(ctx context.Context, fullHash *string) (GetMediaNodeByFullHashRow, error)
	// Includes archived rows, unlike GetLiveNodeByPath -- used to verify a
	// superseded node's post-archive state (superseded_by, lifecycle_state).
	GetMediaNodeByID(ctx context.Context, id int64) (MediaNode, error)
	// Agent dedup: find an active or hidden node with the given SHA-256 source_path_hash.
	// Excludes ARCHIVED and MISSING nodes so re-ingesting removed content creates a fresh node.
	GetMediaNodeBySourcePathHash(ctx context.Context, sourcePathHash *string) (GetMediaNodeBySourcePathHashRow, error)
	GetMediaNodeByUUID(ctx context.Context, nodeUuid string) (MediaNode, error)
	// Pillar 5 move detection: a file vanished (lifecycle_state='MISSING') and
	// a new file elsewhere hashes the same -- likely the same file, moved.
	GetMissingNodeByFastHash(ctx context.Context, fastHash *string) (MediaNode, error)
	// Confirm-time lookup: scan the active-token index for a specific
	// token_hash. The active-partial unique index keeps the candidate
	// set small. The handler iterates and finds the row whose hash
	// matches -- the index narrows the scan to the small set of
	// in-flight tokens, not the entire history.
	GetPasswordResetTokenByHash(ctx context.Context, arg GetPasswordResetTokenByHashParams) (PasswordResetToken, error)
	// The idempotency look-before-write read for Enqueue: does (node_id, remote)
	// already exist, and in what state?
	GetRemoteSyncState(ctx context.Context, arg GetRemoteSyncStateParams) (RemoteSyncState, error)
	GetScanJob(ctx context.Context, id int64) (ScanJob, error)
	// Hot path: called by SessionMiddleware on every authenticated browser
	// request. Returns the full row including revoked_at so the middleware
	// can reject post-revoke cookies in one query. The partial index
	// sessions_user_active_idx covers the active-set variant but the
	// revoke check needs the full row, so we don't use it here.
	GetSessionByCookieID(ctx context.Context, cookieID string) (Session, error)
	// handlePrune (#61, #238) reads cache_ttl_hours directly off this row --
	// it no longer re-joins config by root_path to recover the TTL.
	GetStorageLocationByID(ctx context.Context, id int64) (StorageLocation, error)
	// Used by storage.Guard (PR 2) to resolve a canonicalized path to its tier --
	// the single source of truth for tier is this table, never a hardcoded
	// prefix. See docs/schema.md fix #1.
	GetStorageLocationByPath(ctx context.Context, rootPath string) (StorageLocation, error)
	// The EnsureSystemUser companion query: lookup the system user by its
	// stable sentinel (external_uid='system'), so the boot sequence can
	// capture its id before any background worker starts. Same shape as
	// GetAttributionUserByExternalUID -- named distinctly so the boot path
	// reads self-documentingly and a future "system user has been renamed"
	// rename has one obvious place to land.
	GetSystemUserID(ctx context.Context) (int64, error)
	// Used by the JIT provisioning path: a forward-auth request with email E
	// and source 'forward-jit' either matches an existing admin or triggers
	// a fresh INSERT in CreateForwardJITUser. Partial unique index
	// users_email_source_uniq covers this.
	GetUserByEmailSource(ctx context.Context, arg GetUserByEmailSourceParams) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Used by /api/v1/login to resolve the presented username to a user row.
	// The lookup is username-only; password verification happens in Go against
	// password_hash. Index: users.username UNIQUE already covers this.
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementAgentEventRetry(ctx context.Context, arg IncrementAgentEventRetryParams) error
	// actor_audit: append-only event log for admin actions that aren't
	// otherwise audited (scan start, restart, settings PUT, storage location
	// PUT, prune execute, pairing lifecycle). Mirrors companion_pairing_audit's
	// shape but cross-cutting: one table, not per-domain.
	//
	// actor_kind + actor_name carry the display identity. actor_user_id
	// (nullable) carries the FK to users when one exists, so admin/audit
	// views can filter "everything by user X" or "everything the system did"
	// without parsing the name string.
	//
	// All positional params use bare ?1/?2 (not sqlc.arg) per AGENTS.md's
	// "SQL Syntax Traps" note.
	InsertActorAudit(ctx context.Context, arg InsertActorAuditParams) error
	// Append-only. The two indexes on (user_id, created_at) and (ip, created_at)
	// cover the admin UI's tail queries without a sort.
	InsertLoginAudit(ctx context.Context, arg InsertLoginAuditParams) error
	InsertMediaNode(ctx context.Context, arg InsertMediaNodeParams) (MediaNode, error)
	// Phase 1 (#33): EXIF/ffprobe overflow. Upsert on the table's natural key so
	// a re-scan that re-derives metadata replaces rather than duplicates rows.
	InsertNodeMetadata(ctx context.Context, arg InsertNodeMetadataParams) error
	InsertPairingAudit(ctx context.Context, arg InsertPairingAuditParams) error
	// Resets a node's thumbnail generation state to PENDING with attempts
	// zeroed, so internal/thumbs.Worker regenerates it on its next pass. The
	// Cache.Write path is os.CreateTemp + os.Rename to the same node_uuid path,
	// so regeneration overwrites the stale file atomically -- no separate
	// Cache.Delete is needed alongside this reset. Called from
	// internal/httpapi's refreshNodeAfterInPlaceWrite, not from
	// internal/pipeline: fast_hash is by construction unchanged on both the
	// Touched branch (its own entry condition) and the rebase branch (it looks
	// the node up BY fast_hash), so neither ever observes a fast_hash change --
	// refreshNodeAfterInPlaceWrite is the one place a node's fast_hash changes
	// while its node_uuid is preserved (the inherit-metadata endpoint's
	// post-write DB sync, #188).
	InvalidateThumbnail(ctx context.Context, id int64) error
	// "Pending" panel: list of un-consumed, un-expired tokens for a given
	// user. The /admin/users/{id}/resets endpoint will use this in #408.
	ListActivePasswordResetTokens(ctx context.Context, arg ListActivePasswordResetTokensParams) ([]PasswordResetToken, error)
	// Admin/audit list view. Offset pagination -- audit volume is bounded
	// (one entry per admin action), so pagination drift isn't the unbounded-
	// table hazard it would be for a per-row event stream like audit_queue.
	// Filters are all sqlc.narg so a caller can filter on any subset
	// (a user-scoped "what did I do" view is actor_user_id + maybe event).
	ListActorAudit(ctx context.Context, arg ListActorAuditParams) ([]ActorAudit, error)
	ListAgentScratchTelemetry(ctx context.Context) ([]AgentScratchTelemetry, error)
	// Global pending list -- used by the admin-UI pending-resets panel
	// (PR #408). The query is intentionally cheap: the
	// password_reset_tokens_user_idx covers user_id + created_at, and the
	// partial active unique covers used_at IS NULL. With a homelab user
	// count this is < 100 rows; production-scale is a follow-up.
	ListAllActivePasswordResetTokens(ctx context.Context, arg ListAllActivePasswordResetTokensParams) ([]PasswordResetToken, error)
	// Recursively list ancestor node IDs.
	// Anchor SELECT explicitly names/aliases all columns to satisfy sqlc's SQLite parser.
	// The CAST is not a runtime coercion -- root_id is always an int64 id -- it
	// exists so sqlc infers the anchor column (and so the whole CTE) as INTEGER
	// instead of falling back to interface{}.
	ListAncestors(ctx context.Context, rootID int64) ([]int64, error)
	// The resolver (internal/settings) loads the whole table once at startup
	// and on every PUT; the table is expected to stay small (one row per
	// overridden field, never one row per node), so no pagination.
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	// Backs GET /api/v1/users (admin-only). Used by the pairing UI's
	// "Owned by" selector (when it lands -- today defaults to the creating
	// admin, see internal/pairing's CreatePairing). Capped at 200 rows in
	// the handler; this query is unbounded by design (an admin-only endpoint,
	// no pagination UI yet).
	ListAttributionUsers(ctx context.Context, arg ListAttributionUsersParams) ([]ListAttributionUsersRow, error)
	// The audit queue (spec sec. 7) is this query over review_state, not a second
	// table. v_media_edges_resolved's parent_missing works for every
	// relationship_type -- the spec's deleted trigger never did. See
	// docs/schema.md fix #4.
	ListAuditQueue(ctx context.Context, arg ListAuditQueueParams) ([]ListAuditQueueRow, error)
	// Keyset (cursor) pagination: when `before_id` is non-zero, only rows
	// ordered AFTER the (confidence, id) cursor are returned. Ordering is
	// (confidence DESC, id ASC); "after" means strictly greater in the
	// lexicographic order. When `before_id` is 0, the first page is returned
	// (no cursor constraint).
	//
	// Keyset over offset: a confirm/reject while the user is on page N
	// shifts the offset window in the offset-based query, so page N+1 may
	// duplicate or skip rows. Keyset pagination is stable across mutations
	// because the cursor is a row identity, not a position.
	//
	// The tie-break for same-confidence rows uses `e.id > cursor.id` (not `<`)
	// because the ordering is `id ASC`: within a confidence tier, the lower
	// id comes first, so "after" the cursor means higher id. A `<` tie-break
	// would duplicate rows on the previous page and skip the rows that should
	// be on this one.
	//
	// `total` is returned as a column on every row via a separate subquery,
	// avoiding a second COUNT(*) query per page turn and the race where a
	// confirmation between the list and the count makes total disagree with
	// what the list shows. The subquery applies only the review_state
	// filter, so total always reflects the full NEEDS_REVIEW set regardless
	// of cursor.
	//
	// The cursor (confidence, id) is resolved in a CTE first, then the main
	// query references it, rather than inlining `SELECT confidence, id FROM
	// media_edges WHERE id = ...` as a subquery at each of its two use sites
	// below -- clearer to read and cheaper to plan than repeating the same
	// lookup twice per row. (An earlier version of this comment attributed the
	// CTE to a sqlc v1.31.1 placeholder-counting bug; disproven by issue #413's
	// fix -- sqlc.arg(before_id) used twice below, once inside the CTE and once
	// in the outer WHERE, correctly collapses to a single BeforeID field.)
	ListAuditQueueDetailed(ctx context.Context, arg ListAuditQueueDetailedParams) ([]ListAuditQueueDetailedRow, error)
	// COALESCE is not a null-guard here -- the WHERE clause already excludes
	// NULL/empty camera_model -- it exists so sqlc infers []string instead of
	// []sql.NullString: camera_model is a nullable column (00001_init.sql), and
	// sqlc's SQLite type inference can't see that this query's own WHERE makes
	// the result always non-NULL.
	ListCameraModelFacets(ctx context.Context) ([]string, error)
	// Recursively list descendant node IDs.
	// Anchor SELECT explicitly names/aliases all columns to satisfy sqlc's SQLite parser.
	// The CAST is not a runtime coercion -- root_id is always an int64 id -- it
	// exists so sqlc infers the anchor column (and so the whole CTE) as INTEGER
	// instead of falling back to interface{}.
	ListDescendants(ctx context.Context, rootID int64) ([]int64, error)
	// One row per pairing with a count of currently-active keys (NULL -> 0)
	// and the earliest unexpired-but-soon-to-expire key (NULL if all keys
	// are permanent or none). Used by the SPA's list view to render the
	// grace-window countdown for in-progress rotations.
	ListDevicePairings(ctx context.Context, arg ListDevicePairingsParams) ([]ListDevicePairingsRow, error)
	// See ListEdgesByMultipleTargets above; this is the symmetric query for
	// children edges at depth d+1.
	ListEdgesByMultipleSources(ctx context.Context, dollar_1 string) ([]MediaEdge, error)
	// Batch lookup of edges by a JSON-encoded array of target_node_ids, used by
	// handleAssetLineage's bounded BFS to fetch every parent edge at depth d+1
	// in one query rather than one per node. Excludes REJECTED edges here (not
	// in Go) so a rejected lineage link can never re-admit its source node into
	// the traversal via a later level.
	ListEdgesByMultipleTargets(ctx context.Context, dollar_1 string) ([]MediaEdge, error)
	ListEdgesBySource(ctx context.Context, sourceNodeID int64) ([]MediaEdge, error)
	ListEdgesByTarget(ctx context.Context, targetNodeID int64) ([]MediaEdge, error)
	ListEdgesForNodes(ctx context.Context, dollar_1 string) ([]ListEdgesForNodesRow, error)
	ListKeysByPairing(ctx context.Context, pairingID int64) ([]DevicePairingKey, error)
	// Tier-2 xmpOriginalDocumentID resolver: a child's XMP:OriginalDocumentID
	// matching a candidate parent's document_id is a near-certain lineage
	// signal (confidence 0.95).
	ListLiveNodesByDocumentID(ctx context.Context, documentID sql.NullString) ([]MediaNode, error)
	// T1 (spec 9.5): before assuming two same-fast_hash files at DIFFERENT live
	// paths are the same content, the pipeline needs every other live node
	// sharing that fast_hash so it can escalate to full_hash and compare.
	ListLiveNodesByFastHash(ctx context.Context, fastHash *string) ([]MediaNode, error)
	// Look up live media nodes sharing exact file_name for fallback path matching.
	ListLiveNodesByFileName(ctx context.Context, fileName string) ([]MediaNode, error)
	// Tier-2 filenameStem resolver: candidate parents sharing a normalized
	// filename stem with the child, scored further by capture day / camera /
	// directory match in internal/graph. Capped at ?2 rows -- defense in depth
	// on top of (not instead of) versionSuffixRe's own -\d{1,2} bound
	// (internal/pipeline/commit.go), which narrows but does not close the
	// over-collapse bug class: an unpadded 1-2 digit hyphen-numbering scheme
	// can still produce a large same-stem batch. FilenameStemResolver logs
	// when this cap is actually hit.
	ListLiveNodesByFilenameStem(ctx context.Context, arg ListLiveNodesByFilenameStemParams) ([]MediaNode, error)
	// #55: the sync worker's enqueue source -- live nodes under a path prefix
	// (the Immich export mount) that have NO remote_sync_state row for the given
	// remote yet. Once pushed, a row exists and the node drops out of this set.
	ListLiveNodesForSync(ctx context.Context, arg ListLiveNodesForSyncParams) ([]ListLiveNodesForSyncRow, error)
	// login_audit: append-only log of authentication events (PR #407).
	// Read by /api/v1/audit?type=login alongside /api/v1/audit?type=activity
	// (which reads actor_audit). login_audit is owned by internal/auth/users;
	// these queries are kept here so the merged audit route can read both
	// tables through the same sqlcgen layer without a second db call site.
	//
	// All positional params use bare ?1/?2 (not sqlc.arg) per AGENTS.md's
	// "SQL Syntax Traps" note.
	// Newest-first. Offset pagination -- volume is bounded by authentication
	// events (not per-asset), so the drift problem that justifies keyset
	// pagination on /api/v1/edges/audit doesn't apply here.
	ListLoginAudit(ctx context.Context, arg ListLoginAuditParams) ([]ListLoginAuditRow, error)
	// Backs POST /api/v1/agent/node-status: bulk status check for a batch of UUIDs.
	// Returns node_uuid, lifecycle_state, full_hash (for verification check), and storage location tier.
	ListMediaNodeStatusesByUUIDs(ctx context.Context, nodeUuids string) ([]ListMediaNodeStatusesByUUIDsRow, error)
	// Backs GET /api/v1/assets. Excludes archived rows by default -- an
	// archived node is reachable via its successor's superseded history, not
	// the main asset list.
	ListMediaNodes(ctx context.Context, arg ListMediaNodesParams) ([]MediaNode, error)
	// Comparison before IS NULL in each clause (not the reverse) is load-bearing:
	// sqlc's SQLite type inference only picks up the column's own (nullable)
	// type off the `col = sqlc.narg(...)` comparison; leading with `IS NULL`
	// makes it fall back to interface{} for every param.
	ListMediaNodesFiltered(ctx context.Context, arg ListMediaNodesFilteredParams) ([]MediaNode, error)
	ListNodeCountsByLocation(ctx context.Context) ([]ListNodeCountsByLocationRow, error)
	// Backs tests and any future metadata inspector UI.
	ListNodeMetadata(ctx context.Context, nodeID int64) ([]NodeMetadatum, error)
	// Column list matches the media_nodes table exactly (including
	// source_path_hash, added by 00015_source_path_hash.sql) so sqlc maps this
	// to the shared MediaNode struct instead of minting a one-off Row type.
	ListNodesByIDs(ctx context.Context, dollar_1 string) ([]MediaNode, error)
	// Offset pagination. Audit log for a single pairing is bounded (a few
	// hundred events over the lifetime of a device, never tens of thousands),
	// so offset drift isn't a concern the way it is for the unbounded
	// audit_queue edge-review list.
	ListPairingAudit(ctx context.Context, arg ListPairingAuditParams) ([]CompanionPairingAudit, error)
	ListPendingAgentEvents(ctx context.Context, limit int64) ([]ListPendingAgentEventsRow, error)
	// internal/thumbs.Worker's claim query: up to ?2 PENDING nodes oldest-first
	// (by id, this codebase's usual FIFO tiebreak), backed by 00007's partial
	// index idx_media_nodes_thumb_pending (WHERE thumb_state = 'PENDING'), so
	// the index stays cheap as the backlog drains rather than scanning every
	// row regardless of state. thumb_attempts < ?1 excludes a node that has
	// already exhausted the worker's retry bound -- a permanently-broken
	// source (corrupt file, unsupported format that errors rather than
	// returning thumbs.ErrUnsupported) stops being retried every pass forever,
	// mirroring remote_sync_state's retry_count bound
	// (ResetRemoteSyncStateFailed). lifecycle_state excludes MISSING/ARCHIVED:
	// there is no live file left to read a thumbnail from.
	//
	// Joined against storage_locations to exclude TIER0_LOCAL_STAGING (#231):
	// workstation-local staging a future offline-ingest agent may record a node
	// for before its bytes have synced anywhere server-visible. Without this,
	// the worker claims a node whose file the server can never open, fails,
	// and burns a retry (and real read I/O against whatever remote/NFS tier it
	// probes) every pass until thumb_attempts hits its bound -- self-limiting
	// but noisy, and never productive. No other tier is excluded here: Tier 1
	// scratch, Tier 2 exports, Tier 3 masters, and PROJECTS are all
	// server-readable.
	ListPendingThumbnails(ctx context.Context, arg ListPendingThumbnailsParams) ([]ListPendingThumbnailsRow, error)
	// #61's TTL cache pruning eligibility: a Tier-1 node past its TTL
	// (mtime_unix < cutoff_unix) is only a candidate if a LIVE ancestor on a
	// TIER3_MASTER_ARCHIVE location has a verified (non-NULL, 64-hex) full_hash.
	// "live" matches v_media_edges_resolved's own parent_alive definition --
	// ACTIVE or HIDDEN, deliberately not the looser "!= ARCHIVED" -- so a
	// vanished (MISSING) or archived Tier-3 master can never authorize a purge.
	// Ancestor, not "same full_hash": walks media_edges target->source
	// (REJECTED edges excluded, and each walked node must itself be non-ARCHIVED),
	// mirroring ListAncestors' direction convention and its ARCHIVED-intermediate
	// exclusion exactly -- a chain that only connects through a superseded
	// version doesn't represent the file currently on disk.
	// Tier-1-only and prunable-only are already schema-enforced
	// (00001_init.sql's CHECK (tier = 'TIER1_LOCAL_SCRATCH' OR prunable = 0)) --
	// not re-checked here; the caller only invokes this against a location it
	// already knows is prunable.
	//
	// Every column in each anchor SELECT is explicitly named/aliased -- sqlc's
	// SQLite parser fails with `*ast.ResTarget has nil name` otherwise (see
	// docs/schema.md's sqlc risk note). "64-hex" is enforced here as
	// length(full_hash) = 64 only, matching the schema's own CHECK exactly
	// (docs/schema.md) -- sqlc's SQLite grammar does not support GLOB
	// ("no viable alternative at input 'GLOB'"), and full_hash is only ever
	// written by internal/hashing.FullHash, which always emits lowercase hex.
	ListPrunableNodes(ctx context.Context, arg ListPrunableNodesParams) ([]ListPrunableNodesRow, error)
	ListRecentScanJobs(ctx context.Context, limit int64) ([]ScanJob, error)
	// Backs GET /api/v1/assets/{id}/sync-status: every remote_sync_state row for
	// a node (both remotes), ordered by remote for a stable DTO.
	ListRemoteSyncStateByNode(ctx context.Context, nodeID int64) ([]RemoteSyncState, error)
	// The sync worker's claim query: oldest-attempt-first so a backlog drains in
	// order, capped at one batch. Scoped to a single remote -- a node can hold
	// both IMMICH and GOOGLE_PHOTOS rows under the (node_id, remote) PK, so
	// ProcessPending(remote) must never list (or re-flip) another remote's rows.
	ListRemoteSyncStateByStatus(ctx context.Context, arg ListRemoteSyncStateByStatusParams) ([]RemoteSyncState, error)
	ListScanJobsFiltered(ctx context.Context, arg ListScanJobsFilteredParams) ([]ScanJob, error)
	ListStorageLocations(ctx context.Context) ([]StorageLocation, error)
	// Tier-3 spatial-temporal resolver candidate lookup: live nodes sharing
	// camera_serial with captured_at_unix within +/-2 seconds of a target timestamp,
	// excluding a given node ID.
	ListTier3Candidates(ctx context.Context, arg ListTier3CandidatesParams) ([]MediaNode, error)
	// Paginated user list for the admin UI. Order by id ASC so paging is
	// stable across inserts (new users go to the END, not the middle).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Walks ancestor lineage target->source for node ?1 (REJECTED edges and
	// ARCHIVED nodes excluded) and returns every live ancestor on a
	// TIER3_MASTER_ARCHIVE location with a verified full_hash.
	// Used by internal/prune.Execute to re-verify the ancestor file on disk (via
	// os.Lstat) immediately before deleting the candidate (#246, #352).
	ListVerifiedTier3Ancestors(ctx context.Context, id int64) ([]ListVerifiedTier3AncestorsRow, error)
	// Backs POST /api/v1/assets/{id}/sync/retry (handleSyncRetry, #156): an
	// explicit operator "try again" action on a PUSH_FAILED row, bypassing
	// ResetRemoteSyncStateFailed's retry_count bound by design (see that
	// query's comment). retry_count resets to 0 here -- the same rule
	// MarkRemoteSyncStatePushed applies on a real success -- so the operator's
	// action restores a full automatic-retry budget, not just one attempt
	// before immediately re-hitting the bound on the very next failure (#182).
	//
	// last_attempt_at is deliberately left untouched, matching
	// ResetRemoteSyncStateFailed (the automatic recovery path for the same
	// PUSH_FAILED -> PENDING_CLOUD_PUSH transition), not UpsertRemoteSyncState.
	// ListRemoteSyncStateByStatus claims oldest-last_attempt_at-first, so
	// bumping it here would send a row an operator just explicitly asked to
	// retry to the BACK of the claim queue -- behind every row the automatic
	// recovery already reset. Leaving it alone keeps the row's original
	// position, so it claims promptly instead of behind a potentially large
	// backlog.
	ManualRetryRemoteSyncState(ctx context.Context, arg ManualRetryRemoteSyncStateParams) error
	MarkAgentEventFailed(ctx context.Context, arg MarkAgentEventFailedParams) error
	MarkAgentEventProcessed(ctx context.Context, id int64) error
	MarkNodeMissing(ctx context.Context, id int64) error
	// Terminal failure: records the error, the attempt time, and increments
	// retry_count -- what ResetRemoteSyncStateFailed's bound is measured against.
	MarkRemoteSyncStateFailed(ctx context.Context, arg MarkRemoteSyncStateFailedParams) error
	// Terminal success: records the remote asset id (empty for a scan-trigger
	// push) and clears any prior error. retry_count resets to 0 -- it tracks
	// consecutive failures since the last success, not a lifetime total.
	// updated_at set explicitly -- no trigger.
	//
	// remote_asset_id uses COALESCE(excluded, existing), matching
	// UpsertRemoteSyncState's pattern, not a bare overwrite: today's only
	// PushFunc (Immich's whole-library TriggerScan) never populates it, so ?3 is
	// always empty and this is currently unreachable in practice. It's still
	// fixed for symmetry -- a bare overwrite would silently NULL a previously
	// recorded id on any future call site that (unlike today's) sometimes pushes
	// without a fresh remote_asset_id in hand.
	MarkRemoteSyncStatePushed(ctx context.Context, arg MarkRemoteSyncStatePushedParams) error
	// Phase 1 (#31): at the end of a clean full scan, every ACTIVE node under the
	// scanned storage location whose last_seen_at predates the scan's start is
	// gone. TouchMediaNode/InsertMediaNode/RebaseMissingNodePath all bump
	// last_seen_at on every node the walk actually saw and committed, so anything
	// still old here was genuinely unseen this scan. KeepActive is the pass's
	// seen-but-uncertain set -- paths the walk saw but did not reliably commit
	// (processFile error, submit refused, dropped result, batch Commit failure) --
	// and is excluded from the sweep: a file on disk with a stale last_seen_at is
	// not proof it's gone. KeepActive paths are passed as a JSON array string
	// to json_each(sqlc.arg(keep_active_paths)) to remain within SQLite
	// per-statement parameter bounds.
	// Scoped by storage_location_id so a scan of one mount never touches another.
	// unixepoch() is 1s granularity, so a node last seen in a scan that happened
	// to end in the SAME wall-clock second as this scan's start may survive one
	// extra scan -- it is swept the next round, which is delayed-not-wrong.
	MarkUnseenNodesMissing(ctx context.Context, arg MarkUnseenNodesMissingParams) (int64, error)
	// Checked before UpsertMediaEdge so the caller can tell a genuinely new
	// edge apart from an existing one whose confidence/evidence was merely
	// refreshed -- UpsertMediaEdge's RETURNING row looks the same either way.
	// Backs scan_jobs.edges_created (fix(pipeline): #90).
	MediaEdgeExists(ctx context.Context, arg MediaEdgeExistsParams) (bool, error)
	// Used by /agent/handshake to find the device's newest unexpired key that
	// the caller hasn't been told about yet. ?2 is the caller's current
	// key_id; we filter strictly newer (created_at, id) so the caller is
	// never told about an older key they already missed or were using before.
	// Returns no rows (sql.ErrNoRows) when the caller is already on the
	// newest active key.
	NewestActiveKeyForPairing(ctx context.Context, arg NewestActiveKeyForPairingParams) (DevicePairingKey, error)
	// Phase 1 (#89): remove node_metadata rows whose owning media_nodes row is
	// ARCHIVED. ARCHIVED nodes are superseded versions that no longer participate
	// in the live graph; their metadata is write-once historical data that grows
	// monotonically with editing activity. Pruning these rows bounds table size
	// without deleting media_nodes rows themselves (the "rows are never deleted"
	// invariant for media_nodes stands).
	PruneArchivedNodeMetadata(ctx context.Context) (int64, error)
	// Pillar 5 move detection, applied: the id and node_uuid never change, so
	// every edge referencing this node (as parent or child) survives the move
	// untouched -- no CASCADE, no rewrite needed.
	RebaseMissingNodePath(ctx context.Context, arg RebaseMissingNodePathParams) error
	RebaseNodePathByUUID(ctx context.Context, arg RebaseNodePathByUUIDParams) error
	// Every row still 'RUNNING' at process startup, before this process has
	// created any scan_jobs row of its own, was left behind by a previous
	// process that never reached a terminal state -- SIGKILL, OOM-kill,
	// container hard-stop, power loss. A WATCH row is RUNNING for its entire
	// process lifetime by design, so this is the only place its state ever
	// gets cleaned up after a crash. Reuses FAILED rather than adding a new
	// enum state (see issue #88's scope note): last_error distinguishes this
	// from a genuine processing failure. Must run before
	// WatcherSupervisor.Start creates any fresh WATCH row for the same
	// location, or a reconciled row and a fresh row could momentarily both
	// claim to represent "the" watch state for it. ix_scan_jobs_active
	// (state, started_at DESC) backs this WHERE clause.
	ReconcileOrphanedScanJobs(ctx context.Context, lastError sql.NullString) (int64, error)
	// Updates the denormalized username/email (a user may have renamed since
	// their last request) and bumps last_seen_at. Called by
	// ResolveOrCreate after a cache miss, in the same transaction as the
	// create-or-no-op insert above. No-op on a missing row (the create
	// branch above will have just inserted one in the same tx).
	RefreshAttributionUserSeen(ctx context.Context, arg RefreshAttributionUserSeenParams) error
	// The metadata-inheritance endpoint (#54) is the first server-initiated
	// filesystem write: it rewrites a child's file in place via exiftool, which
	// changes size_bytes/mtime_unix/fast_hash on disk. Without this update the
	// next scan's commitOne sees a changed fast_hash at the same path and treats
	// it as a version collision -- archiving the node and minting a new
	// node_uuid, which strands every media_edges row (including a human
	// CONFIRMED/REJECTED review decision) on the archived row. Called once,
	// immediately after the write succeeds, so the DB and the file agree before
	// any scan observes the change.
	//
	// full_hash is always cleared and INDEXED_FULL is downgraded to
	// INDEXED_SHALLOW: the write changed the file's bytes, so any previously
	// computed BLAKE3 full_hash no longer matches it. Once fast_hash agrees
	// again this row takes commitOne's Touched branch on the next scan, which
	// never recomputes full_hash on its own (needsFullHash escalates based on
	// current tier/collision state, not on the node's prior indexing_status) --
	// so a stale full_hash would otherwise persist forever, masquerading as a
	// verified integrity fingerprint it no longer is (docs/schema.md fix #8).
	RefreshMediaNodeAfterInPlaceWrite(ctx context.Context, arg RefreshMediaNodeAfterInPlaceWriteParams) error
	// See ConfirmMediaEdge's comment -- same shape, same reasoning.
	RejectMediaEdge(ctx context.Context, arg RejectMediaEdgeParams) (int64, error)
	// #55/#182: worker-level retry. PUSH_FAILED rows whose last attempt is older
	// than the retry window AND whose retry_count hasn't yet reached the bound
	// are reset to PENDING_CLOUD_PUSH so the next worker pass re-attempts them --
	// a transient remote failure must not strand a batch forever. Once
	// retry_count reaches the bound, a row is left PUSH_FAILED permanently: a
	// misconfigured remote (e.g. an empty libraryId, see #182) must not retry
	// every 5 minutes forever. A human can still force a re-attempt via
	// POST /api/v1/assets/{id}/sync/retry (handleSyncRetry), which bypasses this
	// bound by design -- an explicit operator action, not an automatic loop.
	// Scoped to a single remote. last_attempt_at is set explicitly on every
	// attempt, so this only re-claims rows that have not been retried recently
	// (bounded retry frequency, not a hot loop).
	ResetRemoteSyncStateFailed(ctx context.Context, arg ResetRemoteSyncStateFailedParams) (int64, error)
	// Crash recovery: rows left PUSHING by a process that died mid-push are reset
	// to PENDING_CLOUD_PUSH so the next worker pass re-claims them. Scoped to a
	// single remote so an IMMICH recovery can never touch GOOGLE_PHOTOS rows.
	ResetRemoteSyncStateStale(ctx context.Context, arg ResetRemoteSyncStateStaleParams) (int64, error)
	// Backs T7's regression guard: v_media_edges_resolved.parent_missing must
	// be true for every relationship_type, not just DERIVED_FROM -- the thing
	// the spec's deleted trigger (docs/schema.md fix #4) never did.
	ResolvedEdgeParentMissing(ctx context.Context, id int64) (bool, error)
	RevokeAllKeysForPairing(ctx context.Context, arg RevokeAllKeysForPairingParams) error
	// Used by admin "log out everywhere" action and by DisableUser's
	// companion flow (future admin endpoint). Idempotent.
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	// Sets revoked_at on the pairing (does NOT touch keys -- the HTTP layer
	// also revokes every key for the pairing in the same tx).
	RevokeDevicePairing(ctx context.Context, arg RevokeDevicePairingParams) error
	// Admin "delete" / revoke. Idempotent: revoking an already-used or
	// already-expired token matches the row but is a no-op.
	RevokePasswordResetToken(ctx context.Context, arg RevokePasswordResetTokenParams) error
	// Sets revoked_at on a single session (used by DELETE /api/v1/session).
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	// Rotation: set expires_at on every currently-active key for this pairing
	// that doesn't already have one. Idempotent -- re-running after the same
	// clock has no effect.
	SetActiveKeyExpirations(ctx context.Context, arg SetActiveKeyExpirationsParams) error
	// Backs M6: storage.LoadGuard calls this to deactivate a location whose
	// root_path can't be resolved at startup (mount vanished) rather than
	// treating that as a fatal error that prevents the whole server from
	// booting -- see LoadGuard's doc comment.
	SetStorageLocationActive(ctx context.Context, arg SetStorageLocationActiveParams) error
	// Step 3 of a version collision: link the archived row to its successor,
	// once the successor's id is known (i.e. after InsertMediaNode).
	SetSupersededBy(ctx context.Context, arg SetSupersededByParams) error
	// The caller passes the effective thumb_attempts value itself (0 on a
	// successful READY -- a later invalidation starts the attempt count fresh
	// again; current+1 on a FAILED retry) rather than this query
	// incrementing/resetting on its own, so one statement serves every
	// transition -- same "caller passes effective values" contract as
	// UpdateMediaNodePromotedColumns above.
	SetThumbState(ctx context.Context, arg SetThumbStateParams) error
	// Same content at the same path, seen again on a later scan. Records that
	// and, if the row was MISSING (a file re-created at its old path), reactivates
	// it in place -- a MISSING row found alive again is not a version collision
	// and must not stay MISSING.
	//
	// The WHERE lifecycle_state != 'ARCHIVED' clause and MISSING-only CASE
	// make #226's now-possible concurrent FULL_SCAN + manual differential
	// INCREMENTAL against the same Tier-3 location safe rather than merely
	// untested: if a concurrent FULL_SCAN archives this node (a version
	// collision on the same path) between the differential sweep's
	// sweepUnchanged check and its deferred touchBatcher flush, this UPDATE
	// matches zero rows against the now-ARCHIVED row id. The touch is a clean
	// no-op, never updating dead audit trail timestamps or resurrecting into
	// a live duplicate alongside the FULL_SCAN's freshly inserted successor
	// row. See TestConcurrentFullScanArchiveDoesNotResurrectViaDifferentialTouch
	// in internal/pipeline for the regression test.
	TouchMediaNode(ctx context.Context, arg TouchMediaNodeParams) error
	// Updates last_seen_at and idle_expires_at. Called by SessionMiddleware
	// after a successful auth (sliding idle window). One statement per
	// request, but the WHERE matches the active-set partial index path
	// already loaded above so the planner is happy.
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	// Refresh the cached QR SVG after a key rotation. The SVG is computed
	// outside the transaction (in pairing.Service) so this UPDATE is a
	// pure byte-write with no rendering dependency.
	UpdateDevicePairingQRSVG(ctx context.Context, arg UpdateDevicePairingQRSVGParams) error
	// Escalation path for T1: computed lazily, only when fast_hash collides
	// with another live node or the file lives on a TIER3_MASTER_ARCHIVE
	// location (docs/schema.md fix #8's full_hash policy).
	UpdateMediaNodeFullHash(ctx context.Context, arg UpdateMediaNodeFullHashParams) error
	UpdateMediaNodeGraphStatus(ctx context.Context, arg UpdateMediaNodeGraphStatusParams) error
	// #197: the touched/rebased branches' backfill (reconcileAllMetadata ->
	// reconcilePromotedColumns, internal/pipeline/commit.go) refreshes the
	// promoted EXIF/XMP columns from a freshly-probed Result. Before #188 these
	// columns were repopulated incidentally whenever an in-place metadata write
	// (e.g. inherit-metadata) forced a version collision on the next scan; now
	// that the write refreshes fast_hash instead (RefreshMediaNodeAfterInPlaceWrite),
	// the node takes commitOne's Touched branch and would otherwise keep its
	// insert-time values forever -- including a XMP-xmpMM:DerivedFrom written by
	// inherit-metadata that never reaches media_nodes.derived_from_id.
	//
	// captured_at_unix (#204) is included on the same overwrite-on-differ
	// contract as the other six, not fill-only-when-NULL: UpsertMediaEdge's
	// confidence = MAX(excluded, stored) makes re-resolution monotone (it can
	// only upgrade or leave an edge, never downgrade or delete one), so a value
	// that changes here can at worst strand an already-committed Tier-3 edge at
	// its old confidence -- not corrupt it -- while a NULL that never gets
	// promoted is a permanent, not just temporary, blind spot for
	// HeuristicSpatialTemporalResolver. See reconcilePromotedColumns' doc
	// comment for the full reasoning, including why the inherit-metadata path's
	// circular evidence (a child temporally matching the parent because the
	// parent's own timestamp was just copied into it) is benign: every resolver
	// derives Rel from the same inferRelationship, so a Tier-3 candidate always
	// merges into the same (parent, child, rel) group as any stronger Tier-2
	// edge and never creates a second one.
	//
	// The caller passes effective values: a column whose fresh probe value was
	// empty or unchanged is passed through as the node's current value, so this
	// query is only ever reached with at least one genuine change.
	UpdateMediaNodePromotedColumns(ctx context.Context, arg UpdateMediaNodePromotedColumnsParams) error
	UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error
	// Rotates the password hash. Used by /api/v1/password-reset/confirm
	// (self-service) and /api/v1/admin/users/{id}/reset-password (admin).
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error)
	UpsertAgentScratchTelemetry(ctx context.Context, arg UpsertAgentScratchTelemetryParams) (AgentScratchTelemetry, error)
	// The row's mere existence is the override -- callers pass "" for value
	// exactly when the operator wants "explicitly empty", never as a signal to
	// skip the write. See internal/settings/resolver.go for why an empty
	// override still beats a populated config/env base value. updated_at is
	// set via unixepoch() here, not passed from Go, matching every other
	// UPDATE/upsert in this package (docs/schema.md fix #5).
	UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error)
	// A human decision outranks any resolver, permanently: the UPDATE branch is
	// gated by a WHERE that skips rows already CONFIRMED or REJECTED entirely.
	// IMPORTANT: when that WHERE evaluates false, SQLite's RETURNING emits NO
	// ROW at all -- it does NOT return the pre-existing row unmodified (verified
	// against SQLite directly; an earlier version of this comment claimed
	// otherwise and was wrong). Because this query is :one, a human-locked edge
	// therefore surfaces to the caller as sql.ErrNoRows, which internal/graph's
	// Engine.ResolveAndCommit must treat as "edge intentionally left untouched,
	// re-fetch it and continue" -- NOT as a failure to roll the whole batch
	// back on.
	//
	// confidence only ever increases (MAX), never regresses if a later resolve
	// pass finds a weaker signal for the same edge. tier/resolver/evidence_json/
	// review_state are each keyed on WHICH SIDE actually supplied that MAX'd
	// confidence (excluded, i.e. this call's candidate, vs. the row as it stood
	// before this call) rather than being taken unconditionally from excluded or
	// re-derived from a hardcoded threshold -- both of those independently let a
	// later, weaker resolver pass silently overwrite a stronger earlier one:
	// unconditional excluded.tier/resolver/evidence_json could stamp a losing
	// pass's provenance next to a winning MAX'd confidence, and a hardcoded
	// ">= 0.90" ignored internal/graph's per-tier auto-accept threshold (0.85
	// for Tier 3), downgrading a Tier-3 AUTO_ACCEPTED edge back to NEEDS_REVIEW
	// on every subsequent scan pass. review_state is never independently
	// recomputed here at all: excluded.review_state (bind ?8) already carries
	// the tier-correct value Engine computed for this candidate, so keying it
	// the same way as confidence keeps the two permanently consistent. On an
	// exact confidence tie, `>=` deliberately favors the incoming candidate
	// (excluded) -- that's what refreshes evidence_json/resolver/timestamps on
	// an identical same-resolver re-fire, the common case. Do not tighten this
	// to `>` outright (Hermes review on PR #128 suggested exactly that for
	// review_state alone; rejected below).
	//
	// One exception carves into that `>=`: because the per-tier auto-accept
	// threshold differs by tier (0.85 for Tier 3, 0.90 otherwise), an exact
	// confidence tie between a HIGHER tier (already AUTO_ACCEPTED) and a LOWER
	// tier candidate at that same confidence (computed NEEDS_REVIEW, since it
	// doesn't clear ITS tier's higher threshold) would otherwise let the
	// lower-tier candidate win the tie and downgrade review_state -- confidence
	// doesn't regress, but review_state does, which is exactly the class of bug
	// this query exists to prevent. Each CASE below therefore adds one more
	// clause on top of the `>=` tie rule: excluded still wins ties EXCEPT the
	// specific one where the stored row is AUTO_ACCEPTED and the incoming
	// candidate computed NEEDS_REVIEW at that same confidence. Applying that
	// same exception to ALL FOUR fields together (not just review_state, as
	// Hermes' suggestion would have done) is deliberate: tier/resolver/
	// evidence_json/review_state must always
	// describe the SAME pass, so on a blocked tie the stored row's provenance
	// stays fully intact too, rather than adopting the incoming candidate's
	// tier/resolver while keeping the old review_state -- that combination
	// would itself be an inconsistent, self-contradicting row.
	UpsertMediaEdge(ctx context.Context, arg UpsertMediaEdgeParams) (MediaEdge, error)
	// Claims a node for push (or re-claims it): sets the target sync_status and
	// bumps last_attempt_at/updated_at. On a re-claim of an existing PUSH_FAILED
	// row, last_error is cleared and the existing remote_asset_id (if any) is
	// kept. Every transition sets updated_at explicitly -- no triggers, per this
	// repo's invariant. This is the ONLY way a (node_id, remote) row is created.
	UpsertRemoteSyncState(ctx context.Context, arg UpsertRemoteSyncStateParams) (RemoteSyncState, error)
	// Backs config-driven seeding at startup (cmd/branchdam): config.yaml's
	// storageLocations list is applied idempotently on every restart, keyed on
	// root_path's UNIQUE constraint, so re-running it against an
	// already-seeded database updates tier/read_only/prunable/cache_ttl_hours
	// in place rather than failing on the second startup. is_active is
	// unconditionally reset to 1 here -- a location present in config is
	// presumed active until storage.LoadGuard's post-seed resolvability check
	// (M6) says otherwise via SetStorageLocationActive, which is what makes a
	// location that vanished and came back self-heal on the next successful
	// startup.
	//
	// cache_ttl_hours is persisted here (#238) instead of being re-joined from
	// the live config by root_path at prune time -- that re-join silently
	// orphaned a location's TTL whenever its rootPath was edited, since the
	// new row (a different root_path) never matched the old config entry
	// until the strings lined up again.
	UpsertStorageLocation(ctx context.Context, arg UpsertStorageLocationParams) (StorageLocation, error)
	// Walk the proposed child's descendants; if the proposed PARENT is already a
	// descendant of the proposed CHILD, the new edge would close a cycle. Used
	// by internal/graph (PR 7) inside the same write transaction as the edge
	// insert -- DB.InTx's single writer connection is what makes this
	// check-then-insert sound without extra application-level locking.
	//
	// The bare-parameter anchor `SELECT sqlc.arg(...)` needed an explicit alias
	// to satisfy sqlc's SQLite parser -- see docs/schema.md's sqlc risk note.
	WouldCreateCycle(ctx context.Context, arg WouldCreateCycleParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
