// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote_sync_state.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getRemoteSyncState = `-- name: GetRemoteSyncState :one
SELECT node_id, remote, sync_status, remote_asset_id, last_error, last_attempt_at, created_at, updated_at, retry_count
FROM remote_sync_state
WHERE node_id = ?1 AND remote = ?2
`

type GetRemoteSyncStateParams struct {
	NodeID int64
	Remote string
}

// The idempotency look-before-write read for Enqueue: does (node_id, remote)
// already exist, and in what state?
func (q *Queries) GetRemoteSyncState(ctx context.Context, arg GetRemoteSyncStateParams) (RemoteSyncState, error) {
	row := q.db.QueryRowContext(ctx, getRemoteSyncState, arg.NodeID, arg.Remote)
	var i RemoteSyncState
	err := row.Scan(
		&i.NodeID,
		&i.Remote,
		&i.SyncStatus,
		&i.RemoteAssetID,
		&i.LastError,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
	)
	return i, err
}

const listLiveNodesForSync = `-- name: ListLiveNodesForSync :many
SELECT n.id, n.file_path, n.file_name, n.file_ext, n.fast_hash, n.full_hash
FROM media_nodes n
LEFT JOIN remote_sync_state rs
       ON rs.node_id = n.id AND rs.remote = ?1
WHERE n.lifecycle_state != 'ARCHIVED'
  AND (n.file_path = ?2 OR n.file_path LIKE ?2 || '/%')
  AND rs.node_id IS NULL
ORDER BY n.id ASC
LIMIT ?3
`

type ListLiveNodesForSyncParams struct {
	Remote   string
	FilePath string
	Limit    int64
}

type ListLiveNodesForSyncRow struct {
	ID       int64
	FilePath string
	FileName string
	FileExt  string
	FastHash *string
	FullHash *string
}

// #55: the sync worker's enqueue source -- live nodes under a path prefix
// (the Immich export mount) that have NO remote_sync_state row for the given
// remote yet. Once pushed, a row exists and the node drops out of this set.
func (q *Queries) ListLiveNodesForSync(ctx context.Context, arg ListLiveNodesForSyncParams) ([]ListLiveNodesForSyncRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiveNodesForSync, arg.Remote, arg.FilePath, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveNodesForSyncRow{}
	for rows.Next() {
		var i ListLiveNodesForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.FileName,
			&i.FileExt,
			&i.FastHash,
			&i.FullHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemoteSyncStateByNode = `-- name: ListRemoteSyncStateByNode :many
SELECT node_id, remote, sync_status, remote_asset_id, last_error, last_attempt_at, created_at, updated_at, retry_count
FROM remote_sync_state
WHERE node_id = ?1
ORDER BY remote ASC
`

// Backs GET /api/v1/assets/{id}/sync-status: every remote_sync_state row for
// a node (both remotes), ordered by remote for a stable DTO.
func (q *Queries) ListRemoteSyncStateByNode(ctx context.Context, nodeID int64) ([]RemoteSyncState, error) {
	rows, err := q.db.QueryContext(ctx, listRemoteSyncStateByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemoteSyncState{}
	for rows.Next() {
		var i RemoteSyncState
		if err := rows.Scan(
			&i.NodeID,
			&i.Remote,
			&i.SyncStatus,
			&i.RemoteAssetID,
			&i.LastError,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemoteSyncStateByStatus = `-- name: ListRemoteSyncStateByStatus :many
SELECT node_id, remote, sync_status, remote_asset_id, last_error, last_attempt_at, created_at, updated_at, retry_count
FROM remote_sync_state
WHERE remote = ?1 AND sync_status = ?2
ORDER BY last_attempt_at ASC, node_id ASC
LIMIT ?3
`

type ListRemoteSyncStateByStatusParams struct {
	Remote     string
	SyncStatus string
	Limit      int64
}

// The sync worker's claim query: oldest-attempt-first so a backlog drains in
// order, capped at one batch. Scoped to a single remote -- a node can hold
// both IMMICH and GOOGLE_PHOTOS rows under the (node_id, remote) PK, so
// ProcessPending(remote) must never list (or re-flip) another remote's rows.
func (q *Queries) ListRemoteSyncStateByStatus(ctx context.Context, arg ListRemoteSyncStateByStatusParams) ([]RemoteSyncState, error) {
	rows, err := q.db.QueryContext(ctx, listRemoteSyncStateByStatus, arg.Remote, arg.SyncStatus, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemoteSyncState{}
	for rows.Next() {
		var i RemoteSyncState
		if err := rows.Scan(
			&i.NodeID,
			&i.Remote,
			&i.SyncStatus,
			&i.RemoteAssetID,
			&i.LastError,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manualRetryRemoteSyncState = `-- name: ManualRetryRemoteSyncState :exec
UPDATE remote_sync_state
SET sync_status = 'PENDING_CLOUD_PUSH', last_error = NULL, retry_count = 0,
    updated_at = unixepoch()
WHERE node_id = ?1 AND remote = ?2
`

type ManualRetryRemoteSyncStateParams struct {
	NodeID int64
	Remote string
}

// Backs POST /api/v1/assets/{id}/sync/retry (handleSyncRetry, #156): an
// explicit operator "try again" action on a PUSH_FAILED row, bypassing
// ResetRemoteSyncStateFailed's retry_count bound by design (see that
// query's comment). retry_count resets to 0 here -- the same rule
// MarkRemoteSyncStatePushed applies on a real success -- so the operator's
// action restores a full automatic-retry budget, not just one attempt
// before immediately re-hitting the bound on the very next failure (#182).
//
// last_attempt_at is deliberately left untouched, matching
// ResetRemoteSyncStateFailed (the automatic recovery path for the same
// PUSH_FAILED -> PENDING_CLOUD_PUSH transition), not UpsertRemoteSyncState.
// ListRemoteSyncStateByStatus claims oldest-last_attempt_at-first, so
// bumping it here would send a row an operator just explicitly asked to
// retry to the BACK of the claim queue -- behind every row the automatic
// recovery already reset. Leaving it alone keeps the row's original
// position, so it claims promptly instead of behind a potentially large
// backlog.
func (q *Queries) ManualRetryRemoteSyncState(ctx context.Context, arg ManualRetryRemoteSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, manualRetryRemoteSyncState, arg.NodeID, arg.Remote)
	return err
}

const markRemoteSyncStateFailed = `-- name: MarkRemoteSyncStateFailed :exec
UPDATE remote_sync_state
SET sync_status = 'PUSH_FAILED', last_error = ?3, retry_count = retry_count + 1,
    last_attempt_at = unixepoch(), updated_at = unixepoch()
WHERE node_id = ?1 AND remote = ?2
`

type MarkRemoteSyncStateFailedParams struct {
	NodeID    int64
	Remote    string
	LastError sql.NullString
}

// Terminal failure: records the error, the attempt time, and increments
// retry_count -- what ResetRemoteSyncStateFailed's bound is measured against.
func (q *Queries) MarkRemoteSyncStateFailed(ctx context.Context, arg MarkRemoteSyncStateFailedParams) error {
	_, err := q.db.ExecContext(ctx, markRemoteSyncStateFailed, arg.NodeID, arg.Remote, arg.LastError)
	return err
}

const markRemoteSyncStatePushed = `-- name: MarkRemoteSyncStatePushed :exec
UPDATE remote_sync_state
SET sync_status = 'PUSHED', remote_asset_id = COALESCE(?3, remote_asset_id), last_error = NULL,
    retry_count = 0, last_attempt_at = unixepoch(), updated_at = unixepoch()
WHERE node_id = ?1 AND remote = ?2
`

type MarkRemoteSyncStatePushedParams struct {
	NodeID        int64
	Remote        string
	RemoteAssetID sql.NullString
}

// Terminal success: records the remote asset id (empty for a scan-trigger
// push) and clears any prior error. retry_count resets to 0 -- it tracks
// consecutive failures since the last success, not a lifetime total.
// updated_at set explicitly -- no trigger.
//
// remote_asset_id uses COALESCE(excluded, existing), matching
// UpsertRemoteSyncState's pattern, not a bare overwrite: today's only
// PushFunc (Immich's whole-library TriggerScan) never populates it, so ?3 is
// always empty and this is currently unreachable in practice. It's still
// fixed for symmetry -- a bare overwrite would silently NULL a previously
// recorded id on any future call site that (unlike today's) sometimes pushes
// without a fresh remote_asset_id in hand.
func (q *Queries) MarkRemoteSyncStatePushed(ctx context.Context, arg MarkRemoteSyncStatePushedParams) error {
	_, err := q.db.ExecContext(ctx, markRemoteSyncStatePushed, arg.NodeID, arg.Remote, arg.RemoteAssetID)
	return err
}

const resetRemoteSyncStateFailed = `-- name: ResetRemoteSyncStateFailed :execrows
UPDATE remote_sync_state
SET sync_status = 'PENDING_CLOUD_PUSH', updated_at = unixepoch()
WHERE sync_status = 'PUSH_FAILED' AND remote = ?1 AND last_attempt_at < ?2 AND retry_count < ?3
`

type ResetRemoteSyncStateFailedParams struct {
	Remote        string
	LastAttemptAt sql.NullInt64
	RetryCount    int64
}

// #55/#182: worker-level retry. PUSH_FAILED rows whose last attempt is older
// than the retry window AND whose retry_count hasn't yet reached the bound
// are reset to PENDING_CLOUD_PUSH so the next worker pass re-attempts them --
// a transient remote failure must not strand a batch forever. Once
// retry_count reaches the bound, a row is left PUSH_FAILED permanently: a
// misconfigured remote (e.g. an empty libraryId, see #182) must not retry
// every 5 minutes forever. A human can still force a re-attempt via
// POST /api/v1/assets/{id}/sync/retry (handleSyncRetry), which bypasses this
// bound by design -- an explicit operator action, not an automatic loop.
// Scoped to a single remote. last_attempt_at is set explicitly on every
// attempt, so this only re-claims rows that have not been retried recently
// (bounded retry frequency, not a hot loop).
func (q *Queries) ResetRemoteSyncStateFailed(ctx context.Context, arg ResetRemoteSyncStateFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetRemoteSyncStateFailed, arg.Remote, arg.LastAttemptAt, arg.RetryCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetRemoteSyncStateStale = `-- name: ResetRemoteSyncStateStale :execrows
UPDATE remote_sync_state
SET sync_status = 'PENDING_CLOUD_PUSH', updated_at = unixepoch()
WHERE sync_status = 'PUSHING' AND remote = ?1 AND last_attempt_at < ?2
`

type ResetRemoteSyncStateStaleParams struct {
	Remote        string
	LastAttemptAt sql.NullInt64
}

// Crash recovery: rows left PUSHING by a process that died mid-push are reset
// to PENDING_CLOUD_PUSH so the next worker pass re-claims them. Scoped to a
// single remote so an IMMICH recovery can never touch GOOGLE_PHOTOS rows.
func (q *Queries) ResetRemoteSyncStateStale(ctx context.Context, arg ResetRemoteSyncStateStaleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetRemoteSyncStateStale, arg.Remote, arg.LastAttemptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertRemoteSyncState = `-- name: UpsertRemoteSyncState :one
INSERT INTO remote_sync_state (node_id, remote, sync_status, remote_asset_id, last_error, last_attempt_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, unixepoch())
ON CONFLICT (node_id, remote) DO UPDATE SET
    sync_status     = excluded.sync_status,
    remote_asset_id = COALESCE(excluded.remote_asset_id, remote_sync_state.remote_asset_id),
    last_error      = excluded.last_error,
    last_attempt_at = excluded.last_attempt_at,
    updated_at      = unixepoch()
RETURNING node_id, remote, sync_status, remote_asset_id, last_error, last_attempt_at, created_at, updated_at, retry_count
`

type UpsertRemoteSyncStateParams struct {
	NodeID        int64
	Remote        string
	SyncStatus    string
	RemoteAssetID sql.NullString
	LastError     sql.NullString
	LastAttemptAt sql.NullInt64
}

// Claims a node for push (or re-claims it): sets the target sync_status and
// bumps last_attempt_at/updated_at. On a re-claim of an existing PUSH_FAILED
// row, last_error is cleared and the existing remote_asset_id (if any) is
// kept. Every transition sets updated_at explicitly -- no triggers, per this
// repo's invariant. This is the ONLY way a (node_id, remote) row is created.
func (q *Queries) UpsertRemoteSyncState(ctx context.Context, arg UpsertRemoteSyncStateParams) (RemoteSyncState, error) {
	row := q.db.QueryRowContext(ctx, upsertRemoteSyncState,
		arg.NodeID,
		arg.Remote,
		arg.SyncStatus,
		arg.RemoteAssetID,
		arg.LastError,
		arg.LastAttemptAt,
	)
	var i RemoteSyncState
	err := row.Scan(
		&i.NodeID,
		&i.Remote,
		&i.SyncStatus,
		&i.RemoteAssetID,
		&i.LastError,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
	)
	return i, err
}
