// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolve_snapshot.sql

package sqlcgen

import (
	"context"
)

const agentCreatedVirtualNode = `-- name: AgentCreatedVirtualNode :one
SELECT EXISTS(
    SELECT 1 FROM event_queue
    WHERE agent_id = ?1 AND event_type = 'EVENT_VIRTUAL_NODE_CREATED'
      AND status = 'PROCESSED'
      AND json_extract(payload_json, '$.nodeUuid') = ?2
) AS created_by_agent
`

type AgentCreatedVirtualNodeParams struct {
	AgentID  string
	NodeUuid string
}

func (q *Queries) AgentCreatedVirtualNode(ctx context.Context, arg AgentCreatedVirtualNodeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, agentCreatedVirtualNode, arg.AgentID, arg.NodeUuid)
	var created_by_agent bool
	err := row.Scan(&created_by_agent)
	return created_by_agent, err
}

const inactivateResolveEdge = `-- name: InactivateResolveEdge :exec
UPDATE media_edges
SET is_active = 0, updated_at = unixepoch()
WHERE id = ?1 AND resolver = 'resolve_project_db'
  AND review_state NOT IN ('CONFIRMED', 'REJECTED')
`

func (q *Queries) InactivateResolveEdge(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, inactivateResolveEdge, id)
	return err
}

const listResolveEdgesForTimeline = `-- name: ListResolveEdgesForTimeline :many
SELECT id, source_node_id, target_node_id, resolver, evidence_json,
       review_state, is_active
FROM media_edges
WHERE target_node_id = ?1 AND relationship_type = 'PROJECT_SIDECAR'
`

type ListResolveEdgesForTimelineRow struct {
	ID           int64
	SourceNodeID int64
	TargetNodeID int64
	Resolver     string
	EvidenceJson string
	ReviewState  string
	IsActive     int64
}

func (q *Queries) ListResolveEdgesForTimeline(ctx context.Context, targetNodeID int64) ([]ListResolveEdgesForTimelineRow, error) {
	rows, err := q.db.QueryContext(ctx, listResolveEdgesForTimeline, targetNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResolveEdgesForTimelineRow{}
	for rows.Next() {
		var i ListResolveEdgesForTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.Resolver,
			&i.EvidenceJson,
			&i.ReviewState,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolveTimelineScopes = `-- name: ListResolveTimelineScopes :many
SELECT timeline_node_id FROM resolve_timeline_scopes
WHERE agent_id = ?1 AND scope_id = ?2
`

type ListResolveTimelineScopesParams struct {
	AgentID string
	ScopeID string
}

func (q *Queries) ListResolveTimelineScopes(ctx context.Context, arg ListResolveTimelineScopesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listResolveTimelineScopes, arg.AgentID, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var timeline_node_id int64
		if err := rows.Scan(&timeline_node_id); err != nil {
			return nil, err
		}
		items = append(items, timeline_node_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshResolveEdge = `-- name: RefreshResolveEdge :exec
UPDATE media_edges
SET evidence_json = ?2, is_active = 1, updated_at = unixepoch()
WHERE id = ?1 AND resolver = 'resolve_project_db'
  AND review_state NOT IN ('CONFIRMED', 'REJECTED')
`

type RefreshResolveEdgeParams struct {
	ID           int64
	EvidenceJson string
}

func (q *Queries) RefreshResolveEdge(ctx context.Context, arg RefreshResolveEdgeParams) error {
	_, err := q.db.ExecContext(ctx, refreshResolveEdge, arg.ID, arg.EvidenceJson)
	return err
}

const registerResolveTimelineScope = `-- name: RegisterResolveTimelineScope :exec
INSERT OR IGNORE INTO resolve_timeline_scopes (agent_id, scope_id, timeline_node_id)
VALUES (?1, ?2, ?3)
`

type RegisterResolveTimelineScopeParams struct {
	AgentID        string
	ScopeID        string
	TimelineNodeID int64
}

func (q *Queries) RegisterResolveTimelineScope(ctx context.Context, arg RegisterResolveTimelineScopeParams) error {
	_, err := q.db.ExecContext(ctx, registerResolveTimelineScope, arg.AgentID, arg.ScopeID, arg.TimelineNodeID)
	return err
}

const resolveTimelineScopeOwner = `-- name: ResolveTimelineScopeOwner :one
SELECT EXISTS(
    SELECT 1 FROM resolve_timeline_scopes
    WHERE timeline_node_id = ?1 AND agent_id = ?2 AND scope_id = ?3
) AS scope_owner
`

type ResolveTimelineScopeOwnerParams struct {
	TimelineNodeID int64
	AgentID        string
	ScopeID        string
}

func (q *Queries) ResolveTimelineScopeOwner(ctx context.Context, arg ResolveTimelineScopeOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, resolveTimelineScopeOwner, arg.TimelineNodeID, arg.AgentID, arg.ScopeID)
	var scope_owner bool
	err := row.Scan(&scope_owner)
	return scope_owner, err
}

const updateResolveTimelineDisplayName = `-- name: UpdateResolveTimelineDisplayName :exec
UPDATE media_nodes SET file_name = ?2, updated_at = unixepoch()
WHERE id = ?1
`

type UpdateResolveTimelineDisplayNameParams struct {
	ID       int64
	FileName string
}

func (q *Queries) UpdateResolveTimelineDisplayName(ctx context.Context, arg UpdateResolveTimelineDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateResolveTimelineDisplayName, arg.ID, arg.FileName)
	return err
}
