// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const cancelScanJob = `-- name: CancelScanJob :exec
UPDATE scan_jobs SET state = 'CANCELLED', finished_at = unixepoch(), updated_at = unixepoch() WHERE id = ?1
`

// Phase 1 (#32): a WATCH job torn down by a clean shutdown ends CANCELLED,
// not FAILED -- only a watcher that died on its own is a failure.
func (q *Queries) CancelScanJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelScanJob, id)
	return err
}

const completeScanJob = `-- name: CompleteScanJob :exec
UPDATE scan_jobs SET state = 'COMPLETED', finished_at = unixepoch(), updated_at = unixepoch() WHERE id = ?1
`

func (q *Queries) CompleteScanJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeScanJob, id)
	return err
}

const completeScanJobWithWarning = `-- name: CompleteScanJobWithWarning :exec
UPDATE scan_jobs SET state = 'COMPLETED', last_error = ?2, finished_at = unixepoch(), updated_at = unixepoch() WHERE id = ?1
`

type CompleteScanJobWithWarningParams struct {
	ID        int64
	LastError sql.NullString
}

// #225: used when the MISSING sweep is skipped because the walk saw zero
// files. The scan itself still completed cleanly -- state stays COMPLETED,
// not FAILED, since a walk *error* is a distinct, already-handled failure
// mode (see FailScanJob) -- but last_error carries a human-readable note so
// an operator can tell "swept nothing because there was genuinely nothing to
// see" apart from "swept nothing because the walk aborted."
func (q *Queries) CompleteScanJobWithWarning(ctx context.Context, arg CompleteScanJobWithWarningParams) error {
	_, err := q.db.ExecContext(ctx, completeScanJobWithWarning, arg.ID, arg.LastError)
	return err
}

const countRunningScanJobs = `-- name: CountRunningScanJobs :one
SELECT COUNT(*) FROM scan_jobs WHERE state = 'RUNNING' AND kind != 'WATCH'
`

func (q *Queries) CountRunningScanJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunningScanJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunningScansForLocationByKind = `-- name: CountRunningScansForLocationByKind :one
SELECT COUNT(*) FROM scan_jobs
WHERE storage_location_id = ?1 AND kind = ?2 AND state = 'RUNNING'
`

type CountRunningScansForLocationByKindParams struct {
	StorageLocationID sql.NullInt64
	Kind              string
}

// #163/#226: called inside the same transaction as CreateScanJob (see
// pipeline.createScanJob) so the check-then-insert is one atomic unit, not
// just an accident of the writer pool being single-connection. Parameterized
// on kind (rather than hardcoded to 'FULL_SCAN') since #226 added a second
// HTTP-triggered path (POST /api/v1/scan {differential:true}) that creates
// an INCREMENTAL job directly, which needs the same same-kind guard a
// FULL_SCAN already got -- SweeperSupervisor's own INCREMENTAL passes are
// still serialized by its own ticker loop (sweeper.go), so this check is a
// no-op there, not a behavior change. WATCH jobs are excluded by the
// caller only ever passing FULL_SCAN or INCREMENTAL here -- they're already
// singleton-per-location via WatcherSupervisor.Start's sync.Once and are
// long-lived by design, so they must not block (or be blocked by) either.
func (q *Queries) CountRunningScansForLocationByKind(ctx context.Context, arg CountRunningScansForLocationByKindParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunningScansForLocationByKind, arg.StorageLocationID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScanJobsFiltered = `-- name: CountScanJobsFiltered :one
SELECT COUNT(*)
FROM scan_jobs
WHERE (?1 IS NULL OR kind = ?1)
  AND (?2 IS NULL OR state = ?2)
`

type CountScanJobsFilteredParams struct {
	Kind  interface{}
	State interface{}
}

func (q *Queries) CountScanJobsFiltered(ctx context.Context, arg CountScanJobsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanJobsFiltered, arg.Kind, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanJob = `-- name: CreateScanJob :one
INSERT INTO scan_jobs (storage_location_id, kind, state, started_at, updated_at)
VALUES (?1, ?2, 'RUNNING', unixepoch(), unixepoch())
RETURNING id, storage_location_id, kind, state, files_seen, files_hashed,
          files_failed, edges_created, started_at, finished_at, last_error, updated_at
`

type CreateScanJobParams struct {
	StorageLocationID sql.NullInt64
	Kind              string
}

func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error) {
	row := q.db.QueryRowContext(ctx, createScanJob, arg.StorageLocationID, arg.Kind)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.StorageLocationID,
		&i.Kind,
		&i.State,
		&i.FilesSeen,
		&i.FilesHashed,
		&i.FilesFailed,
		&i.EdgesCreated,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const failScanJob = `-- name: FailScanJob :exec
UPDATE scan_jobs SET state = 'FAILED', last_error = ?2, finished_at = unixepoch(), updated_at = unixepoch() WHERE id = ?1
`

type FailScanJobParams struct {
	ID        int64
	LastError sql.NullString
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) error {
	_, err := q.db.ExecContext(ctx, failScanJob, arg.ID, arg.LastError)
	return err
}

const getScanJob = `-- name: GetScanJob :one
SELECT id, storage_location_id, kind, state, files_seen, files_hashed,
       files_failed, edges_created, started_at, finished_at, last_error, updated_at
FROM scan_jobs
WHERE id = ?1
`

func (q *Queries) GetScanJob(ctx context.Context, id int64) (ScanJob, error) {
	row := q.db.QueryRowContext(ctx, getScanJob, id)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.StorageLocationID,
		&i.Kind,
		&i.State,
		&i.FilesSeen,
		&i.FilesHashed,
		&i.FilesFailed,
		&i.EdgesCreated,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentScanJobs = `-- name: ListRecentScanJobs :many
SELECT id, storage_location_id, kind, state, files_seen, files_hashed,
       files_failed, edges_created, started_at, finished_at, last_error, updated_at
FROM scan_jobs
ORDER BY started_at DESC
LIMIT ?1
`

func (q *Queries) ListRecentScanJobs(ctx context.Context, limit int64) ([]ScanJob, error) {
	rows, err := q.db.QueryContext(ctx, listRecentScanJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJob{}
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.StorageLocationID,
			&i.Kind,
			&i.State,
			&i.FilesSeen,
			&i.FilesHashed,
			&i.FilesFailed,
			&i.EdgesCreated,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsFiltered = `-- name: ListScanJobsFiltered :many
SELECT id, storage_location_id, kind, state, files_seen, files_hashed,
       files_failed, edges_created, started_at, finished_at, last_error, updated_at
FROM scan_jobs
WHERE (?3 IS NULL OR kind = ?3)
  AND (?4 IS NULL OR state = ?4)
ORDER BY started_at DESC
LIMIT ?1 OFFSET ?2
`

type ListScanJobsFilteredParams struct {
	Limit  int64
	Offset int64
	Kind   interface{}
	State  interface{}
}

func (q *Queries) ListScanJobsFiltered(ctx context.Context, arg ListScanJobsFilteredParams) ([]ScanJob, error) {
	rows, err := q.db.QueryContext(ctx, listScanJobsFiltered,
		arg.Limit,
		arg.Offset,
		arg.Kind,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJob{}
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.StorageLocationID,
			&i.Kind,
			&i.State,
			&i.FilesSeen,
			&i.FilesHashed,
			&i.FilesFailed,
			&i.EdgesCreated,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileOrphanedScanJobs = `-- name: ReconcileOrphanedScanJobs :execrows
UPDATE scan_jobs
SET state = 'FAILED', last_error = ?1, finished_at = unixepoch(), updated_at = unixepoch()
WHERE state = 'RUNNING'
`

// Every row still 'RUNNING' at process startup, before this process has
// created any scan_jobs row of its own, was left behind by a previous
// process that never reached a terminal state -- SIGKILL, OOM-kill,
// container hard-stop, power loss. A WATCH row is RUNNING for its entire
// process lifetime by design, so this is the only place its state ever
// gets cleaned up after a crash. Reuses FAILED rather than adding a new
// enum state (see issue #88's scope note): last_error distinguishes this
// from a genuine processing failure. Must run before
// WatcherSupervisor.Start creates any fresh WATCH row for the same
// location, or a reconciled row and a fresh row could momentarily both
// claim to represent "the" watch state for it. ix_scan_jobs_active
// (state, started_at DESC) backs this WHERE clause.
func (q *Queries) ReconcileOrphanedScanJobs(ctx context.Context, lastError sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, reconcileOrphanedScanJobs, lastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateScanJobProgress = `-- name: UpdateScanJobProgress :exec
UPDATE scan_jobs
SET files_seen = ?2, files_hashed = ?3, files_failed = ?4, edges_created = ?5, updated_at = unixepoch()
WHERE id = ?1
`

type UpdateScanJobProgressParams struct {
	ID           int64
	FilesSeen    int64
	FilesHashed  int64
	FilesFailed  int64
	EdgesCreated int64
}

func (q *Queries) UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateScanJobProgress,
		arg.ID,
		arg.FilesSeen,
		arg.FilesHashed,
		arg.FilesFailed,
		arg.EdgesCreated,
	)
	return err
}
