// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const cancelScanJob = `-- name: CancelScanJob :exec
UPDATE scan_jobs SET state = 'CANCELLED', finished_at = unixepoch(), updated_at = unixepoch() WHERE id = ?1
`

// Phase 1 (#32): a WATCH job torn down by a clean shutdown ends CANCELLED,
// not FAILED -- only a watcher that died on its own is a failure.
func (q *Queries) CancelScanJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelScanJob, id)
	return err
}

const completeScanJob = `-- name: CompleteScanJob :exec
UPDATE scan_jobs SET state = 'COMPLETED', finished_at = unixepoch(), updated_at = unixepoch() WHERE id = ?1
`

func (q *Queries) CompleteScanJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeScanJob, id)
	return err
}

const createScanJob = `-- name: CreateScanJob :one
INSERT INTO scan_jobs (storage_location_id, kind, state, started_at, updated_at)
VALUES (?1, ?2, 'RUNNING', unixepoch(), unixepoch())
RETURNING id, storage_location_id, kind, state, files_seen, files_hashed,
          files_failed, edges_created, started_at, finished_at, last_error, updated_at
`

type CreateScanJobParams struct {
	StorageLocationID sql.NullInt64
	Kind              string
}

func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error) {
	row := q.db.QueryRowContext(ctx, createScanJob, arg.StorageLocationID, arg.Kind)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.StorageLocationID,
		&i.Kind,
		&i.State,
		&i.FilesSeen,
		&i.FilesHashed,
		&i.FilesFailed,
		&i.EdgesCreated,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const failScanJob = `-- name: FailScanJob :exec
UPDATE scan_jobs SET state = 'FAILED', last_error = ?2, finished_at = unixepoch(), updated_at = unixepoch() WHERE id = ?1
`

type FailScanJobParams struct {
	ID        int64
	LastError sql.NullString
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) error {
	_, err := q.db.ExecContext(ctx, failScanJob, arg.ID, arg.LastError)
	return err
}

const getScanJob = `-- name: GetScanJob :one
SELECT id, storage_location_id, kind, state, files_seen, files_hashed,
       files_failed, edges_created, started_at, finished_at, last_error, updated_at
FROM scan_jobs
WHERE id = ?1
`

func (q *Queries) GetScanJob(ctx context.Context, id int64) (ScanJob, error) {
	row := q.db.QueryRowContext(ctx, getScanJob, id)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.StorageLocationID,
		&i.Kind,
		&i.State,
		&i.FilesSeen,
		&i.FilesHashed,
		&i.FilesFailed,
		&i.EdgesCreated,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentScanJobs = `-- name: ListRecentScanJobs :many
SELECT id, storage_location_id, kind, state, files_seen, files_hashed,
       files_failed, edges_created, started_at, finished_at, last_error, updated_at
FROM scan_jobs
ORDER BY started_at DESC
LIMIT ?1
`

func (q *Queries) ListRecentScanJobs(ctx context.Context, limit int64) ([]ScanJob, error) {
	rows, err := q.db.QueryContext(ctx, listRecentScanJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJob{}
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.StorageLocationID,
			&i.Kind,
			&i.State,
			&i.FilesSeen,
			&i.FilesHashed,
			&i.FilesFailed,
			&i.EdgesCreated,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanJobProgress = `-- name: UpdateScanJobProgress :exec
UPDATE scan_jobs
SET files_seen = ?2, files_hashed = ?3, files_failed = ?4, edges_created = ?5, updated_at = unixepoch()
WHERE id = ?1
`

type UpdateScanJobProgressParams struct {
	ID           int64
	FilesSeen    int64
	FilesHashed  int64
	FilesFailed  int64
	EdgesCreated int64
}

func (q *Queries) UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateScanJobProgress,
		arg.ID,
		arg.FilesSeen,
		arg.FilesHashed,
		arg.FilesFailed,
		arg.EdgesCreated,
	)
	return err
}
