// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_locations.sql

package sqlcgen

import (
	"context"
)

const getStorageLocationByPath = `-- name: GetStorageLocationByPath :one
SELECT id, name, root_path, tier, read_only, prunable, is_active, created_at, updated_at
FROM storage_locations
WHERE root_path = ?1
`

// Used by storage.Guard (PR 2) to resolve a canonicalized path to its tier --
// the single source of truth for tier is this table, never a hardcoded
// prefix. See docs/schema.md fix #1.
func (q *Queries) GetStorageLocationByPath(ctx context.Context, rootPath string) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, getStorageLocationByPath, rootPath)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Tier,
		&i.ReadOnly,
		&i.Prunable,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageLocations = `-- name: ListStorageLocations :many
SELECT id, name, root_path, tier, read_only, prunable, is_active, created_at, updated_at
FROM storage_locations
ORDER BY id
`

func (q *Queries) ListStorageLocations(ctx context.Context) ([]StorageLocation, error) {
	rows, err := q.db.QueryContext(ctx, listStorageLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RootPath,
			&i.Tier,
			&i.ReadOnly,
			&i.Prunable,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
