// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countAttributionUsers = `-- name: CountAttributionUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountAttributionUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttributionUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttributionUser = `-- name: CreateAttributionUser :one
INSERT INTO users (auth_provider, external_uid, username, email, source, password_hash, last_seen_at, created_at, created_by)
VALUES (?1, ?2, ?3, ?4, 'forward-link', NULL, unixepoch(), unixepoch(), 'attribution-bootstrap')
ON CONFLICT (auth_provider, external_uid) DO UPDATE SET external_uid = excluded.external_uid
RETURNING id
`

type CreateAttributionUserParams struct {
	AuthProvider string
	ExternalUid  string
	Username     string
	Email        sql.NullString
}

// Lazy-provisioning insert. The caller resolves auth_provider +
// external_uid from the Principal; username/email are denormalized
// display fields refreshed on every ResolveOrCreate. source='forward-link'
// with NULL password_hash matches PR #407's existing CHECK constraint --
// these rows are attribution-only, not local-auth credentials.
// Returns the row id on both insert and on conflict (no-op) so the
// caller never has to distinguish "created" from "already existed" --
// matching the ResolveOrCreate contract: get-or-create with stable id.
// SQLite's RETURNING on ON CONFLICT DO NOTHING returns nothing for the
// no-op case; the workaround is DO UPDATE SET on the conflict target
// column with a no-op value so the row is "updated" (still returned) but
// nothing actually changes.
func (q *Queries) CreateAttributionUser(ctx context.Context, arg CreateAttributionUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAttributionUser,
		arg.AuthProvider,
		arg.ExternalUid,
		arg.Username,
		arg.Email,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const demoteUserFromAdmin = `-- name: DemoteUserFromAdmin :exec
UPDATE users SET is_admin = 0 WHERE id = ?1
`

// Set users.is_admin = 0 for the supplied user id. The mirror of
// PromoteUserToAdmin, used by user-management flows (an admin-UI
// demote action is planned in the issue #453 follow-ups) and, today,
// by the PAT live-authority tests that exercise a demoted owner's
// token failing closed. Idempotent -- demoting a non-admin row is a
// no-op.
func (q *Queries) DemoteUserFromAdmin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, demoteUserFromAdmin, id)
	return err
}

const ensureBootstrapUser = `-- name: EnsureBootstrapUser :one
INSERT INTO users (auth_provider, external_uid, username, email, source, password_hash, last_seen_at, created_at, created_by)
VALUES ('system', 'ansible-bootstrap', 'ansible-bootstrap', NULL, 'forward-link', NULL, unixepoch(), unixepoch(), 'admin-bootstrap')
ON CONFLICT (auth_provider, external_uid) DO UPDATE SET external_uid = excluded.external_uid
RETURNING id
`

// Lazy-provisions the service-account user the bootstrap PAT belongs
// to (issue #453 PR E). auth_provider='system' / external_uid=
// 'ansible-bootstrap' can't collide with a real Authentik uid (those
// are UUIDs) or with the system sentinel (whose external_uid is just
// 'system'). The user is created with is_admin=1 by the caller --
// this query only handles the existence half; the admin bit lives on
// a separate UPDATE because is_admin isn't part of the INSERT
// columns above (admin is set by the local-auth migration, and the
// existing forward-link rows use NULL password_hash which the local-
// auth schema accepts).
//
// email is NULL, NOT ”: 00018's partial unique index
// users_email_source_uniq ON (email, source) WHERE email IS NOT NULL
// treats ” as a value, and EnsureSystemUser already owns the
// (”, 'forward-link') pair -- a second forward-link row with ” would
// fail the boot with UNIQUE constraint violated (round-3 review).
// NULL is excluded from the index predicate, so any number of
// forward-link service rows can carry it.
func (q *Queries) EnsureBootstrapUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ensureBootstrapUser)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ensureSystemUser = `-- name: EnsureSystemUser :one
INSERT INTO users (auth_provider, external_uid, username, email, source, password_hash, last_seen_at, created_at, created_by)
VALUES ('system', 'system', 'system', '', 'forward-link', NULL, unixepoch(), unixepoch(), 'attribution-bootstrap')
ON CONFLICT (auth_provider, external_uid) DO UPDATE SET external_uid = excluded.external_uid
RETURNING id
`

// Lazy-provisions the "system" attribution sentinel: background workers
// (SweeperSupervisor's INCREMENTAL passes, prune, anything that has no
// request Principal) attribute their writes to this user. Idempotent:
// re-running returns the same row. source='forward-link' with NULL
// password_hash matches PR #407's existing CHECK; auth_provider='system'
// / external_uid='system' can't collide with a real Authentik uid (those
// are UUIDs). This is the canonical "no human behind this" attribution in
// actor_audit and scan_jobs.started_by_user_id. The DO UPDATE SET trick
// (see CreateAttributionUser) keeps RETURNING returning a row on conflict.
func (q *Queries) EnsureSystemUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ensureSystemUser)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAttributionUserByExternalUID = `-- name: GetAttributionUserByExternalUID :one

SELECT id, auth_provider, external_uid, username, email, created_at, last_seen_at
FROM users
WHERE auth_provider = ?1 AND external_uid = ?2
`

type GetAttributionUserByExternalUIDParams struct {
	AuthProvider string
	ExternalUid  string
}

type GetAttributionUserByExternalUIDRow struct {
	ID           int64
	AuthProvider string
	ExternalUid  string
	Username     string
	Email        sql.NullString
	CreatedAt    int64
	LastSeenAt   int64
}

// users: one row per human principal that has ever authenticated via
// Authentik ForwardAuth. Lazily provisioned on first sight by
// internal/users.Service.ResolveOrCreate, keyed on the stable
// (auth_provider, external_uid) so Authentik username renames don't
// fragment attribution.
//
// All positional params use bare ?1/?2 (not sqlc.arg) per AGENTS.md's
// "SQL Syntax Traps" note.
func (q *Queries) GetAttributionUserByExternalUID(ctx context.Context, arg GetAttributionUserByExternalUIDParams) (GetAttributionUserByExternalUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAttributionUserByExternalUID, arg.AuthProvider, arg.ExternalUid)
	var i GetAttributionUserByExternalUIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.ExternalUid,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getAttributionUserByID = `-- name: GetAttributionUserByID :one
SELECT id, auth_provider, external_uid, username, email, created_at, last_seen_at
FROM users
WHERE id = ?1
`

type GetAttributionUserByIDRow struct {
	ID           int64
	AuthProvider string
	ExternalUid  string
	Username     string
	Email        sql.NullString
	CreatedAt    int64
	LastSeenAt   int64
}

func (q *Queries) GetAttributionUserByID(ctx context.Context, id int64) (GetAttributionUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAttributionUserByID, id)
	var i GetAttributionUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.ExternalUid,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSystemUserID = `-- name: GetSystemUserID :one
SELECT id
FROM users
WHERE auth_provider = 'system' AND external_uid = 'system'
`

// The EnsureSystemUser companion query: lookup the system user by its
// stable sentinel (external_uid='system'), so the boot sequence can
// capture its id before any background worker starts. Same shape as
// GetAttributionUserByExternalUID -- named distinctly so the boot path
// reads self-documentingly and a future "system user has been renamed"
// rename has one obvious place to land.
func (q *Queries) GetSystemUserID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSystemUserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserAdminStatus = `-- name: GetUserAdminStatus :one
SELECT is_admin, disabled_at FROM users WHERE id = ?1
`

type GetUserAdminStatusRow struct {
	IsAdmin    int64
	DisabledAt sql.NullInt64
}

// Live authority check for PAT minting (issue #453 PR E): the PAT
// lookup query requires the OWNER to be is_admin=1 with disabled_at
// NULL, so minting for anyone else would hand back a well-formed
// token that can never authenticate. Mint runs this check in the
// same transaction as the insert; both columns are returned so the
// caller decides (is_admin is 0/1 per 00018's CHECK; disabled_at
// NULL means the account can authenticate).
func (q *Queries) GetUserAdminStatus(ctx context.Context, id int64) (GetUserAdminStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAdminStatus, id)
	var i GetUserAdminStatusRow
	err := row.Scan(&i.IsAdmin, &i.DisabledAt)
	return i, err
}

const listAttributionUsers = `-- name: ListAttributionUsers :many
SELECT id, auth_provider, external_uid, username, email, created_at, last_seen_at
FROM users
ORDER BY username ASC, id ASC
LIMIT ?1 OFFSET ?2
`

type ListAttributionUsersParams struct {
	Limit  int64
	Offset int64
}

type ListAttributionUsersRow struct {
	ID           int64
	AuthProvider string
	ExternalUid  string
	Username     string
	Email        sql.NullString
	CreatedAt    int64
	LastSeenAt   int64
}

// Backs GET /api/v1/users (admin-only). Used by the pairing UI's
// "Owned by" selector (when it lands -- today defaults to the creating
// admin, see internal/pairing's CreatePairing). Capped at 200 rows in
// the handler; this query is unbounded by design (an admin-only endpoint,
// no pagination UI yet).
func (q *Queries) ListAttributionUsers(ctx context.Context, arg ListAttributionUsersParams) ([]ListAttributionUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttributionUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttributionUsersRow{}
	for rows.Next() {
		var i ListAttributionUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthProvider,
			&i.ExternalUid,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteBootstrapUserToAdmin = `-- name: PromoteBootstrapUserToAdmin :exec
UPDATE users SET is_admin = 1, disabled_at = NULL WHERE id = ?1
`

// Bootstrap-specific variant of PromoteUserToAdmin: sets is_admin = 1
// AND clears disabled_at for the ansible-bootstrap service account.
// Reactivation is correct HERE and only here: the operator re-running
// the bootstrap sequence intends the minted PAT to work, and the PAT
// lookup query (GetUserPATByHash) requires disabled_at IS NULL --
// promoting without reactivating would mint a wildcard token that
// 401s on every request while the boot logs success (round-3 review).
// Named distinctly so a future admin-UI promote action can't pick it
// up and inherit the reactivation side effect. Idempotent.
func (q *Queries) PromoteBootstrapUserToAdmin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, promoteBootstrapUserToAdmin, id)
	return err
}

const promoteUserToAdmin = `-- name: PromoteUserToAdmin :exec
UPDATE users SET is_admin = 1 WHERE id = ?1
`

// Set users.is_admin = 1 for the supplied user id. Does NOT touch
// disabled_at: a promote action must never silently re-enable a
// disabled account (round-5 review) -- reactivation is a separate,
// explicit decision (see PromoteBootstrapUserToAdmin for the one
// caller whose semantics include it). Idempotent.
func (q *Queries) PromoteUserToAdmin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, promoteUserToAdmin, id)
	return err
}

const reconcileLocalExternalUID = `-- name: ReconcileLocalExternalUID :exec
UPDATE users
SET external_uid = ?2,
    auth_provider = 'local'
WHERE id = ?1
`

type ReconcileLocalExternalUIDParams struct {
	ID          int64
	ExternalUid string
}

// Realigns external_uid AND auth_provider on an existing user row.
// Used by the local reconciliation path in
// internal/users.Service.resolveLocal when a username-based lookup
// finds a source='local' row whose stored external_uid no longer
// matches the current username -- typically because an admin renamed
// the local user without an accompany-side sync to external_uid, or
// because migration 00028 Down rewrote auth_provider to
// 'forward-link' and external_uid to the raw username. The
// session/middleware sets ExternalUID=username for local principals,
// so a renamed or Down-affected user lands here on their next
// request and attribution silently NULLs until this UPDATE runs.
// Caller (resolveLocal) verifies source='local' and the pre-update
// external_uid mismatch before invoking, so this query is a
// targeted single-row UPDATE with no further filtering.
func (q *Queries) ReconcileLocalExternalUID(ctx context.Context, arg ReconcileLocalExternalUIDParams) error {
	_, err := q.db.ExecContext(ctx, reconcileLocalExternalUID, arg.ID, arg.ExternalUid)
	return err
}

const refreshAttributionUserSeen = `-- name: RefreshAttributionUserSeen :exec
UPDATE users
SET username = ?2, email = ?3, last_seen_at = unixepoch()
WHERE id = ?1
`

type RefreshAttributionUserSeenParams struct {
	ID       int64
	Username string
	Email    sql.NullString
}

// Updates the denormalized username/email (a user may have renamed since
// their last request) and bumps last_seen_at. Called by
// ResolveOrCreate after a cache miss, in the same transaction as the
// create-or-no-op insert above. No-op on a missing row (the create
// branch above will have just inserted one in the same tx).
func (q *Queries) RefreshAttributionUserSeen(ctx context.Context, arg RefreshAttributionUserSeenParams) error {
	_, err := q.db.ExecContext(ctx, refreshAttributionUserSeen, arg.ID, arg.Username, arg.Email)
	return err
}
