// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_pats.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countUserPATs = `-- name: CountUserPATs :one
SELECT COUNT(*) FROM user_pats WHERE user_id = ?1
`

func (q *Queries) CountUserPATs(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserPATs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserPAT = `-- name: CreateUserPAT :one

INSERT INTO user_pats (user_id, name, hashed_key, scopes_json, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, unixepoch(), ?5)
RETURNING id, user_id, name, hashed_key, scopes_json, created_at, last_used_at, expires_at, revoked_at
`

type CreateUserPATParams struct {
	UserID     int64
	Name       string
	HashedKey  string
	ScopesJson string
	ExpiresAt  sql.NullInt64
}

// user_pats: per-user admin PATs for unattended operations. See
// 00033_user_pats.sql's header comment for the rationale and storage
// shape. All queries here are admin-gated -- RequirePAT middleware
// sits on the route and rejects without a valid+scoped token before
// the handler runs.
//
// All positional params use bare ?1/?2 (not sqlc.arg) per AGENTS.md's
// "SQL Syntax Traps" note.
// Mints a new PAT. hashed_key is HMAC-SHA256(pepper, plaintext);
// the caller has the plaintext to return to the operator exactly
// once and never persists. scopes_json is JSON-encoded by the Go
// layer; SQLite's json_valid CHECK on the column protects against
// malformed storage. expires_at is nullable for non-expiring tokens.
func (q *Queries) CreateUserPAT(ctx context.Context, arg CreateUserPATParams) (UserPat, error) {
	row := q.db.QueryRowContext(ctx, createUserPAT,
		arg.UserID,
		arg.Name,
		arg.HashedKey,
		arg.ScopesJson,
		arg.ExpiresAt,
	)
	var i UserPat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.HashedKey,
		&i.ScopesJson,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserPATByHash = `-- name: GetUserPATByHash :one
SELECT up.id AS id, up.user_id AS user_id, up.name AS name, up.hashed_key AS hashed_key,
       up.scopes_json AS scopes_json, up.created_at AS created_at, up.last_used_at AS last_used_at,
       up.expires_at AS expires_at, up.revoked_at AS revoked_at
FROM user_pats AS up
JOIN users AS u ON u.id = up.user_id
WHERE up.hashed_key = ?1 AND up.revoked_at IS NULL
  AND u.is_admin = 1 AND u.disabled_at IS NULL
`

// Hot path: called on every authenticated PAT request. UNIQUE on
// hashed_key makes this an indexed lookup. Returns NULL when no row
// matches (caller distinguishes miss from error via the sql.ErrNoRows
// sentinel).
//
// The JOIN on users is authority enforcement, not display: the WHERE
// requires the owner to be a live admin (is_admin = 1, disabled_at
// NULL), so demoting or disabling the owner invalidates every one of
// their tokens on the next request instead of freezing admin
// authority at mint time. A token whose owner fails the check
// surfaces as sql.ErrNoRows -> 401, identical to a revoked token.
func (q *Queries) GetUserPATByHash(ctx context.Context, hashedKey string) (UserPat, error) {
	row := q.db.QueryRowContext(ctx, getUserPATByHash, hashedKey)
	var i UserPat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.HashedKey,
		&i.ScopesJson,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUserPATs = `-- name: ListUserPATs :many
SELECT id, user_id, name, hashed_key, scopes_json, created_at, last_used_at, expires_at, revoked_at
FROM user_pats
WHERE user_id = ?1
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListUserPATsParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

// Backs GET /api/v1/users/me/pats -- lists all the calling user's
// PATs, including revoked (so the UI can show "last used 3 days ago,
// revoked yesterday" history). Plaintext is never stored, so the
// "list" response has nothing to redact -- just metadata.
func (q *Queries) ListUserPATs(ctx context.Context, arg ListUserPATsParams) ([]UserPat, error) {
	rows, err := q.db.QueryContext(ctx, listUserPATs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPat{}
	for rows.Next() {
		var i UserPat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.HashedKey,
			&i.ScopesJson,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLiveBootstrapPATs = `-- name: RevokeLiveBootstrapPATs :execrows
UPDATE user_pats
SET revoked_at = COALESCE(revoked_at, unixepoch())
WHERE user_id = ?1 AND name = 'bootstrap' AND revoked_at IS NULL
`

// Crash-recovery hygiene, run inside the bootstrap mint transaction:
// a previous boot killed between the commit and the file write leaves
// a live name='bootstrap' wildcard row whose plaintext never reached
// disk; the next boot's re-mint would otherwise accumulate live
// bootstrap tokens forever (round-5 review). Revoking prior live
// bootstrap rows for this user in the same tx keeps exactly one
// live bootstrap token at any time. Scoped to the bootstrap user +
// the reserved name so an admin's own 'bootstrap'-named token on a
// different account is untouched.
func (q *Queries) RevokeLiveBootstrapPATs(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeLiveBootstrapPATs, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserPAT = `-- name: RevokeUserPAT :execrows
UPDATE user_pats
SET revoked_at = COALESCE(revoked_at, unixepoch())
WHERE id = ?1 AND user_id = ?2 AND revoked_at IS NULL
`

type RevokeUserPATParams struct {
	ID     int64
	UserID int64
}

// Soft-delete by setting revoked_at. The WHERE keeps it to live rows
// owned by the calling user, so the affected-row count is
// meaningful: 1 = revoked, 0 = the id doesn't exist, isn't live, or
// belongs to another user -- the caller maps 0 to a 404 instead of
// reporting a silent false success.
func (q *Queries) RevokeUserPAT(ctx context.Context, arg RevokeUserPATParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserPAT, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserPATByHash = `-- name: RevokeUserPATByHash :execrows
UPDATE user_pats
SET revoked_at = COALESCE(revoked_at, unixepoch())
WHERE hashed_key = ?1 AND revoked_at IS NULL
`

// Bootstrap orphan cleanup: if the plaintext file write fails after
// the mint transaction committed, the row is a live non-expiring
// wildcard PAT no one can ever present. Revoke it (soft-delete, not
// a hard delete -- the no-delete audit invariant holds) so the DB
// matches reality. Keyed by hashed_key because the bootstrap path
// knows the hash, not the row id.
func (q *Queries) RevokeUserPATByHash(ctx context.Context, hashedKey string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserPATByHash, hashedKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchUserPAT = `-- name: TouchUserPAT :exec
UPDATE user_pats
SET last_used_at = ?2
WHERE hashed_key = ?1 AND (last_used_at IS NULL OR last_used_at < ?2 - 60)
`

type TouchUserPATParams struct {
	HashedKey  string
	LastUsedAt sql.NullInt64
}

// Best-effort last_used_at bump on every authenticated request. The
// auth path calls this async (go func() + background write); a flush
// failure is logged but never propagates back to the request -- the
// operator-visible cost of an auth path is one indexed PK lookup,
// not a write. The WHERE last_used_at IS NULL OR last_used_at < ?3
// throttles the writes: only the first request in any 60s window
// actually mutates the row, so a flood of requests from one token
// doesn't generate a flood of disk writes. Keyed by hashed_key so
// the middleware can call this without a second lookup.
func (q *Queries) TouchUserPAT(ctx context.Context, arg TouchUserPATParams) error {
	_, err := q.db.ExecContext(ctx, touchUserPAT, arg.HashedKey, arg.LastUsedAt)
	return err
}
